### ISSUE TITLE
Uncaught exception 'Zend_Acl_Exception' with message 'Resource 'gestion_parametrages' not found'

### ISSUE THREAD

**Issue by fbeauchamp** [SDIS62/prevarisc#100]
Je viens de mettre à jour prevarisc, j'ai ce message d'erreur : 

[Fri Feb 07 10:42:37 2014] [error] [client 192.168.23.18] PHP Fatal error:  Uncaught exception 'Zend_Acl_Exception' with message 'Resource 'gestion_parametrages' not found' in /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Acl.php:365
Stack trace:
#0 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Acl.php(846): Zend_Acl->get('gestion_paramet...')
#1 /var/www/prevarisc/application/plugins/ACL.php(94): Zend_Acl->isAllowed('Pr??ventionnist...', 'gestion_paramet...', 'admin')
#2/var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php(309): Plugin_ACL->preDispatch(Object(Zend_Controller_Request_Http))
#3 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker->preDispatch(Object(Zend_Controller_Request_Http))
#4 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#5 /var/www/prevarisc/application/Bootstrap.php(21): Zend_Application_Bootstrap_Bootstrap in /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php on line 312, referer: http://prevarisc.sdis71.fr/

**Comment by kdubuc** [comment]
Avez vous fait un forward depuis le fichier Mysql Workbench ?
Cette erreur est générée par l'absence de ressources disponibles en base.

**Comment by fbeauchamp** [comment]
Oui , même problème
Je viens même de purger et reconstruire la base, sans succès

Florent

**Comment by kdubuc** [comment]
Pouvez vous me confirmer que la ressource 'gestion_parametrages' est bien présente dans la table resources ?
Les ACL sont stockées en cache, purgez le cache APC (http://stackoverflow.com/questions/911158/how-to-clear-apc-cache-entries) pour forcer le rechargement du cache. (Si vous êtes en environnement autre que production, le cache se régénère au bout de 60 secondes, sinon c'est une heure)

**Comment by fbeauchamp** [comment]
C'était le cache . Maintenant, tout fonctionne

Merci

**Comment by kdubuc** [comment]
Je close alors ! ;)
