### ISSUE TITLE
$config_security['salt'] n'est pas  documenté

### ISSUE THREAD

**Issue by fbeauchamp** [SDIS62/prevarisc#101]
Bonjour, 

le salt qui était constant est maintenant une variable. Cette variable n'est pas documenté 

Dans quel fichier faut il le déclarer ( pour rappel l'ancien valait 7aec3ab8e8d025c19e8fc8b6e0d75227 ) 

Merci

Florent

**Comment by kdubuc** [comment]
Il faut créer un fichier secret.ini dans application/configs

Et placer ceci dedans : 

``` ini
; Paramètres de configuration de toutes les données sensibles du projet

[general]
ldap.host = 
ldap.port = 
ldap.username = 
ldap.password = 
ldap.baseDn = 
security.salt = [--SALT-A-PLACER-ICI--]

[development : general]
; Paramètres présents dans db.ini

[testing : general]
; Paramètres présents dans db.ini

[staging : general]
db.host = 
db.user = 
db.password = 
db.dbname = 

[production : general]
db.host = 
db.user = 
db.password = 
db.dbname = 
```

C'est un fichier contenant toutes les données sensibles, dont le salt permettant de hasher les mots de passe. Vous pouvez, soit réutiliser le salt (mais comme celui est public, il n'a plus d'intérêt au niveau sécurité) soit en générer un nouveau (c'est un MD5 de 32 caractères).

Attention, si vous en générez un nouveau, il faut recréer les comptes non-ldap pour régénérer leur mot de passe.

**Comment by fbeauchamp** [comment]
merci
