### ISSUE TITLE
Création établissement : Undefined index ID_COMMISSION

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#135]
A la création d'un nouvel établissement, si aucune commission n'a été renseignée, un warning apparaît dans la sortie (ou dans les logs) si la redirection n'est pas effectuée : undefined index ID_COMMISSION.

Le problème se situe dans la classe Service_Etablissement dans le switch sur le type d'établissement qui présume d'un ID_COMMISSION existe.

**Comment by kdubuc** [comment]
Merci pour le feedback, je m'en occupe !

**Comment by kdubuc** [comment]
Idem donc pour : 

Undefined index: NUMERO_ETABLISSEMENTPLAN
Undefined index: DATE_ETABLISSEMENTPLAN
Undefined index: MISEAJOUR_ETABLISSEMENTPLAN
