### ISSUE TITLE
Commissions : membres : bouton supprimer invisible sur écran portable

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#143]
Sur écran d'ordinateur portable (15 pouces wides), le bouton supprimer un membre de commission est invisible, sauf scroll latéral, lui-même dur à trouver :

![image](https://f.cloud.github.com/assets/6736730/2421311/586b53fa-ab80-11e3-96b0-a07f6601518e.png)

**Comment by kdubuc** [comment]
Cette partie doit de toutes façons refaite via l'utilisation du bootstrap, des services layers, et du cache (assez lent quand il y a beaucoup de membres). Je note le problème visuel pour la refonte prochaine.
