### ISSUE TITLE
Profil : Problèmes dans la modification

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#148]
La modification du profil utilisateur pose problème à plusieurs niveaux :
- la modification est effectuée dans une popup et les champs sont difficile à atteindre sauf scroll important (voir pj)
- la modification de l'image de profil ouvre une popup derrière la 1ère popup
- le chargement d'une nouvelle photo de profil se termine en : 
  ( ! ) Fatal error: Class 'GD_resize' not found in /prevarisc-master-git2/application/controllers/UserController.php on line 59

![image](https://f.cloud.github.com/assets/6736730/2439688/65c32b50-adff-11e3-997f-65b6435c428b.png)

**Comment by kdubuc** [comment]
Pour ce qui est de "Class 'GD_resize' not found", c'est étrange, normalement la dépendance est chargée par l'autoload du composer. Elle est d'ailleurs utilisée pour l'ajout des pièces jointes des établissements sans problèmes.

Euh, peut être de forcer un reset des dépendances via composer résoudrait le problème.

Pour ce qui est du redesign, c'est prévu, je dois faire une passe dessus, comme j'ai pu le faire pour établissement.

**Comment by A511701** [comment]
Indice : GD_resize ou GD_Resize... telle est la question ;-)

**Comment by kdubuc** [comment]
Ouch ... Bien joué ! :+1:
