### ISSUE TITLE
recherche utilisateur

### ISSUE THREAD

**Issue by bmpmsic13** [SDIS62/prevarisc#166]
Dans la page "recherche", onglet "utilisateur", si on ne remplit pas le champ de recherche on trouve bien tous les utilisateurs. Mais si on marque le nom d'une personne existante, (ou prenom ou login), la recherche est vide

**Comment by kdubuc** [comment]
Ce problème est résolu dans la version qui arrive début de semaine prochaine.
La recherche des utilisateurs a été désactivée, et toute leur gestion (mot de passe, nom, prénom etc ) est déléguée à un référent Prevarisc qu'il vous faudra désigner. Il aura accès à une partie de l'administration pour gérer tout cela.

Cela concerne aussi les #164  #165
