### ISSUE TITLE
php5.4 ou 5.3

### ISSUE THREAD

**Issue by fbeauchamp** [SDIS62/prevarisc#169]
application/plugins/acl.php utilise la syntaxe de php 5.4+ , hors la doc de prevarisc parle de compatibilité avec php5.3+ 
ligne 16 : `$service_user->updateLastActionDate(Zend_Auth::getInstance()->getIdentity()['ID_UTILISATEUR']);`

A noter que php 5.3 semble toujours être la version de base sur ubuntu

**Comment by kdubuc** [comment]
La version de PHP minimale demandée est bien la 5.4 maintenant. Nous n'avons pas eu encore le temps de mettre à jour la doc. Tout cela sera bien indiqué lors de la montée de version officielle.
