### ISSUE TITLE
Installation défectueuse

### ISSUE THREAD

**Issue by youenncreach** [SDIS62/prevarisc#208]
Bonjour,
Je viens d'installer Prevarisc master sur une machine Windows XP avec EasyPHP :
- Installation de Zend Framework 1.12.7 : ok
- Installation de MySql et du MCD : ok
- Installation des dépendances : ok
  J'ai fait quelques essais :
- phpinfo(); : ok
- génération d'un pdf avec Zend : ok

Dès que, je lance /public/index.php, j'obtiens une page vierge.

Quand je lance /tests/Bootstrap.php, j'obtiens le message :
Fatal error: Uncaught exception 'Zend_Cache_Exception' with message
'The apc extension must be loaded for using this backend !' in
C:\Program Files\Esy\data\localweb\projects\prv\vendor\zendframework\zendframework1\library\Zend\Cache.php:209
Stack trace: #0 C:\Program
Files\Esy\data\localweb\projects\prv\vendor\zendframework\zendframework1\library\Zend\Cache\Backend\Apc.php(59):
Zend_Cache::throwException('The apc extensi...') #1 C:\Program
Files\Esy\data\localweb\projects\prv\vendor\zendframework\zendframework1\library\Zend\Cache.php(153):
Zend_Cache_Backend_Apc->__construct(Array) #2 C:\Program
Files\Esy\data\localweb\projects\prv\vendor\zendframework\zendframework1\library\Zend\Cache.php(94):
Zend_Cache::_makeBackend('APC', Array, false, false) #3 C:\Program
Files\Esy\data\localweb\projects\prv\application\Bootstrap.php(35):
Zend_Cache::factory('Core', 'APC', Array) #4 C:\Program
Files\Esy\data\localweb\projects\prv\vendor\zendframework\zendframework1\library\Zend\Application\Bootstrap\BootstrapAbstract.php(681):
Boots in C:\Program
Files\Esy\data\localweb\projects\prv\vendor\zendframework\zendframework1\library\Zend\Cache.php
on line 209

J'ai installé php_apc.dll. Elle est bien visible dans phpinfo(); mais dès que je lance du php avec Zend le serveur ne répond plus.

Et quand je lance /tests/ApplicationTest.php :
Fatal error: Class 'PHPUnit_Framework_TestCase' not found in
C:\Program Files\Esy\data\localweb\projects\prv\tests\ApplicationTest.php
on line 4

Avez-vous une idée ?

Merci de votre aide.

**Comment by A511701** [comment]
Bonjour,

Pouvez-vous nous copier le contenu d'un php -i ou mettre en pièce jointe la page web html du phpinfo() ?
Avez-vous précisé dans le php.ini l'extension + l'activation de l'extension ?
extension=php_apc.dll
[...]
[APC]
apc.enabled = 1

Merci,
Vincent MICHEL

**Comment by youenncreach** [comment]
Bonjour,
phpinfo() : http://dl.free.fr/gZkoyzB8b
J'ai ajouté les lignes suivantes dans le php.ini
extension=php_apc.dll
[APC]
apc.enabled=1
apc.shm_size=512M
apc.num_files_hint=10000
apc.user_entries_hint=10000
apc.max_file_size=5M
apc.stat=0
apc.optimization=0
apc.shm_segments=1
apc.enable_cli=1
apc.cache_by_default=1
apc.include_once_override=1

Merci

**Comment by A511701** [comment]
Je n'ai pas accès au lien sur mon réseau qui est bloqué par le proxy. Je regarde ce soir.
D'une manière générale, je vous déconseille Windows pour travailler sur Prévarisc, mais plutôt d'utiliser une plate-forme linux comme Debian, CentOS....

**Comment by kdubuc** [comment]
C'est effectivement un problème au niveau du serveur, l'extension APC doit être activée. Je close.
