### ISSUE TITLE
Accès fiche Etablissement problème de droits

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#211]
Bonjour,
Lorsque je souhaite accéder à une fiche Etablissement, cela est impossible, voici l'erreur retourné (j'ai bien renseigné la Gestion des ressources spécialisées):

Notice: Undefined offset: 4 in /var/www/prevarisc/application/plugins/ACL.php on line 93
Notice: Undefined offset: 5 in /var/www/prevarisc/application/plugins/ACL.php on line 94
Notice: Undefined offset: 6 in /var/www/prevarisc/application/plugins/ACL.php on line 95

Dans l'attente d'une réponse,

**Comment by kdubuc** [comment]
Pouvez vous me donner l'"Identifiant de la ressource" des établissements ? ça doit être du genre : etablissement_erp_0_0_0_0_0

**Comment by diasn** [comment]
identifiant de la ressource : etablissement_erp_1-2-3-116-4-5-6-117-118-119-7-121-124-8-9-10-11-12-125-13-14-15-16-17-18-19-20-21-22-23-24-25-26-127-27-28-29-30-31-128-32-33-34-35-36-37-38-129-39-40-41-130-42-131-43-46-47-132-48-49-50-51-52-53-104-122-100-105-106-107-108-54-126-55-56-

**Comment by kdubuc** [comment]
ah, pour sélectionner l'ensemble des types / activités, vous avez tout coché ?
Si l'ensemble des types / activités ne sont pas cochés, la matrice des droits les ignore par défaut.
Et là, la longueur de la ressource est trop grande, d'où le bug. Essayez de supprimer cette ressource, et recréez en une sans cocher les types / activités.

**Comment by diasn** [comment]
problème résolu merci.
