### ISSUE TITLE
Paramétrage de l'application google maps

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#212]
Bonjour,
Comment paramétrer la clé pour utiliser google maps dans prevarisc?

**Comment by A511701** [comment]
Bonjour,
Il vous faut ajouter dans un fichier .ini comme secret.ini ou application.ini l'entrée suivante :

```
googlemap.key = 939DFSODJKISDIFJD
```

Avec votre clé bien sûr ;)
