### ISSUE TITLE
génération d'un rapport dans un dossier

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#213]
lors de la génération du rapport dans un dossier une erreur survient lors de l'ouverture de open office:
![image](https://cloud.githubusercontent.com/assets/6367639/3300889/97faf026-f625-11e3-916c-1e8e923e32cf.png)

**Comment by kdubuc** [comment]
Hum, qu'est ce que tu en pense @alucard62 ?

**Comment by ghost** [comment]
C’est un problème dans le document contenant les champs de fusions. 
Ce problème est assez aléatoire et est difficile à identifier. Il peut être provoqué par un style, un tableau, un élément particulier du  document.
Je vous conseille de repartir d’un fichier vierge et d’y intégrer vos données en faisant des tests au fur et à mesure pour repérer d’où vient l’erreur.

**Comment by A511701** [comment]
De notre côté, un autre problème souvent rencontré est que Prevarisc ne reconnait pas le champ de fusion même s'il est présent. La faute au balisage XML aléatoire et surtout à l'expression régulière de la librairie qui est un peu trop restrictive.

**Comment by kdubuc** [comment]
Cela viendrait donc de la librairie utilisée, nous ne pouvons pas faire grand chose pour le moment sur cette branche de Prevarisc. Je vous tient au courant si il y a un changement dans les libs / architecture du projet à court / moyen terme.

**Comment by A511701** [comment]
La lib me semble en effet simple et "fait le boulot", mais démontre rapidement des limites. Un changement à ce niveau serait intéressant.

**Comment by kdubuc** [comment]
Si seulement on pouvait revenir aux origines du projet, un coup de Dependency Inversion Principle, et ça aurait pu être réglé très rapidement en switchant de lib et de service.
C'est dans le même esprit que de fournir des Service Providers différents répondant à une interface pré-définie pour le géo-codage par exemple.

Il y aura de toutes façons une évolution de la structure de Prevarisc.
