### ISSUE TITLE
Recherche d'Etablissements

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#215]
Lors de la recherche d'établissements:
- Si on recherche par la cellule en haut à droite ou par la cellule dans l'onglet Etablissement dans recherche détaillée: on n'obtient pas le même nombre d'établissements malgré la même saisie de caractères.
- Si on fait une recherche avec zone géographique et que l'on choisi une commune, quand on retourne sur recherche géographique sans rien saisir et que l'on revient sur recherche détaillée, la dernière commune sélectionnée reste renseignée. (il faudrait que cela réinitialise la zone de recherche à 0)
- La recherche par id établissement semble ne pas fonctionner?

**Comment by kdubuc** [comment]
- Vous voulez dire qu'il y a une différence de nombre de résultats dans "Lister" et "Recherche" ?
- C'est un effet voulu, la recherche géographique est un critère semi-persistant, utile lors de multi recherches sur la même zone géographique ;
- Il faut taper un "# + ID DE L'ETABLISSEMENT" dans la zone de recherche de l'établissement

**Comment by diasn** [comment]
d'accord nous prenons en compte.

**Comment by diasn** [comment]
les bugs ont disparus en ce qui concerne la recherche, je close
