### ISSUE TITLE
Fiche Etablissement - ajout d'une Adresse

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#217]
Lors de l'ajout d'une adresse, on fait retirer l'adresse ancienne.
Quand on sauvegarde, cela duplique l'adresse retirer au lieu de la supprimer.
On se retrouve avec une liste de toutes les anciennes adresses à chaque sauvegarde de la fiche.

**Comment by A511701** [comment]
Bonjour,
Ce problème avait été identifié en début de semaine, lié à l'historisation et corrigé par pull request #214.
Une mise à jour de prevarisc est nécessaire.

**Comment by kdubuc** [comment]
Je close ici, et je garde le PR #214
