### ISSUE TITLE
Supprimer un Dossier

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#220]
Lors de la création d'une dossier par erreur, peut-on supprimer le dossier et comment?

**Comment by A511701** [comment]
A ma connaissance, on ne peut supprimer un dossier.
Par contre, vous pouvez le renommer, changer le type et la nature si vous vous êtes trompés.

**Comment by A511701** [comment]
@kdubuc vous confirmez?

**Comment by kdubuc** [comment]
C'est exactement ça, nous n'avons pas donné la possibilité de supprimer un dossier / établissement dans Prevarisc car cela aurait un impact sur les données importantes gravitant autour (l'avis, les stats, etc ). Vous pouvez par contre renommer le dossier, et le "redessiner" complètement.

**Comment by diasn** [comment]
D'accord nous prenons en compte.
