### ISSUE TITLE
Lier un dossier à un Etablissement

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#221]
Lors de la liaison d'un dossier à un établissement, la commune de l'etablissement n’apparaît pas dans la liste déroulante.
Cela pose problème quand un établissement à le même nom dans deux communes différentes, on ne sait pas lequel choisir.

**Comment by kdubuc** [comment]
Exact, nous allons faire le nécessaire. ;)

**Comment by kdubuc** [comment]
Je réouvre pour garder ce ticket visible le temps de la correction ! ;)
