### ISSUE TITLE
Choix activité lors de la création d'un Etablissement

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#222]
Lors du choix de l'activité, la liste déroulant de choix du type propose la lettre.
Lors du choix dans la liste déroulante du détails de l'activité, il y a un décalage et des types de la mauvaise lettre apparaissent.

**Comment by A511701** [comment]
Bonjour,
Quel navigateur utilisez vous ?
Pouvez-vous préciser l'exemple précis où vous rencontrez le problème ?

**Comment by diasn** [comment]
Nous utilisons CHrome, voici une copie d'écran en exemple pour l'activité N on propos Etablissment de Culte en fin de liste ce qui est faux :
![image](https://cloud.githubusercontent.com/assets/6367639/3325492/b3f00fd0-f78f-11e3-8cd7-5495ef118fe8.png)

**Comment by A511701** [comment]
Bonjour,

Pouvez-vous lister les erreurs d'association ? ou avez-vous un document qui référence les bonnes associations pour que nous puissions corriger ?
Exemple : N => Etablissement du culte ====> P => Etablissement du culte

**Comment by kdubuc** [comment]
Effectivement, il y a un problème.
Mais chez moi, c'est okay, il n'y a pas "Etablissement du culte" dans N.

Vous avez le même souci @alucard62 & @A511701 ?

**Comment by kdubuc** [comment]
je peux close ?
