### ISSUE TITLE
Erreur generation convocations commissions

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#223]
Bonjour, voici l'erreur lors de la génération des convocations avec les documents type du SDIS62:
Stack trace:
#0 /var/www/prevarisc/application/views/scripts/calendrier-des-commissions/generationconvoc.phtml(51): Odf->__construct('/var/www/prevar...')
#1 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/View.php(108): include('/var/www/prevar...')
#2 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/View/Abstract.php(888): Zend_View->_run('/var/www/prevar...')
#3 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('calendrier-des-...')
#4 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('calendrier-des-...', NULL)
#5 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#6 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#7 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#8 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('generationconvo...')
#9 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(101): Zend_Controller_Front->dispatch()
#11 /var/www/prevarisc/application/Bootstrap.php(21): Zend_Application_Bootstrap_Bootstrap->run()
#12 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Application.php(366): Bootstrap->run()
#13 /var/www/prevarisc/public/index.php(37): Zend_Application->run()
#14 {main}

Request Parameters:

array (
  'controller' => 'calendrier-des-commissions',
  'action' => 'generationconvoc',
  'module' => 'default',
  'dateCommId' => '19',
)    

pouvez-vous m'aider?

**Comment by kdubuc** [comment]
Quelle est l'erreur en question ?
Il nous faudrait plus que la stack trace pour que de notre côté nous puissions enquêter sur le bug. De notre côté, et après plusieurs tests, la génération des convocations fonctionne, les droits d'écriture sont bien appliqués sur les dossiers ?

**Comment by diasn** [comment]
je fais plus de test et je vous tiens au courant.

**Comment by kdubuc** [comment]
je peux close ?
