### ISSUE TITLE
Dossier: Etude et reprise des prescriptions dossier précédent

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#224]
Lorsque l'on ajoute une nouvelle prescription dans un dossier et que l'on valide, si l'on revient en ajouter de nouvelles, le bouton reprise des prescription dossier précédent n'est plus accessible.

Ne pourrait-on pas le laisser accessible?

**Comment by kdubuc** [comment]
Cette fonction n'est qu'un raccourci pour accélérer la première saisie des prescriptions. Il faut les gérer manuellement ensuite.
