### ISSUE TITLE
Création Etablissement

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#225]
Lors de la création d'un Etablissement, l'Identifiant propose une valeur du type: SDIS29-...
Pourriez-vous le rendre paramétrable?

Par exemple pour le SDIS 07 avec E007?

**Comment by A511701** [comment]
Bonjour,
C'est une coquille issue d'une démonstration faite au SDIS29 pour prouver la faisabilité d'effectuer une reprise + un fonctionnement nominal sur des identifiants fonctionnels auto-générés.
Normalement, ce point a dû être supprimé depuis.

**Comment by diasn** [comment]
ok, je close
