### ISSUE TITLE
Alertes dans tableau de bord

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#227]
Comment sont paramétrés les dossiers qui s'affichent dans la zone alerte du tableau de bord, et les icône de type "important" ou "info"?

**Comment by A511701** [comment]
Il n'y a pour l'instant pas de paramétrage à ce niveau. L'importance a été déterminée par rapport à l'importance fonctionnelle réelle de l'alerte remontée. Si vous jugez qu'un niveau doit être modifié / modulé, vous pouvez nous le préciser.

**Comment by diasn** [comment]
d'accord, cela serait-il possible de le rendre paramétrable, ou sinon nous fournir les règles paramétrées  ?

**Comment by kdubuc** [comment]
Pour l'instant, tout est dans le code en "dur". Pour rendre l'ensemble paramétrable, il faut créer une interface d'administration du tableau de bord, ce n'est pas encore prévu à l'heure actuelle.

**Comment by massisad** [comment]
Voici les alertes implémentées :
- établissements avec un avis défavorables (durée précisée dans l'affichage de  l'alerte par exemple : depuis 10 jours).
- dossier avec date de commission échue et pas d'avis rendu
- courriers sans réponses depuis plus de 5 jour (durée précisé dans l'alerte).
- établissements sans prochaine visite périodique programmée alors que le statut est ouvert
- établissements sans préventionnistes

Pour informations :
- les alertes sont affichées dans l'ordre de leurs importances  et selon le profil de l'utilisateur
- un lien vers le dossier ou établissement ou commission dans chaque alerte pour régler le problème
