### ISSUE TITLE
Fiche Etablissement: descriptif

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#229]
Dans le descriptif technique, il faudrait permettre la saisie au format heures/minutes, car actuellement c'est un entier.

Hors, il y a des stabilité au feu en 1/2 heures.

**Comment by kdubuc** [comment]
Nous allons surement modifier l'unité affichée (heure en minute)

**Comment by kdubuc** [comment]
C'est okay, l'unité est maintenant la minute, vous devez mettre à jour depuis la 2.x et éxecuter la migration https://github.com/SDIS62/prevarisc/blob/2.x/sql/migrations/2.2-15-surfacesminutes.sql
