### ISSUE TITLE
Dossiers: textes applicables

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#231]
Dans le choix des textes applicables dans la fiche dossier, aucune validation ou sauvegarde des modifications n'est proposée après les avoir cochés.
Ne devrait-on pas faire comme pour les textes applicables dans le fiche Etablissement?

**Comment by kdubuc** [comment]
C'est prévu, il faut que l'on réalise une deuxième passe sur la partie dossier pour harmoniser l'interface.
