### ISSUE TITLE
Extractions statistiques

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#232]
En ce qui concerne les extraction statistiques, les extractions seront t'elles figées, où pourrons-nous générer nos propres extraction et les intégrer dans le logiciel?
si oui, quel est le logiciel utilisé?

**Comment by kdubuc** [comment]
Pour les requêtes personnalisées, nous recommandons iReport pour requêter la base. Après n'importe quel BO pourrait faire l'affaire.
