### ISSUE TITLE
Mot de passe root

### ISSUE THREAD

**Issue by youenncreach** [SDIS62/prevarisc#233]
Bonsoir,
Quel est le mot de passe de connexion du premier utilisateur root ?
Ce n'est pas "root" comme indiqué dans la documentation.
Merci

**Comment by kdubuc** [comment]
Je pense que ceci peut vous aider :

https://github.com/SDIS62/prevarisc/issues/101

**Comment by youenncreach** [comment]
Bonjour,
Je fonctionne sans ldap.
J'ai ajouter la ligne dans mon secret.ini : pas mieux.
Ci-après mon secret.ini :
<i>
[general]
ldap.host = 
ldap.port = 
ldap.username = 
ldap.password = 
ldap.baseDn = 
security.salt = [7aec3ab8e8d025c19e8fc8b6e0d75227]
</i>
<i>
[production]
resources.db.params.host = localhost
resources.db.params.username = root
resources.db.params.password = root
resources.db.params.dbname = prevarisc
</i>

**Comment by kdubuc** [comment]
Et sans les crochets ?

**Comment by youenncreach** [comment]
Non, pas mieux, toujours le même message "Aie, Les identifiants ne correspondent pas".
User : root
Passwd : root

**Comment by kdubuc** [comment]
avez vous une base de données remplies ? notamment la table utilisateurs ?

**Comment by youenncreach** [comment]
Non, le seul user est root. C'est la toute première connexion à la base.

**Comment by youenncreach** [comment]
C'est bon, j'ai fait une petite modification dans SessionController.php :-), puis une modification du mot de passe par l'interface d'administration.
Merci pour votre aide.

**Comment by SDIS91** [comment]
Bonjour

Quelle est cette petite modification? J'ai le même problème.

Merci

**Comment by fbeauchamp** [comment]
https://github.com/SDIS62/prevarisc/blob/2.x/application/controllers/SessionController.php ligne 55 
en remplaçant   `if ($adapter->authenticate()->isValid())` par        `if (true)` cela devrait contourner l'authentification

**ne pas oublier de le remettre après**
Votre problème est vraisemblablement lié a un SALT mal paramétré dans les variable d'environnement

**Comment by SDIS91** [comment]
Merci ça marche mais il semble que le compte root n'a pas accès au menu administration:
"Vos droits ne permettent pas d'accéder à cette page !"
