### ISSUE TITLE
[info] Installation de test

### ISSUE THREAD

**Issue by youenncreach** [SDIS62/prevarisc#234]
Bonjour,
Je viens de finir une procédure d'installation de test de Prevarisc.
A lire sur http://goo.gl/HjAc8c
Bonne continuation.

**Comment by kdubuc** [comment]
Wow, c'est génial !
Vous pouvez aussi forker le projet, et modifier directement la documentation d'installation, et nous la proposer ici !

En tous cas, merci pour votre contribution ! :-)

**Comment by fbeauchamp** [comment]
Dans la même série, est ce que quelqu'un à envisagé un docker ?

**Comment by kdubuc** [comment]
Un docker ? Ce docker http://www.docker.com/ ?

**Comment by fbeauchamp** [comment]
Oui
L'idée serai de charger la base MySQL, et les documents  sur le serveur et de n'avoir qu'a lancer prevarisc dans le container docker 

L'install pourrait devenir : 
- installer mysql 
- remplir mysql avec mysqlwrokbench
- remplir les données du secret.ini
- lancer le dockerfile

**Comment by kdubuc** [comment]
Hum, je connais pas vraiment cette techno, déjà entendu parler sur twitter, mais j'ai pas été plus loin.
Si tu as quelque chose à nous proposer en PR, pourquoi pas !

**Comment by youenncreach** [comment]
Bonsoir,
J'ai proposé une modification du fichier documentation_installation.md et inséré prevarisc.sql dans le dossier /docs/db/ de mon fork.

**Comment by fbeauchamp** [comment]
sur ubuntu les packages zend s'appellent :  libzend-framework-zendx-php libzend-framework-php

**Comment by kdubuc** [comment]
Pas besoin d'installer Zend via apt, le composer s'en charge !
Vous pouvez proposer votre documentation en pull request pour que j'ajoute votre contribution dans le dépôt officiel

**Comment by A511701** [comment]
De notre côté, nous avons industrialisé l'installation et nous utilisons un script shell
