### ISSUE TITLE
Prérequis d'installation

### ISSUE THREAD

**Issue by didiercampion** [SDIS62/prevarisc#236]
Bonjour,

Pouvez-vous confirmer les prérequis pour la version 2.0.

Je m'explique , je viens de faire une installation sur une Debian 6.0, la version PHP supportée officiellement est la 5.3, ce qui semble conforme à la doc d'installation. J'ai rencontré le problème suivant  lors de l’accès à l'application :

PHP Parse error:  syntax error, unexpected '[' in /var/www/prevarisc/application/plugins/ACL.php on line 16

Problème visiblement lié à la version PHP 5.3. En forçant la migration en PHP 5.4, le problème disparaît.... même si d'autres apparaissent du fait que la version 5.4 ne soit pas officiellement supportée sur debian 6.

Alors PHP 5.3 ou PHP 5.4 ???

Cordialement
Didier

**Comment by kdubuc** [comment]
PHP 5.4, la documentation est en pleine mise à jour, vous pouvez consulter l'avancée ici grâce à un de nos contributeurs : #235 ;-)
La version 5.4 n'est pas officiellement supportée sur debian 6, sur la 7ème version, c'est le 5.4 qui est conseillée. Vous pouvez ajouter un dépôt non-officiel comme ceci pour avoir le support du 5.4 : http://memo-linux.com/installer-php-5-4-sur-debian-squeeze/

**Comment by didiercampion** [comment]
Merci de votre retour.

C'est effectivement la doc que j'ai suivi pour la bascule en 5.4, mais visiblement plusieurs dépendances ont "sautées" lors de la migration, je vais refaire un test....

Cordialement
