### ISSUE TITLE
Accès aux pièces jointes des Dossiers

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#240]
Lorsque je cherche à accéder aux pièces jointes, voici l'erreur 

![image](https://cloud.githubusercontent.com/assets/6367639/3396841/7125c498-fd15-11e3-86bd-f85562545170.png)

Auriez-vous une solution à me proposer?

**Comment by kdubuc** [comment]
le fichier 13060647.doc existe t'il dans un des sous dossiers de prevarisc/data/ ?

**Comment by kdubuc** [comment]
je peux close ?
