### ISSUE TITLE
Gestion des ressources spécialisées

### ISSUE THREAD

**Issue by sla33** [SDIS62/prevarisc#246]
2 problèmes :  il faudrait pouvoir choisir "tous les types" quand on créé une ressource spécialisée, c'est très laborieux (et long) de cocher une à une toutes les case. D'autre part, si on met beaucoup de types, on ne peut plus ensuite accorder ce droit au niveau des profils : en effet le nom de la ressource spécialisée reprend tous les types les uns à la suite des autres. La ligne est trop longue et comme il n'y a pas d'ascenseur horizontal on n'a plus accès aux cases à cocher pour indiquer qu'on veut accorder ce droit à ce profil.

**Comment by kdubuc** [comment]
En fait dans la gestion des ressources spécialisées, le fait de ne choisir aucun type, revient à dire tous les types. C'est pas vraiment intuitif, je vous l'accorde. Mais cela évite de tout cocher.
