### ISSUE TITLE
Affectation d'un préventionniste lors de la création d'un nouvel établissement

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#249]
Sur quel critère sont proposés les "préventionnistes conseillés", lors de l'ajout d'un nouvel établissement?

**Comment by kdubuc** [comment]
- Site : Préventionnistes des groupements de communes ;
- Etablissement / Habitation / EIC / IGH : Préventionnistes du site ou des groupements de commune ;
- Cellule : Préventionnistes de l'établissement parent.
