### ISSUE TITLE
Ouverture des pièces-jointes des dossiers dans le navigateur internet

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#250]
Pour ceux qui ont récupéré les pièces jointes .doc des dossiers de ERP vers prevarisc, lorsque l'on veux les ouvrir dans prevarisc cela génère une erreur fichier introuvable.
Le problème vient du fait que le nom de la pièce jointe se termine en .DOC en majuscule et que l'adresse dans la fenêtre du navigateur internet recherche le document .doc en minuscule.
Peut-on corriger cela ? ou dois-je renommer mes fichiers avec .doc en minuscule ?

**Comment by kdubuc** [comment]
Nous avons modifié la méthode de téléchargement d'un fichier, rencontres-tu encore ce bug @diasn ?

**Comment by diasn** [comment]
Je test et je vous dis-ça
