### ISSUE TITLE
Erreur lors de la création de membres dans les commissions

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#251]
Lors de l'ajout de membres pour les commissions, voici l'erreur généré:

![image](https://cloud.githubusercontent.com/assets/6367639/3655103/f788bde2-1174-11e4-97e8-b8a2a6599b99.png)

Avez-vous une solution à mon problème?

**Comment by kdubuc** [comment]
La nouvelle partie des commissions est intégrée dans la version 3.x en cours de développement https://github.com/SDIS62/prevarisc/tree/3.x
