### ISSUE TITLE
Affecter un préventionniste à un groupement de communes

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#252]
La liste déroulante qui propose les préventionnistes à affecter ne fonctionne pas. Elle propose les 10 premiers de la liste et on ne peut pas sélectionner les autres.

**Comment by kdubuc** [comment]
ça devrait aller beaucoup mieux avec cette mise à jour : https://github.com/SDIS62/prevarisc/commit/fcf65759409dfdf255f37133cced96a3e83f8f78
