### ISSUE TITLE
Accès aux Etablissements liés

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#253]
Lorsque l'on on veut accéder à la fiche d'un établissement lié, cela nous indique que nous n'avons pas les droits.
Hors le groupe de l'utilisateur donne tous les droits dans la ressources.
Bug?

**Comment by kdubuc** [comment]
les droits d'accès aux cellules sont bien spécifiés ?

**Comment by diasn** [comment]
Oui, la ressource spécialisée donne accès à tout.

**Comment by kdubuc** [comment]
Le bug est il résolu ?

**Comment by jacquetj** [comment]
je me trouve dans le même cas de figure. je ne parviens pas à ajouter un établissement même en mettant un maximum de droits.
quelle manipulation est ce que je peux faire?

**Comment by sla33** [comment]
Avez-vous bien créé les ressources spécialisées ? Pour créer une ressource spécialisée pour l'ensemble des types et activité, il suffit de n'en cocher aucune. Vous pouvez ainsi créer 5 ressources spécialisées (une par genre) et ne rien cocher, et vous aurez accès à tout. Une fois la ressource spécialisée créée, il faut l'affecter à chacun des profils utilisateurs.
ça marche chez nous en version 2 (bêta) du juin 2014.

**Comment by diasn** [comment]
Problème résolu, il faut bien créer 1 ressource spécialisée par genre.
