### ISSUE TITLE
Champs de compétence de la commission

### ISSUE THREAD

**Issue by sla33** [SDIS62/prevarisc#257]
Quand je remplis les éléments pour "champ de compétence de la commission" et que je sauvegarde, le logiciel m'indique que les règles ont bien été sauvegardées, cependant :
- quand je sors et que je reviens il n'y a aucune règle
- rien n'apparaît en base de données
  (j'ai également tenté d'appliquer les règles mais le résultat est le même)

D'autre part, le champ "commission" est-il obligatoire pour un établissement  dans PREVARISC ? (question posée dans le cadre de la reprise des données = cet élément ne semble pas renseigné au niveau des établissements dans ERP2)

**Comment by kdubuc** [comment]
Les bugs liés à la gestion des commissions est réglé.
La nouvelle partie des commissions est intégrée dans la version 3.x en cours de développement https://github.com/SDIS62/prevarisc/tree/3.x
La présentation est différente ainsi que le process de sauvegarde.

**Comment by kdubuc** [comment]
Avez vous rencontré ce bug à nouveau sur la version 2.0 ?

**Comment by sla33** [comment]
Je ne suis pas sûre de notre version. Quelle fonctionnalité/écran puis-je regarder qui m'assurerais que je sois en V 2.0 (en tout cas on n'est pas en version supérieure, c'est sûr) ? C'est à dire quel changement visible a eu lieu entre la V1.2 et la V2 ?

**Comment by kdubuc** [comment]
Si vous avez une matrice des droits avec des ressources spécialisées, vous êtes en 2.0 ;)

**Comment by sla33** [comment]
Je pense qu'on est en V2.0 et ça fonctionne : les règles dont bien sauvegardées à l'écran et en base de données
