### ISSUE TITLE
Qu'utilisez-vous comme prescriptions types ?

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#259]
Par défaut la liste des prescriptions types dans Prévarisc est aujourd'hui vide par défaut.
Question : qu'utilisez-vous aujourd'hui comme prescriptions types ?

**Comment by diasn** [comment]
Pour le SDIS 07 nous avons une liste de prescriptions personnalisées.

**Comment by A511701** [comment]
OK, merci !
