### ISSUE TITLE
Génération des rapports

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#260]
La fonction générer les rapports dans les dossiers ne fonctionne pas.
En effet, le rapport est signalé généré, mais il ne se sauvegarde pas sur le serveur.
Dans la liste des pièces jointes on a le nom "Rapport" au lieu d'avoir le numéro de document.

De plus, comment est défini le nom des rapports générés? (exemple: "14080154.odt")

**Comment by kdubuc** [comment]
poke @alucard62 ?

**Comment by ghost** [comment]
La génération de document ne fonctionne absolument pas ?
Aucun document n’est retrouvé même en regardant directement dans le dossier du serveur /var/www/prevarisc/public/data/uploads/pieces-jointes ?

Concernant le document en lui-même, le fichier est enregistré sur le serveur avec un nom de type :
id_de_la_piece_jointe.odt (id_de_la_piece_jointe étant un entier qui s’auto-incrémente)
Dans la liste des pièces jointe le document généré apparait avec le nom « Rapport » et une description de type : « Rapport de l’établissement X généré le xx/xx/xxxx à xx:xx »

**Comment by kdubuc** [comment]
Peut-on close @diasn ?

**Comment by diasn** [comment]
Salut,

Oui on peut close.
Par contre, as tu une réponse à la seconde partie de ma question qui concerne le nom des documents ? (apparement c'est l'année, suivi du numéro préventionniste et du numéro de document généré par le préventionniste, sauf que les numéros de documents ne se suiventt pas.)

**Comment by diasn** [comment]
J'ai eu ma réponse.
tu peux close.
