### ISSUE TITLE
Gestion de l'affichage de la fiche ETABLISSEMENT et DOSSIER

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#261]
La différence entre l'affichage de la fiche Dossier et la fiche Etablissement est peu visible dans le logiciel.
Pourrait-on faire apparaître l'intitulé "DOSSIER" ou "ETABLISSEMENT" en entête, selon la fiche dans laquelle nous sommes? (actuellement on peut seulement le voir dans la barre d'adresse en tout petit.)

**Comment by kdubuc** [comment]
On peut imaginer une icône représentant un dossier, ou un autre type d'indicateur visuel. Je me penche la dessus ;)
