### ISSUE TITLE
Fiche DOSSIER: liste déroulante de choix avis rapporteur et avis commission

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#262]
Il y a un bug d'affichage des listes déroulantes.
Elles proposent plusieurs fois le même avis et celui ci n'est pris en compte à la sauvegarde de la fiche.
![image](https://cloud.githubusercontent.com/assets/6367639/4061503/a666704e-2df8-11e4-8010-b6d9558b0d59.png)

**Comment by kdubuc** [comment]
ça te dit quelque chose Rémi @alucard62 ?

**Comment by ghost** [comment]
Je n’ai jamais rencontré ce bug.
Est-il présent dans tous les dossiers ?
Pouvez-vous vérifier que la table « avis » contient uniquement deux lignes :
- Favorable
- Défavorable

**Comment by kdubuc** [comment]
Nicolas, as tu rencontré à nouveau ce bug ? Pour savoir si l'on doit close ce ticket.

**Comment by diasn** [comment]
Bonjour,
J'ai vérifié, la table avis n'était pas à jour il y avait 4 lignes.
Tu peux close
