### ISSUE TITLE
Numero de version à afficher

### ISSUE THREAD

**Issue by sla33** [SDIS62/prevarisc#276]
Pourriez-vous faire en sorte que le numéro de version soit affiché quand on est dans Prevarisc, par exemple dans le bandeau du bas :
(SDIS62 R&D & Ministère de l'intérieur · Conditions d’utilisation · À propos de · Développeurs · Aide · © 2014 Prevarisc)
Ce serait plus simple pour vous donner un numéro de version quand on déclare un bug

**Comment by kdubuc** [comment]
C'est envisageable, le plus dur étant de trouver une sorte d'identification unique d'une version en fonction des commits enregistrés sur celle ci. Je vais voir ce que je peux trouver ! ;)

**Comment by pcano65** [comment]
bonjour,

Peut etre aussi rajouter un champs "version BD" quelque part pour savoir où on en est des mises à jour SQL.

Merci!

**Comment by kdubuc** [comment]
Et voila, le numéro de version fait son apparition ! https://github.com/SDIS62/prevarisc/commit/12a24b3e3fe1e6b7e8e9effebde864d1feabfe95
Il se compose du "nom de la branche actuelle"@"dernier commit"

**Comment by A511701** [comment]
Bonjour,
Petite question : 
- en production, il est déconseillé de conserver des informations de dev. C'est pourquoi nous ne déployons pas de copie de travail git. 
- de plus, l'introduction de cet item dans le footer génère des call filesystem supplémentaires sur toutes les pages.
- enfin, le numéro de commit n'est pas très parlant pour un utilisateur

Je vous propose plutôt un fichier de configuration ou équivalent qui affiche une information en dur qui est changée manuellement.

Qu'en pensez-vous ?

**Comment by sla33** [comment]
Kdubuc m'a demandé sur un autre post si j'avais toujours le problème en V2.0, mais nous n'avons actuellement aucun moyen de savoir dans quelle version nous sommes. Il faut que le numéro de version soit lié à la version et non pas entré manuellement sinon on ne peut relier les anomalies à une version.
Dans les applications récentes dont nous nous dotons, le numéro de version est affiché ainsi sur chaque page.
Je parle bien sûr des versions "officielles" qui sont fournies aux utilisateurs pour tests et production. Au moment de la release, il faut indiquer le numério de version.

**Comment by kdubuc** [comment]
Au niveau des call, j'ai pas vu une grande perte de performance. On peut limiter l'affichage au mode debug si jamais.

Si on ne se trouve pas dans un dossier géré par git, on ne peut pas retrouver automatiquement ou l'on se trouve. Et je me vois mal incrémenter un compteur à chaque petite modification du code .. Pour le numéro de commit, l'utilisateur n'a pas besoin de savoir à quoi cela correspond exactement, il est surtout utile pour le support, on peut savoir a quelle version exacte (date, commit, dernier auteur ..) se trouve la version de l'utilisateur.

Je vais réouvrir le ticket pour donner la parole aux autres contributeurs.

**Comment by A511701** [comment]
Le "problème" avec git, c'est que tout à chacun peut installer une version à partir du dépôt et qu'il existe une quasi infinité de version, en effet.
Je vais dans votre sens sur ce point, sur le fait qu'on ne va pas changer le numéro de version manuellement.
Cependant, si vous êtes d'accord, il serait intéressant de pouvoir fixer en dur une version depuis une variable du vhost ? ou un fichier de configuration ?
Les call filesystem sont très peut nombreux et ne seront pas visible à faible volumétrie. Il s'agit d'une optimisation de performance non bloquante en effet.

**Comment by kdubuc** [comment]
Le problème du vhost, c'est que c'est celui qui installeras Prevarisc qui décidera dans quelle version il se trouve, c'est pas génial :-/ 
Après vous pouvez customiser ça dans votre process d'installation. Un script qui vient shooter la récupération du commit dans le footer, en le remplaçant par un texte de votre choix. Qu'est ce que vous en pensez ?

**Comment by A511701** [comment]
Il faudrait en effet un processus de ce type.
Nous avons tenté avec un placeholder, mais les pre ou post dispatch des plugins ne permettent pas d'utiliser ce mécanisme car :
- predispatch : call trop tôt, la view ne s'est pas exécutée
- postdispatch : call trop tôt aussi car la view s'est exécutée mais pas le layout...

Le script qui retire le contenu du footer est exclus car nous venons modifier le core de l'application en version communautaire. C'est trop intrusif.

Actuellement, nous injectons un js dans la page, mais ça n'est pas idéale et ne permettra pas d'éviter les appels par la lib liée à Git.

Voyez-vous une autre solution ?

**Comment by kdubuc** [comment]
Et sur un dispatchLoopShutdown ?

**Comment by A511701** [comment]
C'est trop tard car le layout est déjà mergé avec les placeholders.
Par ailleurs, on a une fatal error dans le footer lorsqu'on a pas de copie git :
 Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /home/plm/prevarisc-trunk/prevarisc/vendor/sebastian/git/src/Git.php on line 152

Je vous propose la correction suivante qui permettrait de réutiliser le processus de version et d'injection de version depuis le plugin de view :

```
// Envoi de la version en cours sur la vue 
            if (getenv('PREVARISC_VERSION') != false) {
                $view->branch_prevarisc = getenv('PREVARISC_BRANCH');
                $view->revision_prevarisc = getenv('PREVARISC_REVISION');
                $view->version_prevarisc = getenv('PREVARISC_VERSION');
            } else {
                $git = new SebastianBergmann\Git\Git(APPLICATION_PATH . DS . '..');
                $view->branch_prevarisc = $git->getCurrentBranch();
                $view->revision_prevarisc = end($git->getRevisions())['sha1'];
                $view->version_prevarisc = $view->branch_prevarisc . '@' . substr((string) $view->revision_prevarisc, 0, 7);
            }
```
