### ISSUE TITLE
Date dernière VP

### ISSUE THREAD

**Issue by sla33** [SDIS62/prevarisc#278]
Dans quelle tale et quel champ de la base de données de PREVARISC peut-on trouver l'information affichée sur la fiche établissement dans "Dernière VP" (exemple : septembre 2014) ?

**Comment by kdubuc** [comment]
Elle est reprise automatiquement via les dossiers de l'établissement !

**Comment by kdubuc** [comment]
Je peux close ce ticket ?

**Comment by sla33** [comment]
Alors en cherchant on a fini par trouver, je l'indique pour les autres SDIS : l’application prend visiblement la date DATEVISITE_DOSSIER la plus récente  pour faire son calcul et afficher une date de prochaine visite.
Reste à savoir si elle n'effectue ce traitement que pour les dossier de type Visite Périodique ou pour tous les types de Visites.

**Comment by kdubuc** [comment]
Pour calculer la prochaine date de visite, on procède comme suit :
- On recherche les dossiers de types "Visite de commission périodique" et "Groupe de visite périodique" correspondant à l'établissement ;
- On récupère les deux derniers enregistrement DATEVISITE_DOSSIER de la liste des dossiers ;
- Si les deux dates sont favorables et qu'on se trouve dans un établissement sans locaux à sommeil, la prochaine date de visite est égale à la dernière DATEVISITE_DOSSIER + Périodicité + 2 ans ; Sinon, c'est DATEVISITE_DOSSIER + Périodicité

Voila, si vous vouliez la précision sur le mode de calcul, il fallait demander :)

Voici la portion de code responsable de ce calcul :  https://github.com/SDIS62/prevarisc/blob/master/application/services/Etablissement.php#L74

**Comment by sla33** [comment]
Merci, c'était effectivement ce que je cherchais ! Je crois qu'on peut clôturer :-)

**Comment by kdubuc** [comment]
Alors, clôturons ! :-)
