### ISSUE TITLE
MAJ du logiciel prévarisc, commandes?

### ISSUE THREAD

**Issue by SDIS-Vendee** [SDIS62/prevarisc#280]
Bonjour,

pouvez vous nous confirmer que la commande suivante est à lancer en cas de MAJ de l'application prevarisc.
sur un l'environnement de test, se positionner dans le répertoire /var/www/prevarisc-test et lancer la commande: 
"root@srv-prevarisc:/var/www/prevarisc-test# git pull"

sur un l'environnement de production, se positionner dans le répertoire /var/www/prevarisc et lancer la commande: 
"root@srv-prevarisc:/var/www/prevarisc# git pull"

Est- ce suffisant? ou des variables sont elles nécessaires?
dans notre cas, la commande ci dessus nous renvoie: 
"root@srv-prevarisc:/var/www/prevarisc-test# git pull
Already up-to-date."

Merci.

**Comment by kdubuc** [comment]
Un `git pull` suffit ! Et le Already up-to-date signifie que vous avez la dernière mise à jour. ;)

**Comment by SDIS-Vendee** [comment]
Merci! Très bien, effectivement des MAJ se déroulent depuis vos dernières validations. 
A la fin de la procédure Git pull, nous voyons apparaitre parfois des SQL dans le dossier /sql/migrations :

```
           create mode 100644 sql/migrations/2.1-06-addressources-372-373.sql
           create mode 100644 sql/migrations/2.1-07-natures_courrier.sql
           create mode 100644 sql/migrations/2.1-08-ressourcesdashboard.sql
```

Faut-il nécessairement les éxécuter ?
Cela rejoint certainement le dossier #287 mais nous préférons demander et àvoir confirmation.

**Comment by kdubuc** [comment]
Oui ce sont des fichiers de migrations SQL. Vous devez executer que les nouveaux (c'est à dire, ceux qui n'ont jamais été executé avant sur votre BDD). ;)

**Comment by SDIS-Vendee** [comment]
merci
