### ISSUE TITLE
Erreur lors de l'exécution de bower install pour version 3.x

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#281]
Lorsque j exécute la commande bower install voici l'erreur que j'obtiens:

Error: EACCES, mkdir '/var/www/prevarisc-3.x/www/assets/bower_components'

Je vous joins le script complet ci-dessous, avez-vous rencontré ce problème et avez vous une solution. (j'ai parcouru les forum et rien ne fonctionne).

dias@svrerp:/var/www/prevarisc-3.x/www/assets$ bower install
bower cached        git://github.com/jquery/jquery.git#2.1.1
bower validate      2.1.1 against git://github.com/jquery/jquery.git#2.*
bower cached        git://github.com/twbs/bootstrap.git#3.2.0
bower validate      3.2.0 against git://github.com/twbs/bootstrap.git#3.*
bower cached        git://github.com/enyo/dropzone.git#3.10.2
bower validate      3.10.2 against git://github.com/enyo/dropzone.git#3.*
bower cached        git://github.com/davidstutz/bootstrap-multiselect.git#0.9.9
bower validate      0.9.9 against git://github.com/davidstutz/bootstrap-multisel                                             ect.git#0.9.*
bower cached        git://github.com/Mottie/tablesorter.git#2.17.8
bower validate      2.17.8 against git://github.com/Mottie/tablesorter.git#2.*
bower cached        git://github.com/arshaw/fullcalendar.git#1.6.4
bower validate      1.6.4 against git://github.com/arshaw/fullcalendar.git#1.*
bower cached        git://github.com/daneden/animate.css.git#3.2.0
bower validate      3.2.0 against git://github.com/daneden/animate.css.git#3.*
bower cached        git://github.com/metafizzy/packery.git#1.2.4
bower validate      1.2.4 against git://github.com/metafizzy/packery.git#1.*
bower cached        git://github.com/brianreavis/selectize.js.git#0.10.1
bower validate      0.10.1 against git://github.com/brianreavis/selectize.js.git                                             #0.10.*
bower cached        git://github.com/aamirafridi/jQuery.Marquee.git#1.3.1
bower validate      1.3.1 against git://github.com/aamirafridi/jQuery.Marquee.gi                                             t#1.*
bower cached        git://github.com/jquery/jquery.git#2.1.1
bower validate      2.1.1 against git://github.com/jquery/jquery.git#>=1.2.6
bower cached        git://github.com/jquery/jquery.git#2.1.1
bower validate      2.1.1 against git://github.com/jquery/jquery.git#>= 1.11.0
bower cached        git://github.com/twbs/bootstrap.git#3.2.0
bower validate      3.2.0 against git://github.com/twbs/bootstrap.git#>= 2.3.2
bower cached        git://github.com/jquery/jquery.git#1.10.2
bower validate      1.10.2 against git://github.com/jquery/jquery.git#~1.10.2
bower cached        git://github.com/desandro/classie.git#1.0.1
bower validate      1.0.1 against git://github.com/desandro/classie.git#>=1 <2
bower cached        git://github.com/desandro/get-style-property.git#1.0.3
bower validate      1.0.3 against git://github.com/desandro/get-style-property.g                                             it#>=1 <2
bower cached        git://github.com/desandro/get-size.git#1.1.7
bower validate      1.1.7 against git://github.com/desandro/get-size.git#^1.1
bower cached        git://github.com/metafizzy/outlayer.git#1.2.0
bower validate      1.2.0 against git://github.com/metafizzy/outlayer.git#^1.2.0
bower cached        git://github.com/brianreavis/sifter.js.git#0.3.4
bower validate      0.3.4 against git://github.com/brianreavis/sifter.js.git#0.3                                             .x
bower cached        git://github.com/brianreavis/microplugin.js.git#0.0.3
bower validate      0.0.3 against git://github.com/brianreavis/microplugin.js.gi                                             t#0.0.x
bower cached        git://github.com/desandro/get-style-property.git#1.0.3
bower validate      1.0.3 against git://github.com/desandro/get-style-property.g                                             it#*
bower cached        git://github.com/desandro/doc-ready.git#1.0.3
bower validate      1.0.3 against git://github.com/desandro/doc-ready.git#>=1.0.                                             1 <2.0
bower cached        git://github.com/desandro/matches-selector.git#1.0.2
bower validate      1.0.2 against git://github.com/desandro/matches-selector.git                                             #>=1 <2
bower cached        git://github.com/Wolfy87/EventEmitter.git#4.2.8
bower validate      4.2.8 against git://github.com/Wolfy87/EventEmitter.git#>=4.                                             2 <5
bower cached        git://github.com/desandro/eventie.git#1.0.5
bower validate      1.0.5 against git://github.com/desandro/eventie.git#>=1.0.3                                              <2.0
bower cached        git://github.com/desandro/jquery-bridget.git#1.0.1
bower validate      1.0.1 against git://github.com/desandro/jquery-bridget.git#>                                             =1 <2
bower cached        git://github.com/desandro/eventie.git#1.0.5
bower validate      1.0.5 against git://github.com/desandro/eventie.git#*

Please note that,
    fullcalendar#1.6.4 depends on jquery#~1.10.2 which resolved to jquery#1.10.2
    bootstrap#3.2.0, bootstrap#3.2.0 depends on jquery#>= 1.9.0 which resolved t                                             o jquery#2.1.1
    Prevarisc depends on jquery#2.\* which resolved to jquery#2.1.1
    jquery.tablesorter#2.17.8 depends on jquery#>=1.2.6 which resolved to jquery                                             #2.1.1
    bootstrap-multiselect#0.9.9 depends on jquery#>= 1.11.0 which resolved to jq                                             uery#2.1.1
    selectize#0.10.1 depends on jquery#>=1.7.0 which resolved to jquery#2.1.1
Resort to using jquery#2.\* which resolved to jquery#2.1.1
Code incompatibilities may occur.

bower EACCES        EACCES, mkdir '/var/www/prevarisc-3.x/www/assets/bower_compo                                             nents'

Stack trace:
Error: EACCES, mkdir '/var/www/prevarisc-3.x/www/assets/bower_components'

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/S                                             tandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/                                             lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1035:                                             31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_m                                             odules/q/q.js:741:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.31
OS: Linux 3.2.0-4-686-pae ia32

**Comment by kdubuc** [comment]
Je pense que ça doit être un problème de droit, as tu essayé en sudo ?

**Comment by diasn** [comment]
Je n'arrive pas à exécuter les commandes avec le préfixe sudo (commande introuvable), y a t'il un module à installer?

**Comment by kdubuc** [comment]
On dirait juste que bower n'arrive pas à écrire le dossier bower_components dans prevarisc/www/assets
Voici quelques pistes, mais c'est plus une erreur bower que de prevarisc ..
http://stackoverflow.com/questions/21616785/bower-installation-errors
http://stackoverflow.com/questions/22257726/eacces-error-with-bower-install
