### ISSUE TITLE
Document qui ne se supprime pas

### ISSUE THREAD

**Issue by SDIS-Vendee** [SDIS62/prevarisc#286]
Bonjour, dans la gestion des documents,

un utilisateur a poussé un document nommé:
convoc SCD-salle-accessibilité cohésion sociale+CHD.odt

Ce document à bien été ajouté. 
Seulement, impossible de le supprimer de la liste.
problème de caractère?

Idem pour un document nommé:
convoc SCD-salle-DDTM+forces de l'ordre.odt

**Comment by kdubuc** [comment]
poke @alucard62 ?

**Comment by ghost** [comment]
Bonjour,
C’est le caractère « + » dans le nom des fichiers qui pose problème. La fonction unlink de php ne s’exécute pas correctement lorsque le nom est composé d’un ou plusieurs « + ».
Le seul moyen de supprimer ce fichier pour le moment est d’aller directement sur le serveur.

**Comment by A511701** [comment]
Un problème similaire a été corrigé il y a quelques jours sur la liste des rapports sélectionnables pour génération sur la partie dossier : lorsqu'il y avait une simple quote (apostrophe), on ne voyait pas la totalité du chemin.
