### ISSUE TITLE
Probleme Création Etablissement

### ISSUE THREAD

**Issue by cp61** [SDIS62/prevarisc#287]
Bonjour

Nous avons intégrés toutes nos communes ainsi que les types de rues et les rues de toutes les communes.

Lorsque nous voulons créer un établissement , nous avons l'erreur suivante : 

Message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'prevarisc.classement' doesn't exist, query was: DESCRIBE `classement` 

![2014-10-08_160813](https://cloud.githubusercontent.com/assets/8723270/4560394/bb856422-4ef4-11e4-9b3c-2598c30dfb91.jpg)

**Comment by kdubuc** [comment]
Avez vous exécuté les fichiers sql sql/migrations ?
Sinon, vous devez les executer dans l'ordre en personnalisant le nom  de votre base prevarisc dans le script.

**Comment by cp61** [comment]
De quel fichiers parlez vous ?

Pour ma part il s'agit de la VM installée lors de notre venue au SDIS 62 en septembre.

Nous n'avons jamais évoqué les fichiers dont vous parlez.

**Comment by kdubuc** [comment]
Ils sont nouveaux, c'est pour faciliter les migrations sql, elles sont en cours de documentation.
Vous n'avez qu'a executer les fichiers se trouvant ici : https://github.com/SDIS62/prevarisc/tree/master/sql/migrations

**Comment by cp61** [comment]
Ok impec cela fonctionne

Merci

**Comment by kdubuc** [comment]
Pas de problème !

**Comment by Thierrysdis58** [comment]
Bonjour, 

je rencontre un problème similaire sur la table 'prevarisc.utilisateurpreferences' lors la connexion à prevarisc en root
Ci-dessous le message d'erreur en question
"Erreur d'authentification SQLSTATE[42S02]: Base table or view not found: 1146 Table 'prevarisc.utilisateurpreferences' doesn't exist, query was: DESCRIBE `utilisateurpreferences`"
Avez-vous une idée sur la question .
Merci de votre réponse
