### ISSUE TITLE
Impossible d'ouvrir les dossiers.

### ISSUE THREAD

**Issue by SDIS-Vendee** [SDIS62/prevarisc#289]
Bonjour,

L'ouverture des dossiers enregistrés m'est refusée.
"Accès non autorisé !
Vos droits ne permettent pas d'accéder à cette page ! Si vous ..."

Le groupe de l'utilisateur dispose pourtant de toutes les autorisations, les droits sont tous cochés.

Cordialement.

**Comment by kdubuc** [comment]
Il doit y'avoir une erreur dans le traitement de la page, pouvez vous me donner ce qui se trouve dans votre error_log lorsque vous voulez accéder à cette page ?

**Comment by SDIS-Vendee** [comment]
Il se situe ou ce fichier ?

**Comment by kdubuc** [comment]
Sur votre serveur. Normalement sur un debian, vous trouvez ça dans /var/log/apache2/error_log. Vous lancez un tail sur ce fichier

**Comment by SDIS-Vendee** [comment]
voici les dernières lignes du fichier:

"[Mon Oct 13 15:26:26 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:26 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:26 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:26 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:26 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:26 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:26 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:26 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:27 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:27 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:27 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:27 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:27 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:27 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:27 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:26:27 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add"

**Comment by kdubuc** [comment]
Avez vous copié le contenu de votre error_log juste après avoir déclenché l'erreur sur Prevarisc ?
Je ne vois pas d'accès au dossier sur les logs

**Comment by SDIS-Vendee** [comment]
nous générons l'erreur à 15h51 (heure du serveur prevarisc) et dans le fichier /var/log/apache2/error.log, la dernière ligne est à 15h45.

**Comment by kdubuc** [comment]
Bon, donc la page ne génère pas d'erreur pouvant interférer avec la gestion des droits d'accès au dossier. L'accès à un dossier dépend (entre autres) des droits de l'utilisateur sur l'établissement concerné. Cette gestion passe par l'ajout des ressources spécialisées. Avez vous bien créé les ressources liées aux droits des dossiers et aux droits des établissements ? En les affectants bien au bon groupe ?

**Comment by kdubuc** [comment]
Si jamais, j'ai modifié le comportement de la page d'erreur pour qu'elle n'affiche plus les erreurs d'accès alors que l'erreur vient d'autre part. https://github.com/SDIS62/prevarisc/commit/2124069f800b690d1551f716933728614a1c264f

**Comment by SDIS-Vendee** [comment]
ok en ajoutant une ressource liée au Dossier et en modifiant les droits.
Merci Kevin
