### ISSUE TITLE
Impossibilité de créer un établissement

### ISSUE THREAD

**Issue by SDIS-Vendee** [SDIS62/prevarisc#290]
Bonjour,

nous n'arrvons pas à ajouter des étblissements rattachés à certaines communes!
voici le contenu du fichier error.log

<b> 
[Mon Oct 13 15:42:46 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:42:46 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:42:46 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:42:46 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:42:46 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:42:46 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:42:46 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
[Mon Oct 13 15:42:46 2014] [error] [client 10.186.3.26] PHP Notice:  Array to string conversion in /var/www/prevarisc-test/application/models/DbTable/Groupement.php on line 79, referer: http://prevarisc-test.sdis85.fr/etablissement/add
</b>

**Comment by kdubuc** [comment]
A quel moment vous bloquez ? Sur l'écran des valeurs par défauts ? sur l'écran d'ajout d'adresse ? à la sauvegarde de l'établissement ?

**Comment by SDIS-Vendee** [comment]
A la sauvegarde de l'établissement, cad, au clic du bouton "Ajouter l'établissement". Tout est renseigné et rien ne se passe lors du clic.

**Comment by kdubuc** [comment]
Je n'arrive pas à reproduire le bug.
Si vous avez accès à la console web de votre navigateur, il serait intéressant de savoir ce que Prevarisc retourne quand vous appuyez sur la sauvegarde. (sur Chrome : clic droit - Procéder à l'inspection - Network). Sinon, on peut s'appeler pour debugger ça ensemble.

**Comment by kdubuc** [comment]
ça devrait aller beaucoup mieux avec cette mise à jour : https://github.com/SDIS62/prevarisc/commit/8d6b80784c651d82a390dfb5c6dcd5f7c33e6f50
Vous pouvez confirmer ?

**Comment by SDIS-Vendee** [comment]
J'ai effectué un git pull pour prendre en compte cette modification mais voici le message d'erreur :
![2014-10-14_11h39_18](https://cloud.githubusercontent.com/assets/8723308/4626906/0a2dd4f2-5386-11e4-98f3-3c21178a89f9.png)

**Comment by kdubuc** [comment]
Vous pouvez réinitialiser Prevarisc avec le dépôt git avec ces deux commandes :

```
git fetch --all
git reset --hard origin/master
```

Cela supprime tout le contenu local modifié.
Faites quand même une sauvegarde de ce qui se trouve dans le dossier public/data/uploads si jamais vous avez généré des documents ou importé des pièces jointes dans Prevarisc.

**Comment by SDIS-Vendee** [comment]
J'ai effectué les 2 commandes ci-dessus + un git pull avec succès.
La sauvegarde de l'etablissement fonctionne.
Cloture OK.

**Comment by SDIS-Vendee** [comment]
Par contre, erreur suivante sur la page d'accueil...
![erreur](https://cloud.githubusercontent.com/assets/8723308/4627452/591d731a-538b-11e4-890f-74c1d648ca8b.JPG)

**Comment by kdubuc** [comment]
Vous devez lancer une mise à jour des dépendances :

```
php composer.phar update -o
```

A exécuter à la racine de Prevarisc.

**Comment by SDIS-Vendee** [comment]
Ok, cela fonctionne.
