### ISSUE TITLE
Changement de branche par défaut (master -> 2.x)

### ISSUE THREAD

**Issue by kdubuc** [SDIS62/prevarisc#291]
J'envisage de renommer la branche "master" en "2.x" pour refléter le fait que l'on travaille sur la deuxième version de Prevarisc. Il existe déjà sur le dépôt les branches 1.x et 3.x.

Il n'y aura pas vraiment d'impact, ne serait ce que chaque installations devra "switcher" de branche locale pour continuer de recevoir les mises à jour.

Qu'est ce que vous en pensez ?

**Comment by diasn** [comment]
c'est ok pour moi, pour les mises à jour on aura quoi comme commande à saisir du coup?

**Comment by kdubuc** [comment]
Histoire de repartir sur une base saine, ces deux commandes devraient suffire : 

```
git fetch --all
git reset --hard origin/2.x
```

**Comment by A511701** [comment]
OK pour nous, ça n'en sera que plus clair !! :)

**Comment by kdubuc** [comment]
Branche master dépréciée ! Pour changer de branche active, c'est git checkout 2.x après un pull. Les changements doivent être poussés sur la branche 2.x à partir de maintenant !

**Comment by SDIS-Vendee** [comment]
Bonjour,

A quoi correspond la branche "Master" ?
Devons-nous continuer à effectuer un git pull à la racine de notre dossier "prevarisc" ?
Merci pour vos réponses.

Cordialement.

**Comment by kdubuc** [comment]
La branche master ne correspond plus à grand chose maintenant, avant, c'était sur cette branche qu'était effectué tous les développements. Maintenant, pour être plus clair cette branche est renommée 2.x afin de clarifier le fait que l'on travaille actuellement sur la deuxième version du logiciel.

Pour bénéficier des dernières mise à jour, vous devez exécuter ces commandes : (_ATTENTION_, avant tout, faites des sauvegardes, surtout au niveau des données uploadées sur Prevarisc, répertoire public/data/uploads)

```
git fetch --all
git reset --hard origin/2.x
git checkout 2.x
```

Vous êtes dorénavant sur la branche 2.x, et pour bénéficier des mises à jour de cette branche, un `git pull` suffit :wink:

**Comment by diasn** [comment]
dans quel dossier on se positionne pour exécuter ces lignes?

var/www/prevarisc ?

**Comment by kdubuc** [comment]
Oui

**Comment by SDIS-Vendee** [comment]
Bonjour,

Les actions :
- git fetch --all
- git reset --hard origin/2.x
- git checkout 2.x
  et
- git pull
  ont fonctionné.
  ![2014-11-13_09h51_33](https://cloud.githubusercontent.com/assets/8723308/5025592/c58b8a5e-6b1a-11e4-9d58-4780a3512f9a.png)

Par contre, a aucun moment nous avons passé de requêtes sql et lors du git pull pas de sql de signalé.
Dans le repertoire /var/www/prevarisc-test/sql/migrations, nous voyons des requetes 2.2.
Devons-nous les executer ? Devons-nous ré-executer les 2.1 ?
![capture](https://cloud.githubusercontent.com/assets/8723308/5025568/8c22c6e2-6b1a-11e4-9e30-be00872f998d.JPG)

**Comment by kdubuc** [comment]
Vous devez exécuter uniquement les nouveaux fichiers de migrations que vous n'avez pas exécuté auparavant

**Comment by SDIS-Vendee** [comment]
Ok, par contre; pourquoi est ce qu'on ne visualise plus ces fichiers sql sans le git pull ?

**Comment by kdubuc** [comment]
le `git fetch --all` récupère le tout de façon silencieuse, il n'affiche pas le détail des fichiers mis à jour

**Comment by SDIS-Vendee** [comment]
Ok, merci.
