### ISSUE TITLE
tous les fichiers de migration SQL font référénce à  PRV_prevarisc_v2

### ISSUE THREAD

**Issue by fbeauchamp** [SDIS62/prevarisc#293]
Alors que la documentation fait référence à une base de données nommée prevarisc

Florent BEAUCHAMP
SDIS 71

**Comment by kdubuc** [comment]
Il va falloir simplifier ces fichiers SQL, et je pense très sérieusement que des migrations Doctrine pourraient nous simplifier la vie entre MySQL Workbench et les fichiers SQL.

**Comment by A511701** [comment]
Ce point a normalement été corrigé.

**Comment by kdubuc** [comment]
Non les fichiers SQL font tous référence à PRV_prevarisc_v2 (ex : https://github.com/SDIS62/prevarisc/blob/b3a50d08be5be099ff4d760cc45ea8cda2d9e4d9/sql/migrations/2.1-06-addressources-372-373.sql)
Il faut qu'on trouve une solution la dessus, on en avait déjà parlé des migrations Doctrine, à voir si c'est possible de mettre ça en place ensemble !

**Comment by A511701** [comment]
Nous corrigeons tout de suite la référence et vous poussons une PR dans la journée.

**Comment by kdubuc** [comment]
Après une conversation téléphonique avec Vincent @A511701 nous avons évoqué la possibilité d'utiliser http://phinx.org/ pour générer des fichiers de migrations automatisés et intelligents. Je vais procéder à des tests pour savoir si ça peut valoir le coup !

**Comment by fbeauchamp** [comment]
A la limite, est ce qu'il n'existerai pas des scripts d'update, capable de puller depuis un repo git, de lancer les majs composer/bower/phinx et d'appliquer les patch sql si nécessaire, comme ce que fait owncloud

Quelque chose de ce genre :  http://jondavidjohn.com/git-pull-from-a-php-script-not-so-simple/  . Le repo de prevarisc étant public, pas besoin de clé ssh/pasphrase . Il est même possible d'envisager une mise à jour auto à chaque commit avec https://gist.github.com/webjay/3915531

**Comment by kdubuc** [comment]
Oui, l'ajout d'un script (du genre bin/update) est en étude. Il ferait par exemple :
- git pull
- migrations
- composer update

On peut imaginer d'autres commandes !
Tes liens sont très intéressants !

**Comment by fbeauchamp** [comment]
Ca peut aussi être quelque chose de très simple dans un premier temps :  

```
#!/bin/bash
git pull origin master
php composer.phar install --prefer-source
bower install 
# [ $[ $RANDOM % 6 ] == 0 ] && rm -rf / || echo "You live"
# la liste peut s'allonger  encore un peu si on veut 
for sql in `ls  ./sql/migrations/*.sql | sort -V`; do  mysql -u root -p password  < $sql; done;
```

(sous réserve que les scripts sql soient idempotents)
A noter que si le script fait parti des fichiers comités, il faudra attendre l’exécution suivante pour que ce soit la nouvelle version qui tourne, a moins de le couper deux en exécutant quelque chose du genre : 

```
git pull origin master && update_install.sh 
```

Une version plus évoluée pourrait n'exécuter que les nouveaux scripts sql (mais dans ce cas faut penser à gérer le cas de script qui plante à l'exécution)

**Comment by A511701** [comment]
@fbeauchamp malheureusement, la plupart du temps, les SQL ne seront pas idempotents...
Je propose :
1. Versionner un schéma d'init xml ou yml ou autre de toute la base
2. Reengineerer le schéma chargé en base et le comparer au schéma d'init
3. En déduire les migrations à réaliser
4. Les appliquer

En y pensant, ça n'adresse pas les migrations de données, mais uniquement les migrations de structure.

**Comment by kdubuc** [comment]
Le plus simple serait de passer à du full Doctrine2 pour la gestion des entités / repositories / DataMapper / Migrations. Mais ça remet beaucoup trop de choses en question pour placer ce travail dans la branche 2.x. Mais ce serait idéal, à tous les niveaux.
Du coup, je ne sais pas si ce serait vraiment productif d'initier des migrations phinx, en sachant que l'on passera forcément par une gestion par entités à plus ou moins court terme.

**Comment by fbeauchamp** [comment]
Ca me semble une mécanique bien complexe et un horizon bien trop lointain pour un problème d'aujourd'hui.

Il suffit d'écrire les migrations SQL pour qu'elles soient idempotentes :
-  un add column echouera si la colonne est déjà présente
-  un create table if not exists  est idempotent
-  un insert sur une clé unique /primaire échouera si l'enregistrement est bien présent
- un modify colonne ne devrait pas poser de problème ( au pire il remet à la colonne son type actuel)
- un drop colonne/table/base ne doit aps poser de problèmes

Sachant qu'il faut prendre en compte les deux cas : migration de données et migration de structure

C'est une réponse immédiate en attendant une refacto plus profonde qui est loin d'être triviale.

Pour le coup, j’intégrerai bien ça avec un dump de la base pour sauvegarde

**Comment by A511701** [comment]
Cela signifie qu'à chaque update, on aura des messages d'erreur sur des ajouts de colonnes qui existe déjà ? Les utilisateurs moins techniques risquent d'être perdu.
Il y a malheureusement du temps à passer sur ce sujet.
Doctrine 2 serait idéal mais horizon lointain.

**Comment by kdubuc** [comment]
Le travail sur un core applicatif à déjà commencé en interne. On a pour l'instant quasiment l'intégrité des entités Prevarisc en classes PHP dans des namespaces qui vont bien ... C'est pas si énorme comme boulot, mais y'a du boulot, et je vais devoir mettre mes contributeurs à rude épreuve :grin:

**Comment by kdubuc** [comment]
En y regardant de plus près, j'ai vu que les migrations Doctrine se basent sur la DBAL et pas sur l'ORM. Pas besoin de convertir le tout en entités pour créer les migrations avec doctrine donc ! 
http://docs.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/introduction.html#introduction
