### ISSUE TITLE
Aie ! Une erreur '' est survenue ... sur une installation vierge

### ISSUE THREAD

**Issue by fbeauchamp** [SDIS62/prevarisc#294]
Je monte une installation depuis zéro pour travailler sur la reprise de données et je rencontre ce message lors de l'appel  a $service_user->getDashboardData après connexion avec le compte root

Pas de messages dans les logs 

A noter que le compte root par défaut est paramétré avec un salt qui n'est pas celui par défaut.

**Comment by kdubuc** [comment]
Tu as utilisé le script sql dans le dossier init/ j'imagine ? Il doit y'avoir un problème la dessus, une migration qui n'est pas passé dans ce script. Je regarde ça.

**Comment by kdubuc** [comment]
En attendant tu peux essayer d'exécuter la migration 2.1-08-ressourcesdashboard.sql

**Comment by fbeauchamp** [comment]
Les enregistrements sont déjà présents en base

**Comment by kdubuc** [comment]
L'error te dit quoi exactement ?
Ta durée de cache est elle supérieure à 1s ?

**Comment by A511701** [comment]
Pouvez-vous placer la stack trace dans Git ?

**Comment by A511701** [comment]
Bonjour,
J'ai rechargé une base vierge et je ne reproduis pas le problème.

**Comment by fbeauchamp** [comment]
Je n'ai pas de stacktrace :/ . 
Je resteste ça demain sur une base vierge.

**Comment by A511701** [comment]
Pour voir la stacktrace, activez le mode debug dans votre vhost via 
`SetEnv PREVARISC_DEBUG_ENABLED 1`

**Comment by fbeauchamp** [comment]
merci, je n'avais pas vu cette option

**Comment by A511701** [comment]
Pas de soucis, vous avez toute la liste des options ici si besoin :
https://github.com/SDIS62/prevarisc/blob/master/docs/documentation_installation.md

**Comment by diasn** [comment]
Bonjour,
lors de la mise à jour de prevarisc en exécutant un git pull, voici l'erreur que j'obtiens à la validation des identifiants de connexion:
![image](https://cloud.githubusercontent.com/assets/6367639/4658615/bd271f8e-5500-11e4-853c-266d3f679ff6.png)

Avez-vous une solution?

**Comment by kdubuc** [comment]
Il faut que tu exécutes ce fichier de migration SQL https://github.com/SDIS62/prevarisc/blob/b3a50d08be5be099ff4d760cc45ea8cda2d9e4d9/sql/migrations/2.1-08-ressourcesdashboard.sql

**Comment by diasn** [comment]
Ok, parfait cela fonctionne.

**Comment by diasn** [comment]
Par contre, à l'ouverture d'un fiche Etab ou Dossier, j'ai une erreur, due au Zend, dois-je exécuter une commande?

Fatal error: Uncaught exception 'Zend_Db_Table_Row_Exception' with message 'Specified column "ID_CLASSEMENT" is not in the row' in /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Db/Table/Row/Abstract.php:179 Stack trace: #0 /var/www/prevarisc/application/services/Etablissement.php(173): Zend_Db_Table_Row_Abstract->__get('ID_CLASSEMENT') #1 /var/www/prevarisc/application/plugins/ACL.php(379): Service_Etablissement->get('383') #2 /var/www/prevarisc/application/plugins/ACL.php(315): Plugin_ACL->getEtablissementPageResourses('383') #3 /var/www/prevarisc/application/plugins/ACL.php(197): Plugin_ACL->getPageResources(Object(Zend_Navigation_Page_Mvc), Object(Zend_Controller_Request_Http)) #4 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php(309): Plugin_ACL->preDispatch(Object(Zend_Controller_Request_Http)) #5 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(941): Zend_Controller_Plugin_Broker->preDispatch(Object(Zend_Cont in /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Plugin/Broker.php on line 312

**Comment by kdubuc** [comment]
Dans le dossier sql/migrations/ tu dois exécuter toutes les migrations qui te manquent (tu as déjà fait la 8)

**Comment by fbeauchamp** [comment]
Après avoir activer le debug, et relancé apache, je n'ai plus le soucis

probablement lié à un cache qui contenait une information erronné.

**Comment by kdubuc** [comment]
Oui l'ACL est fortement liée au cache. Je close donc ! :)
