### ISSUE TITLE
Git détecte des changements locaux et empêche la mise à jour via un git pull

### ISSUE THREAD

**Issue by pcano65** [SDIS62/prevarisc#297]
Bonjour

Lorsque je fais un git pull, j'ai le message :

 remote: Counting objects: 401, done.
remote: Compressing objects: 100% (232/232), done.
remote: Total 401 (delta 213), reused 254 (delta 155)
Receiving objects: 100% (401/401), 244.93 KiB | 425 KiB/s, done.
Resolving deltas: 100% (213/213), done.
From https://github.com/SDIS62/prevarisc
   cbbad14..f10941b  master     -> origin/master
- [new branch]      1.x        -> origin/1.x
  a3e697d..b0e952c  gh-pages   -> origin/gh-pages
  Updating cbbad14..f10941b
  error: Your local changes to the following files would be overwritten by merge:
      application/models/DbTable/Classement.php
  Please, commit your changes or stash them before you can merge.
  Aborting

Une idée ??

merci.

Patrice CANO
SDIS 65

**Comment by kdubuc** [comment]
Vous pouvez forcer la mise à jour comme expliqué ici : https://github.com/SDIS62/prevarisc/issues/290#issuecomment-59014660

Avant de faire la manipulation, faites quand même une sauvegarde de ce qui se trouve dans le dossier public/data/uploads si jamais vous avez généré des documents ou importé des pièces jointes dans Prevarisc.

**Comment by pcano65** [comment]
Merci!
