### ISSUE TITLE
Problème Création Etablissement

### ISSUE THREAD

**Issue by cp61** [SDIS62/prevarisc#298]
Bonjour 

Nous avons voulu faire une mise à jour de Prevarisc, aussi nous avons du passer les commandes suivantes pour que cela fonctionne  : 

git fetch --all
git reset --hard origin/master
git pull
php composer.phar update -o

L'accès à Prevarisc fonctionne mais nous n'avons plus les droits pour créer un établissement ou un dossier.
![2014-10-20_152741](https://cloud.githubusercontent.com/assets/8723270/4701791/f2a2b100-585c-11e4-9b81-e83a033eb0b0.jpg)

**Comment by kdubuc** [comment]
Avez vous bien vérifié les droits de votre groupe sur l'ajout d'établissement / de dossier ?

**Comment by cp61** [comment]
En effet j'avais oublié ce paramêtre !!!!

Par contre une fois l'établissement créé, si je veux accéder à la fiche j'ai de nouveau le message d'erreur "accès non autorisé", idem pour les dossiers

Pourtant j'ai bien affecté tous les droits au groupe.

**Comment by cp61** [comment]
J'arrive désormais à acceder à mes établissements.

Par contre sur chaque fiche Etablissements nous avons l'erreur suivante 

Notice: Undefined offset: 5 in /var/www/prevarisc/application/plugins/ACL.php on line 112

Notice: Undefined offset: 6 in /var/www/prevarisc/application/plugins/ACL.php on line 113

![2014-10-21_092950](https://cloud.githubusercontent.com/assets/8723270/4714581/2ae01ec6-58f4-11e4-9372-b47d30afa7d3.jpg)

**Comment by kdubuc** [comment]
Quelle est votre version de PHP ?

**Comment by kdubuc** [comment]
Avez vous toujours ce problème ?

**Comment by kdubuc** [comment]
je close
