### ISSUE TITLE
Libellé de rue obligatoire ?

### ISSUE THREAD

**Issue by pcano65** [SDIS62/prevarisc#301]
Bonjour,

Le libellé de la rue dans la zone localisation semble obligatoire.
Serait il possible de le rendre non obligatoire ? En effet nous avons des ERP qui n'ont pas d'adresse mais juste une commune, comme par exemple l'aéroport.
Merci.

Patrice / SDIS65

**Comment by kdubuc** [comment]
Il me faudrait plusieurs points de vue la dessus, j'ai des solutions en tête, mais pas sur que ça soit de bonnes réponses :
- Ajouter une rue "Non localisé" pour chaque ville, ainsi vous pourriez localiser sur cette rue particulière les établissements ne donnant pas lieu à l'identification précise de leur position ;
- Ajouter une rue "Aéroport" dans la ville concernée ;
- Ou comme vous le proposez, rendre la rue facultative.

J'attends les retours :wink:

**Comment by A511701** [comment]
Bonjour,
Nous avons également rencontré ce besoin par exemple pour une zone qui n'a pas encore de rue.

**Comment by pcano65** [comment]
Pour continuer mes tests d'import j'ai rajouté une adresse "inconnue" pour chaque commune.
Pour l'instant cela me convient ...
Merci.
