### ISSUE TITLE
Descriptif technique : stabilité au feu : unité à la demi-heure

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#302]
Bonjour,
Avez-vous également besoin d'utiliser les champs "Structure SF (heure)" et "Plancher SF (heure)" à la demi-heure près, c'est à dire, saisir 0,5 dans ces champs ?

Si oui, c'est actuellement impossible car en base nous avons un entier.
Si vous avez également ce besoin, et que cela a un sens au niveau de la prévention, nous pouvons passer une évol pour les passer en DECIMAL(10,2) mais cela va occasionner une modification de structure de BDD.

![image](https://cloud.githubusercontent.com/assets/6736730/4822401/1e99c506-5f41-11e4-8ce1-dee03ab7b815.png)

**Comment by kdubuc** [comment]
Oui ce problème nous a déjà été remonté, j'avais pensé à modifier le libellé en "minutes" ...

**Comment by A511701** [comment]
Dans ce cas, nous devons fournir un SQL de migration pour les bases existantes qui fait \* 60 aux données existantes ?

**Comment by kdubuc** [comment]
Oui ! ça me semble être une bonne solution

**Comment by A511701** [comment]
Je vous propose de faire une PR pour cette évolution si vous êtes d'accord.

**Comment by kdubuc** [comment]
Bien sur ! :wink:
