### ISSUE TITLE
Dossier : dossier d’autorisation d’une installation classée

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#303]
Dans les dossiers d'étude, la nature "Autorisation d'une installation classée" n'existe pas.
Comment gérez-vous ce cas aujourd'hui ?

**Comment by kdubuc** [comment]
Après la conversation téléphonique sur ce sujet, on envisage d'ajouter une nature de dossier "Autorisation d'une installation classée" qui serait copié sur le modèle de l'autorisation de travaux.
Je pose ça là, si jamais vous voulez réagir la dessus, c'est le moment ! :wink:

**Comment by A511701** [comment]
Merci !
