### ISSUE TITLE
Création d'un dossier: gestion des droits par rapport aux natures.

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#304]
Bonjour,

Dans la gestion des droits de création, on peut donner un droit de création sur les dossiers et le Etablissements.

Donc, dans la gestion des droits, ne pourrait-on pas donner des droits de créations de dossiers selon la nature?

Par exemple, pour la nature intervention, cela serait pratique que le CODIS puisse accéder à prevarisc et créer un dossier relatif à une intervention, mais, qu'il n'est les droits pour créer un dossier dnas les autres nature (étude, visite,...).

**Comment by kdubuc** [comment]
ça peut etre une amélioration interessante effectivement, il est vrai que pour le moment les droits de création n'ont aucun filtre d'accès. Si jamais je reviens dessus, j'essaierais d'intégrer ça !
