### ISSUE TITLE
Id externe (ERPv2) : agrandissement du texte + mise en gras

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#305]
Bonjour,
Pour rendre l'id externe (identifiant externe issu d'ERPv2 par exemple), validez-vous l'agrandissement du texte et la mise en gras sur la fiche établissement ?

![agrandissement_id](https://cloud.githubusercontent.com/assets/6736730/4846718/81c09b16-604d-11e4-8820-d5083de1c53f.png)

**Comment by kdubuc** [comment]
Pas de problème pour moi. Il serait d'ailleurs sympa, vu que vous êtes dessus, de le placer sur la même ligne que le libellé, et d'avoir une forme : "#ID_ETS" plutot que "id: ID_ETS" pour reprendre la codification de l'identifiant établissement dans la recherche !

**Comment by A511701** [comment]
Bien reçu, je regarde si c'est faisable rapidement sans trop d'impact sur le reste !

**Comment by A511701** [comment]
Voici le résultat, OK pour vous ?

![agrandissement_id](https://cloud.githubusercontent.com/assets/6736730/4859474/9902fc68-60ea-11e4-8f14-24af976852cb.png)

**Comment by kdubuc** [comment]
je voyais plus ça au niveau du positionnement de l'identifiant : 

![capture](https://cloud.githubusercontent.com/assets/895661/4859537/5f0dfbb0-60eb-11e4-8967-0fde29d8b4a0.jpg)

Qu'est ce que vous en pensez ?

**Comment by A511701** [comment]
Et là ?

![agrandissement_id](https://cloud.githubusercontent.com/assets/6736730/4859706/8c8a5028-60ed-11e4-9021-33580fed3998.png)

**Comment by kdubuc** [comment]
C'est bon pour moi !

**Comment by A511701** [comment]
Super merci !

**Comment by A511701** [comment]
Je pousse une PR ce soir, vous pouvez fermer cette issue.

**Comment by kdubuc** [comment]
Vous pouvez la fermer directement via des mots clés dans votre description du PR https://github.com/blog/1506-closing-issues-via-pull-requests on peut linker automatiquement le ticket et le PR associé comme ça !
