### ISSUE TITLE
Type de voie : utilisation ou non utilisation ?

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#306]
Bonjour,
Nous utilisons actuellement le champ LIBELLE_RUETYPE de la table adresseruetype.
Ainsi, les voies contenues dans adresserue ne contiennent pas le libellé de la voie : exemple : "rue jean moulin" ===> "jean moulin".

Cela pose un problème car dans toute l'application le champ LIBELLE_RUETYPE  n'est pas utilisé alors que le modèle de données le permet.

Quelle est la guideline officielle à ce niveau ?

**Comment by kdubuc** [comment]
Elle n'a jamais été utilisé car à l'époque de la construction de ce module, tous les extracts des SIG fournissaient le type de rue directement dans le libellé. J'aimerais utiliser LIBELLE_RUETYPE, mais il faudrait avant tout adapter les ETL des SIG pour faire correspondre les rues aux types de rues. Et là, ce n'est pas à mon niveau de décider ça.
Bonne idée du coup de mettre ça sur un ticket, vous en pensez quoi les autres SDIS ?

**Comment by pcano65** [comment]
Bonjour,

Les types de voie sont inclus dans le libellé dans les bases BD-TOPO de l' IGN ainsi que dans celle d' OPENSTREET MAP.
J'aurais donc tendance à proposer de ne pas utiliser LIBELLE_RUETYPE.

Cdlt.

**Comment by A511701** [comment]
OK, en attendant, nous passons sur un mode sans type de voie devant le libellé de l'adresse.
L'impact sur l'existant est trop grand.
