### ISSUE TITLE
Google MINIFY - Optimisation des requêtes de chargement

### ISSUE THREAD

**Issue by kdubuc** [SDIS62/prevarisc#311]
J'ai poussé une modification majeure dans la fonctionnement interne du chargement des assets de l'application. Pour cela, je me repose sur la librairie minify de Google (https://code.google.com/p/minify/) qui concatène tous les assets en un fichier, et le tout, à la volée. Mais j'imagine que ça va peut être poser des problèmes à d'autres installations, j'ouvre donc le ticket en prévision. Si jamais vous avez un problème, postez ici !

Le commit associé : https://github.com/SDIS62/prevarisc/commit/419b139df83495fd881f9c0221bcf90e05702041

**Comment by A511701** [comment]
Bonjour,
Est-il possible de passer le code PHP en dehors du répertoire public/ qui est accessible par Apache pour des raisons de sécurité ?

**Comment by kdubuc** [comment]
Non, le code doit être en public pour pouvoir générer les feuilles de styles / js à la volée. Après, rien n'est secret dans la lib min, tout ce qu'il se trouve dans le dossier public est directement téléchargeable sur le site du projet, et Google met dans son User Guide d'installation qu'il faut mettre toute la lib à la racine accessible du projet (https://code.google.com/p/minify/wiki/UserGuide#Installing_Minify_for_the_first_time).
Et je n'ai pas vu de package composer qui permet d'externaliser le fonctionnement de la librairie .. Si jamais ça existe, pourquoi pas, mais vraiment, je ne pense pas que l'on risque grand chose avec ce code dans public/

**Comment by A511701** [comment]
Autre question : le cache est passé de "APC" à "File".
Pouvez-vous expliquer ce changement qui peu avoir beaucoup d'impacts ?

**Comment by kdubuc** [comment]
Petite erreur de ma part, une config de développement passée sur GitHub, mais normalement c'est corrigé depuis la fin de semaine dernière, juste après que j'ai passé cette config ici : https://github.com/SDIS62/prevarisc/commit/bd3e384a9a086e709719beb8d8dcfbd7f48bfeef

**Comment by A511701** [comment]
J'ai trouvé un dépôt Packagist pour minify : "mrclay/minify": "~2.2"
Validez-vous le déport de cette lib dans les vendor ?

**Comment by A511701** [comment]
Au quel cas, nous nous en occupons bien sûr
