### ISSUE TITLE
Problème d'extension des fichiers pièces jointes

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#320]
Je ne peux pas ouvrir les fichiers pièces jointes des dossiers.
Je pense que cela est dut au fait de la présence de .DOC écrit en majuscule pour mes fichiers.
Pouvez-vous faire une modification pour que les majuscules soient ignorées?

**Comment by diasn** [comment]
Serait-il possible de faire la modification, car nous ne pouvons plus ouvrir les pièces jointes actuellement ?

**Comment by kdubuc** [comment]
Dans la table piecejointe, les extensions sont en majuscule ?

**Comment by diasn** [comment]
Non, ce sont les noms des fichiers dans le dossiers pièces jointes qui le sont (exemple: 1305132.DOC)

**Comment by kdubuc** [comment]
oui, dans le dossier de stockage. Mais dans la base de données, les extensions le sont elles aussi ? (champ EXTENSION_PIECEJOINTE dans la table piecejointe)

**Comment by diasn** [comment]
Non, elles sont bien en minuscule:

![image](https://cloud.githubusercontent.com/assets/6367639/5167203/df2d6b82-73f6-11e4-988f-e13d425b7db4.png)

**Comment by kdubuc** [comment]
Je viens de me rendre compte que je t'ai fait dire deux fois la même réponse, désolé !
Okay, donc c'est pour cela que Prevarisc n'arrive pas à ouvrir la pièce jointe. Tu as utilisé un ETL pour lier les pièces jointes ?

**Comment by diasn** [comment]
Non, j'ai migré les données à partir des exports ERPV 2 dans des fichiers .xls que j'ai trnasformés en .csv pour les importer dans la base.

Les fichiers nommés en .DOC en majuscules, l'étaient déjà dans le dossier de sauvegarde d'ERPV2.

**Comment by diasn** [comment]
Je pense que le code d'ouverture des pièce jointes dans prevarisc est sensible aux caractères majuscules/minuscules. Peut-on le modifier pour qu'il prenne en compte les deux types de noms de fichiers?

**Comment by kdubuc** [comment]
Ce n'est pas le code mais le filesystem qui l'est. Pour résoudre ton problème, il faut que tu convertisse via une moulinette les extensions pour les mettre en majuscule.

**Comment by diasn** [comment]
Ok, je vais faire ça.
