### ISSUE TITLE
Impossible de mixer utilisaer LDAP et non LDAP

### ISSUE THREAD

**Issue by fbeauchamp** [SDIS62/prevarisc#323]
Bonjour, 
    Le paramètre LDAP est une case à cocher par utilisateur, alors qu'il s'agit d'un paramètre global défini dans l'environnement.

   SI ok, je prépare un patch pour pouvoir mixer les deux ( ldap pour les utilisateurs internes, base de données pour les autres) , avec un flag dans table utilisateurs + la mise à jour du scenrio de modif d'un utilisateur

Merci

Florent

**Comment by kdubuc** [comment]
Je ne comprend pas, la case à cocher est pour indiquer que le compte est à identifier sur l'AD (si le LDAP est configuré dans prevarisc), sinon les mots de passe sont stockés en BDD. Si le compte est à identifier dans l'AD, le mot de passe stocké sera null, c'est en quelque sorte notre flag.

**Comment by fbeauchamp** [comment]
ok , je cherchais un flag quelque part pour une injection depuis l'extérieur.
