### ISSUE TITLE
Dossiers: accès impossible

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#324]
Suite à la dernière mise à jour version 2.x@9cc27bf

Voici l'erreur qui apparaît lorsque je veux accéder à un dossier :

Parse error: syntax error, unexpected '<<' (T_SL) in /var/www/prevarisc/application/controllers/DossierController.php on line 1037

Avez-vous une solution?

**Comment by kdubuc** [comment]
Je n'ai jamais rencontré le problème, c'est sur une page en particulier ? Par exemple, les pièces jointes du dossier sont-elles accessibles ?

**Comment by diasn** [comment]
Non, tous les dossiers sont inaccessibles et renvoient cette erreur.

**Comment by kdubuc** [comment]
as tu relancé un `git pull` pour avoir la dernière mise à jour ?

**Comment by diasn** [comment]
C'est réglé, merci!

**Comment by kdubuc** [comment]
:wink:
