### ISSUE TITLE
Natures dans le type de dossier Etude

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#327]
Il manque des natures dans le type de dossier Etude:
- Certificats d'urbanisme (CU)
- Permis d'aménager (PA)

Pouvez-vous les rajouter?

**Comment by kdubuc** [comment]
Il nous faut les types de champs à faire apparaître pour ces natures pour les rajouter !

**Comment by diasn** [comment]
Les mêmes que pour une AT
