### ISSUE TITLE
Génération de document : Convocations des membres communes

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#328]
Le segment "infosDoss" a récemment été retiré pour les membres de types "communes" pour les génération de commission :

```
  #$infosDoss = $villeODF->setSegment('infosDoss');
```

Or, nous avons une boucle sur les dossiers qui se trouvent sur la commune concernée. Or vu qu'il n'y a plus de segments nous n'aurons que le 1er dossier qui sera indiqué.

Avez-vous des informations à ce sujet ?

**Comment by kdubuc** [comment]
poke @alucard62 ?

**Comment by ghost** [comment]
Le segment semble avoir été retiré lors de ce commit : https://github.com/SDIS62/prevarisc/blob/e048ff34458e89a5f4157900635e29ef860f223a/application/views/scripts/calendrier-des-commissions/generationconvoc.phtml
Je n'ai pas d'informations supplémentaire concernant la raison.
Quels sont les effets sur la génération ? Cela provoque t-il une erreur ?
Je n'ai pas encore effectué de tests et je n'ai pas eu de retour concernant un problème sur cette partie
