### ISSUE TITLE
Export des résultats de recherche : indispensable

### ISSUE THREAD

**Issue by sla33** [SDIS62/prevarisc#332]
Après plusieurs mois de travail, nous avons finalisé notre reprise des données, nous pourrions passer sur Prevarisc mais il manque une fonctionnalité indispensable : l'esport des résultats de recherche.
En effet actuellement ERPV2 met à disposition du groupement Prévention un requêteur qui permet de faire un grand nombre d'interrogations de la base. Ainsi le groupement peut répondre aux nombreuses demandes, souvent nouvelles, qui lui sont adresseées pour sortir des listes d'établissements selon un ou plusieurs critères.
Or dans Prévarisc on peut lister les établissements mais seulement à l'écran : aucun moyen de répondre à une demande de la Direction pour le groupement Prévention, à moins de déranger systématiquemnt le groupement informatique pour qu'il extraie les données en base, ce qui n'est pas acceptable.
Il est donc nécéssaire de prévoir un export des résultats de recherche vers calc (calc permet de les retravailler.
Les critères de recherches disponibles dans établissements/Lister sont suffisants. L'export devrait comprendre les éléments suivants pour chaque établissement :
- Code établissement
- Commission
- Commune
- Adresse
- Type
- Catégorie
- Ouvert
- Avis
- Date dernière visite.
  Comptez-vous mettre en place cette fonctionnalité ?
  Comment les sdis qui sont sur Prevarisc aujourd'hui peuvent fonctionner sans elle ?
  Si vous l'intégrerez aux  statistiques (bien que cela n'en soit pas) il faudra reprendre tous les critères de recherche présents dans établissements/lister

**Comment by kdubuc** [comment]
L'outil recherche a été conçu pour trouver des établissements dans la base et aider l'utilisateur à y accéder. Il n'a jamais été question d'en faire un BO-like. Il est vrai toutefois que l'outil est devenu assez puissant puisqu'il peut ressortir des listes assez simplement.

Pour l'instant, il n'est pas possible d'exporter le résultat de la recherche.

A la question "Comment les sdis qui sont sur Prevarisc aujourd'hui peuvent fonctionner sans elle ?", je pense qu'ils mettent en place un univers BO, ou tout simplement des requêtes spécialisées pour ressortir des indicateurs. Dans quasiment l'ensemble des cas, les services informatique et prévention travaillent ensemble sur le projet Prevarisc, ce qui facilite les demandes et échanges particuliers.

Malgré tout, nous allons pouvoir à nouveau aider la communauté dans la génération de rapport car nous sommes en train de réaliser les extractions INFOSDIS sous iReport. Un travail assez long mais qui va porter ses fruits d'ici la fin d'année.

**Comment by A511701** [comment]
Bonjour,

En effet, les SDIS qui font le choix de Prévarisc optent pour une solution de Reporting annexe. L'objectif de Prévarisc est de se concentrer sur la prévention. La partie reporting est laissée aux applications dont c'est la fonction première.

Si vous souhaitez des solutions à ce niveau, nous pouvons vous aider.
N'hésitez pas à me contacter.

**Comment by sla33** [comment]
@A511701
Je ne considère pas que sortir une liste d'établissements soit du reporting. Pour moi ça fait partie du métier, les applications métier sont censées fournir un minimum de requêtes de base pour travailler. C'est d'ailleurs ce que fait ERPV2, c'est pourquoi nous nous attendions à trouver au minimum les mêmes fonctionnalités qu'avant.
Nous ne nous étions pas rendu compte que le choix de Prevarisc entrainait la construction  à côté d'un infocentre à la charge de chaque sdis (pour faitre les même requêtes, quel dommage)
Merci en tout cas de votre proposition d'aide, je pense qu'on peut mettre en place des solutions nous-même mais c'est touours intéressant d'échanger sur le sujet. Pour l'instant nous n'avons pas de solution de reporting annexe car tout simplement les autres applications métier répondent aux besoins métier.
En tout cas nous n'utiliserons pas BO, il n'est pas chez nous et c'est en opposition avec le choix qui a été effectué pour Prevarisc d'opter pour des solutions libres

**Comment by kdubuc** [comment]
Pensez plutôt à tout ce que ERPV2 ne fait pas :wink: 
Encore une fois c'est un projet participatif, nous sommes ouvert à toutes propositions / réalisations des contributeurs, et si jamais un module d'extraction de la recherche voit le jour, je vous tiendrai informé.
