### ISSUE TITLE
Affichage de la liste des catégories de prescriptions types

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#336]
Serait-il possible d'améliorer la présentation des catégories des prescriptions types dans la fenêtres de choix pour un dossier?

Actuellement tout s'affiche à la suite comme ci-dessous, pourriez-vous créer un affichage en liste ou même liste de choix par catégorie?
![image](https://cloud.githubusercontent.com/assets/6367639/5227518/ebb6f162-76fc-11e4-9dce-0152f6fbfd84.png)

**Comment by kdubuc** [comment]
La partie prescription est actuellement en pleine refonte ;-)
