### ISSUE TITLE
Création Utilisateur: récuperer les informations utilisateurs existantes

### ISSUE THREAD

**Issue by diasn** [SDIS62/prevarisc#338]
Lors de la création d'un nouvel utilisateur, pourrait-on ajouter un bouton pour récupérer les information se trouvant déjà dans la base de données dans la table utilisateursinformations.
Par exemple, pour les mairies, on a les coordonnées des mairies.

**Comment by kdubuc** [comment]
Il est possible de le faire, mais directement en base de données. Un raccourcis graphique est une bonne idée, je la mets de côté ;)
