### ISSUE TITLE
Problème lors de la connection à prevarisc

### ISSUE THREAD

**Issue by sionicolas** [SDIS62/prevarisc#346]
Bonjour à tous, à la fin de l'installation du logiciel prevarisc lors du test de connection à l'adresse "prevarisc.sdisxx.fr" (sdis11 pour moi) je rencontre une erreur que je n'arrive pas à résoudre celà m'affiche une page blanche avec ce message.

Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /var/www/prevarisc-2.x/vendor/sebastian/git/src/Git.php on line 152

Mes compétences en programmation étant limitées je m'en remet à vous pour trouver une solution.
PS: 
version de prevarisc utilisé: prevarisc-2.x
version Debian: debian-7.8.0-i386-xfce via VirtualBox

Merci d'avance.

**Comment by sionicolas** [comment]
Problème résolu.

**Comment by Thierrysdis58** [comment]
Bonjour,

J’essaie moi aussi d’installer prevarisc pour le SDIS58 et je rencontre de nombreux problème en particuliers lors de la première connexion en root.
Avez-vous réussi ? Si oui pourriez-vous me donner des informations sur votre configuration ? Je tombe sur l’erreur suivante :
-   « Erreur d'authentification SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
  Merci d’avance de votre retour.
  Cordialement.

Thierry LAVALETTE

De : sionicolas [mailto:notifications@github.com]
Envoyé : vendredi 6 février 2015 08:43
À : SDIS62/prevarisc
Objet : Re: [prevarisc] Problème lors de la connection à prevarisc (#346)

Problème résolu.

**Comment by sionicolas** [comment]
Bonjour avez vous, dans la base de données prevarisc modifié la clé 'PASSWD_UTILISATEUR' qui se trouve dans la table 'utilisateur' ?

**Comment by Thierrysdis58** [comment]
Oui j’ai modifié la clé comme on me la préconisé (ci-joint copies écran) , j’ai essayé de créer des utilisateurs mais en vain.
A noter que j’accède à ma base mysql sans problème. De votre côté êtes-vous arrivé à vous connecter sur Prevarisc ?
Merci de votre retour.

Cordialement

Thierry LAVALETTE

Erreur connexion prevarisc
[cid:image002.png@01D04215.3D872D80]

Table utilisateur prevarisc

[cid:image002.jpg@01D0415F.48CF5430]
Fichier du virtualHost

[cid:image001.png@01D0415F.48CF5430]

Table utilisateur de mysql

[cid:image005.png@01D04215.3D872D80]

De : sionicolas [mailto:notifications@github.com]
Envoyé : vendredi 6 février 2015 13:41
À : SDIS62/prevarisc
Cc : Thierry LAVALETTE
Objet : Re: [prevarisc] Problème lors de la connection à prevarisc (#346)

Bonjour avez vous, dans la base de données prevarisc modifié la clé 'PASSWD_UTILISATEUR' qui se trouve dans la table 'utilisateur' ?

**Comment by sionicolas** [comment]
Je suis arrivé à me connecter à Prevarisc mais ce n'était pas le exactement la même type d'erreur que vous. La mienne était due à une erreur de renseignement sur la base de données dans le fichier "apache.conf".
Je vous conseille de vérifier si les informations lié à la BDD que vous avez entré dans apache.conf sont exactes.
Tout ce qui commence par PREVARISC_DB ...

**Comment by Thierrysdis58** [comment]
La situation est débloqué, il s'agissait effectivement d'un mauvais paramètrage dans le vhost
Je vous remercie de votre aide.
Cdt

**Comment by Thierrysdis58** [comment]
Etant connecté en root , je ne possède pas les droits d'administration, j'ai un profil "groupe par défaut" et la création n'est pas pas autorisée.
y a t-il une table à modifiée en particuliers, j'ai vérifié les tables ressources et privilèges et tout le semble correct.
Merci d'avance ppiur votre aide.
Cdt

**Comment by kdubuc** [comment]
Vous pouvez ajouter le droit manuellement en base en ajoutant une ligne
dans groupe-privilege avec comme valeurs :
ID_GROUPE = 1
id_privilege = 11

**Comment by sionicolas** [comment]
De rien, je suis moi aussi bloqué à se point, normalement pour avoir les droits il faut allez dans "groupe privilège" 
idgroupe = 1 (correspondant à au groupe par défaut qui inclut root)
idprivilege = 11 (correspondant au privilège d'administration) 
J'ai donc modifié ceci mais ça ne marche pas pour moi et je ne trouve pas de solution.

**Comment by fbeauchamp** [comment]
ici, j'ai un groupe admin  :  le groupe 2 ( je ne sais plus si c'est un groupe que j'ai crée ou un grouep existant), et j'ai ajouté tous les privilèges dans la table `groupe-privileges`

**Comment by sionicolas** [comment]
je viens de faire exactement la même chose en passant root dans un autre groupe que j'ai crée en lui donnant les privilèges admin, ça ne marche toujours pas.

**Comment by Thierrysdis58** [comment]
De mon côté , j'ai réalisé la même manip c'est  à dire :
création d'un nouveau groupe 
création d''un nouvel Id_groupe avec tous les id_preivilege existants 
nouvel affectation id_groupe pour l'utilisateur root dans la table utilisateur
Je me retrouve ainsi avec le profil administrateur pour root

**Comment by sionicolas** [comment]
Est ce que quelqu'un sait où est placer le fichier "export.anc" pour commencer la récupération de la base de données sur "erpv2"

**Comment by joe55** [comment]
bonjour
j'ai exactement le meme soucis que vous :Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /var/www/prevarisc-2.x/vendor/sebastian/git/src/Git.php on line 152
qu'elles sont vos corrections pour que cela fonctionne?
Merci

**Comment by Thierrysdis58** [comment]
Bonjour,
J'aimerais savoir comment exporter la base de données ERPV2 pour migration vers Prevarisc 

Merci

**Comment by kdubuc** [comment]
Voici les documentations d'installation et de reprise des données rédigées à l'occasion des formations de l'année dernière, si ça peut aider. https://apps.sdis62.fr:4000/prevarisc/Documentation_PREVARISC.zip
