### ISSUE TITLE
Probleme connexion prevarisc en root

### ISSUE THREAD

**Issue by Thierrysdis58** [SDIS62/prevarisc#348]
Bonjour,

Je ne parviens pas à me connecter à Prevarisc en root , le message d'erreur affiché est le suivant :
" Erreur d'authentification Les identifiants ne correspondent pas" 
A quoi cela correspond t-il ? Je ne sais pas ou trouver le fichier secret.ini qu'il faut apparement initailiser.
Merci de vos réponses.
Cdt

**Comment by Thierrysdis58** [comment]
Bonjour,
Le problème est résolu, la clé de security_salt du vhost était apparemment incorrecte

**Comment by Thierrysdis58** [comment]
Je tombe sur une nouvelle erreur de connexion en root
« Erreur d'authentification SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)
Auriez-vous des informations concernant ce problème
Merci d'avance . Cdt

**Comment by kdubuc** [comment]
Vous avez un problème de connexion à votre base de données. Vérifiez vos variables d'environnement, prevarisc n'arrive pas à contacter le serveur de BDD.

**Comment by Thierrysdis58** [comment]
Merci pour vos informations, j'ai effectivement modifié le Password de mon fichier vhost et maintenant je peux accéder à prevarisc.
cdt

**Comment by SDIS91** [comment]
Bonjour

J'ai le même problème de premiere identification. Vous dites que la clé security_salt était apparemment incorrecte. Quelle est la bonne?

Merci
