### ISSUE TITLE
Suppression d'un groupement de communes

### ISSUE THREAD

**Issue by SDIS-Vendee** [SDIS62/prevarisc#349]
Bonjour,
la suppression d'un groupement de communes ne fonctionne pas.
La suppression semble effectuée à l'affichage, mais le groupement de communes réapparait à la connexion suivante.

![2015-02-10_11h59_19](https://cloud.githubusercontent.com/assets/8723308/6126025/5a27eb34-b11c-11e4-95ab-d0ac3e4173f8.jpg)

Merci.

**Comment by kdubuc** [comment]
Vous avez toujours le soucis ?
