### ISSUE TITLE
Erreur Zend: Resource 'dashboard' not found 

### ISSUE THREAD

**Issue by dtenet** [SDIS62/prevarisc#352]
Bonjour à tous,

lors de l'installation de prevarisc sur un nouveau serveur, j'obtiens une erreur Zend concernant le tableau de bord juste après l'invite de connexion.
Cette installation est toute récente et je n'ai pas eu encore l'occasion de me connecter à l'application.
L'import du schéma s'est passé sans erreur ainsi que les remplissages des données initiales.
Pourriez-vous m'éclairer sur le paramétrage manquant?

erreur complète:

``` javascript
Stack trace:

#0 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Acl.php(846): Zend_Acl->get('dashboard')
#1 /var/www/prevarisc/application/services/User.php(81): Zend_Acl->isAllowed('Groupe par d\xC3\xA9f...', 'dashboard', 'view_ets_avis_d...')
#2 /var/www/prevarisc/application/controllers/IndexController.php(17): Service_User->getDashboardData('1')
#3 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): IndexController->indexAction()
#4 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#5 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#6 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(101): Zend_Controller_Front->dispatch()
#7 /var/www/prevarisc/application/Bootstrap.php(16): Zend_Application_Bootstrap_Bootstrap->run()
#8 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Application.php(366): Bootstrap->run()
#9 /var/www/prevarisc/public/index.php(72): Zend_Application->run()
#10 {main}    

Request Parameters:

array (
  'controller' => 'index',
  'action' => 'index',
  'module' => 'default',
)    
```

![2015-02-17 16_33_39-accueilaccueil - internet explorer](https://cloud.githubusercontent.com/assets/6303197/6230800/bd9ff7d2-b6c2-11e4-9d21-24036678c4d8.png)

**Comment by fbeauchamp** [comment]
Est ce que vous avez la ligne "dashboard"  dans la table ressource 
Chez moi, id = 100, name=dashboard,  text =Tableau de bord

**Comment by dtenet** [comment]
non ! je n'ai que trois lignes dans cette table:
    1   gestion_parametrages    Gestion et Paramétrages
    2   commission  Gestion des calendriers des commissions
    3   creations   Gestion des droits de création

**Comment by dtenet** [comment]
Effectivement le fichier prevarisc.sql contenu dans le répertoire prevarisc-2.x\sql\init\ ne contient que trois lignes.
Par contre, le dossier prevarisc-2.x\sql\migrations contient 16 autres fichiers SQL avec des modifications des différentes tables, y compris la table resources.
Je vais exécuter l'ensemble de ces fichiers et je vous tient au courant.

**Comment by dtenet** [comment]
L'execution des commandes SQL  des fichiers 2.1-08-ressourcesdashboard.sql et  2.2-10-corretionresourcesdashboard.sql ont bien résolu mon problème.

merci pour l'aide.
