### ISSUE TITLE
Erreur dans les ACL - Impossible d'afficher un établissement pour tous les utilisateurs

### ISSUE THREAD

**Issue by dtenet** [SDIS62/prevarisc#355]
Bonjour,

Je rencontre un problème sur l'accès aux fiches établissements. Les ACL me bloquent l'accès à tous les utilisateurs. J'ai créé des groupes d'utilisateurs supplémentaires en plus du Groupe par défaut. Tous les groupes ont pour le moment toutes les cases cochées dans la matrice des droits. Cependant, aucun utilisateur n'a accès à cette fiche établissement, y compris le compte root. 
A noter: pour pouvoir créer mon premier établissement, j'ai dû ajouter un champ DROITPUBLIC_ETABLISSEMENTINFORMATIONS dans la table etablissementinformations. Ce champs était manquant lors du remplissage inital de la base et j'avais un message d'erreur à la création. (voir pièce jointe)

![2015-02-19 09_57_17-etablissement _ fiche etablissement](https://cloud.githubusercontent.com/assets/6303197/6263890/28b7a950-b81e-11e4-84e8-666c66dfd4d2.png)

![2015-02-18 22_15_29-dossiers _ ajouter un dossierdossiers _ ajouter un dossierdossiers _ ajouter un](https://cloud.githubusercontent.com/assets/6303197/6263885/1d0e7048-b81e-11e4-8b2d-de16f8234db2.png)

Merci pour votre aide.

**Comment by dtenet** [comment]
Bonjour à la communauté,

auriez-vous une piste pour résoudre mon problème d'ACL pour visualiser un établissement?

Merci par avance.

**Comment by fbeauchamp** [comment]
Est ce qu'il ne vous manquerait pas des patch sql vu que vous avez du creer une colonne a la main ?

**Comment by dtenet** [comment]
J'ai repris l'ensemble des patchs SQL contenus dans init et migration et je n'ai pas constaté de différences. J'aurais voulu donc avoir des explications sur la gestion des ACL dans l'application.

**Comment by dtenet** [comment]
Bonjour,

après une reprise complète de l'installation de Preverisc, j'ai toujours mon problème d'accès à ma fiche établissement m'indiquant que je n'ai pas les droits. Quelqu'un pourrait-il m'envoyer le contenu des tables "resources" et "privileges"?

**Comment by kdubuc** [comment]
Pour reprendre dans l'ordre : 
- Vous êtes parti du script init/prevarisc.sql ou avec vous effectué les migrations ?
- En vous connectant avec le compte root avez vous accès à l'espace admin des utilisateurs ?
- Avez vous créé des ressources spécialisées ?

**Comment by dtenet** [comment]
Bonjour,

au vu des nombreux tests que j'ai pu faire, je suis reparti sur une installation depuis le fichier zip de github. Je rencontre un autre problème. J'obtiens le message suivant:

Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /var/www/prevarisc/vendor/sebastian/git/src/Git.php on line 152

auriez-vous une idée de l'origine de ce problème?

**Comment by dtenet** [comment]
Je corrige mon problème après avoir trouvé la raison:
J'ai fait l'installation de prevarisc depuis le fichier zip téléchargé sur github et je n'ai pas les informations de git nécessaire au module git de sebastian permettant l'affichage de la version du commit. J'ai donc refait une installation avec la commande git clone https://github.com/SDIS62/prevarisc.git. L'erreur fatal indiquée a ainsi disparu.

**Comment by dtenet** [comment]
concernant mon problème de droits, le script d'init prevarisc.sql ne contient pas de data pour la table groupe-privilèges.
J'ai modifié la table groupe-privilèges manuellement. J'ai ajouté un enregistrement pour chaque ID présent dans la table privilèges pour le groupe par défaut.
