### ISSUE TITLE
Migration données de ERP V2 vers PREVARISC en erreur

### ISSUE THREAD

**Issue by hfondereSDIS73** [SDIS62/prevarisc#357]
Je procède actuellement à la reprise des données contenues dans l'application ERP V2 vers l'application PREVARISC avec utilisation de la procédure fournie nommée  
"ETL de ERP 2 vers Prevarisc.doc". 
Je rencontre des difficultés sur la phase de chargement de la base prevarisc MYSQL à partir des données déjà chargées dans la base TAMPON SQL. 
Le package "2.1 Alim habitations.dtsx" tombe en erreur avec erreur d'insert sur la table etablissementinformations pour cause d'erreur avec les FK sur commission et etablissement. 
Merci de votre aide.

**Comment by dtenet** [comment]
Bonjour,

Pourriez-vous me fournir la procédure de reprise des données de ERPV2 vers Prevarisc?

merci !

**Comment by hfondereSDIS73** [comment]
Bonjour,
je vous fais suivre la procédure par retour mail.
Cordialement,

**Comment by hfondereSDIS73** [comment]
Bonjour, 
en pièce jointe la procédure que vous nous avez fourni. 

Cordialement, 

---

Hélène FONDERE 
SDIS 73 
Groupement Systèmes d'Information et de Communication 

## 04 79 60 88 07 

----- Mail original -----

De: "dtenet" notifications@github.com 
À: "SDIS62/prevarisc" prevarisc@noreply.github.com 
Cc: "hfondereSDIS73" hfondere@sdis73.fr 
Envoyé: Lundi 16 Mars 2015 21:10:50 
Objet: Re: [prevarisc] Migration données de ERP V2 vers PREVARISC en erreur (#357) 

Bonjour, 
Pourriez-vous me fournir la procédure de reprise des données de ERPV2 vers Prevarisc? 
merci !

**Comment by amaignotSDIS12** [comment]
Bonjour,
Je suis également intéressé par la documentation "ETL de ERP 2 vers Prevarisc.doc"
Par avance, merci !
Cordialement,

**Comment by adimpre** [comment]
Bonjour,

Voici la documentation demandée. Par contre je ne peux pas joindre un .zip avec l'ensemble des documents. En effet, à côté de cette documentation, il y a le projet visual studio qui a servi pour l'ETL.
[ETL de ERP 2 vers Prevarisc.docx](https://github.com/SDIS62/prevarisc/files/18314/ETL.de.ERP.2.vers.Prevarisc.docx)
Cordialement,

**Comment by SDIS91** [comment]
> Le package "2.1 Alim habitations.dtsx" tombe en erreur avec erreur d'insert sur la table etablissementinformations pour cause d'erreur avec les FK sur commission et etablissement.

Bonjour
Je recontre le même problème, est-cwe qu'il a eu une réponse?

Merci d'avance

**Comment by sdis52** [comment]
Bonjour , j'ai aussi le soucis avec la table Alim habitation , sauf que mon erreur est : 

"Impossible de créer de jointures parce que la colonne « date » et la colonne « date_etablissementinformations » n'ont pas de propriétés de métadonnées équivalentes."

Avez-vous une solution ? Merci d'avance 
Cdlmt

**Comment by adimpre** [comment]
Bonjour,

Je viens de vérifier, les données sont bien concordantes, ce sont toutes les 2 des DBTIMESTAMP.
Dans la base staging, vous avez bien le champ "date" de la table Etablissement_Winprev en DATETIME ?

**Comment by sdis52** [comment]
Merci pour cette réponse rapide , et bien oui elle est bien en « datetime » en voici la preuve :

[cid:image001.png@01D1A468.B5121430]

De : adimpre [mailto:notifications@github.com]
Envoyé : lundi 2 mai 2016 11:44
À : SDIS62/prevarisc
Cc : Raphaël LESEUR; Comment
Objet : Re: [SDIS62/prevarisc] Migration données de ERP V2 vers PREVARISC en erreur (#357)

Bonjour,

Je viens de vérifier, les données sont bien concordantes, ce sont toutes les 2 des DBTIMESTAMP.
Dans la base staging, vous avez bien le champ "date" de la table Etablissement_Winprev en DATETIME ?
