### ISSUE TITLE
Positionnement des POI directement sur la carte IGN

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#369]
Bonjour,

Le positionnement d'un POI directement sur la carte IGN est-elle une fonctionnalité existante ? Cette fonctionnalité a-t-elle existé dans les versions précédentes de Prévarisc ?

Merci pour votre aide,

**Comment by kdubuc** [comment]
Oui ! Dans la gestion des couches cartographiques, on peut rajouter des flux WMS.

**Comment by A511701** [comment]
Pardon je me suis mal exprimé : le positionnement de POI dont la position de l'établissement par clic sur la carte IGN est-elle une fonctionnalité existante ? Cette fonctionnalité a-t-elle existé dans les versions précédentes de Prévarisc ?

**Comment by kdubuc** [comment]
Donc ajouter directement sur Prevarisc une donnée cartographique ? non, et pour moi ce n'est pas le but de l'application. C'est au SIG du SDIS à créer de la valeur ajoutée aux cartes intérogées par Prevarisc, pas l'inverse. La seule donnée cartographique saisie dans l'application est l'adresse (qu'elle soit postale, ou autre), ce qui a un sens au niveau prévention.

**Comment by A511701** [comment]
Peut-on aujourd'hui cliquer sur la carte IGN pour ajouter l'adresse de l'établissement ?

**Comment by kdubuc** [comment]
Non, on peut imaginer un clic déclenchant l'ouverture de la boite modale de création avec la latitude / longitude pré-rempli.

**Comment by A511701** [comment]
Merci !

**Comment by A511701** [comment]
Fonctionnalité ajoutée, merci par Atos via la prestation SDIS28
