### ISSUE TITLE
Avis des dossiers

### ISSUE THREAD

**Issue by Panda2a** [SDIS62/prevarisc#371]
Bonjour,
Suite à l'installation de la v2 de Prevarisc, j'ai récupéré les données de la v1.2 que nous utilisions jusqu'à présent.
J'ai un problème d'affichage au niveau des avis dans les dossiers : le menu déroulant affiche plusieurs valeurs identiques comme dans l'issue #262.
Le problème vient certainement du fait que j'ai 5 valeurs dans la table avis au lieu de 2 selon ce que vous semblez dire.
Le problème est que dans les champs AVIS_DOSSIER de la table dossier, j'ai des valeurs de 1 à 4 qui correspondent aux critères suivants de ma table avis : 
1 - N'a pas pu se prononcer
2 - Favorable
3 - Défavorable
4 - Avis différé
5 - Ne nécessite pas d'avis

Comment puis-je résoudre ce problème ? Merci

**Comment by kdubuc** [comment]
- Pour n'a pas pu se prononcer', il vous faut créer une requête SQL pour que NPSP_DOSSIER = 1 quand AVIS_DOSSIER = 1;
- Pour Favorable', il faut déplacer l'avis à l'id 1, et créer une requête SQL pour passer l'id AVIS_DOSSIER à 1 (idem pour defavorable, avec id = 2) ;
- Pour Avis différé, il vous faut créer une requête SQL pour que DIFFERE_AVIS = 1 quand AVIS_DOSSIER = 4 ;
- Pour ne nécessite pas d'avis, AVIS_DOSSIER = null

**Comment by Panda2a** [comment]
Merci beaucoup. 
Je clos
