### ISSUE TITLE
Gestion des couches cartographiques

### ISSUE THREAD

**Issue by Panda2a** [SDIS62/prevarisc#375]
Bonjour,
J'ai un abonnement avec une clé IGN. Cet clé a été rentrée dans le fichier de configuration.

Comment est-ce que je peux avoir accès à ma carto dans la gestion des couches cartographiques ? : si je crée une nouvelle couche, il me demande le type (WMS), un nom une URL,...

Quelles sont les données à mettre dans ces champs sachant que le fond de carte ne s'affiche pas par défaut ?

Merci

**Comment by fbeauchamp** [comment]
Il y a une feinte : à la différence des couche carto métier,  la clé IGN ( et la clé google) se configurent dans le paramétrage de l'environnement 

Il s'agit de la clé PREVARISC_PLUGIN_IGNKEY , définie dans la doc d'installation https://github.com/SDIS62/prevarisc/blob/2.x/docs/documentation_installation.md

**Comment by Panda2a** [comment]
Merci de la réponse mais c'est bien ce que j'ai fait.

Est-ce qu'il faut créer une couche dans la gestion des couches cartos ou est-ce que cela est géré directement via la clé définie dans les variables d'environnement ?

Par ailleurs, je suis en train de changer toute la base adresse de façons à mettre le type de voie dans le nom de la voie comme cela est recommandé pour le moment. Est-ce que le problème pourrait venir d'une adresse non existante (sachant que le nom des communes est existant et que l'établissement est bien rattaché à sa commune) ?

J'ai par ailleurs constaté que je ne peux pas saisir le nom de la voie dans la fiche établissement. Peut-être est-ce en rapport avec une mauvaise base adresse et que ceci empêche la géoloc ?

**Comment by fbeauchamp** [comment]
La couche IGN n'apparaît pas dans la gestion desc ouches WMS. Les couches cartos sont là pour ajouter des couches métiers ( par exemple les points d'eaux, les ERP, ....) par dessus le fond de cart( IGN ou google)

Lorsque la clé est ajoutée ET si l'ERP a une longitude/latitude (table etablissementadresse , colonnes LAT_ETABLISSEMENTADRESSEet LNG_ETABLISSEMENTADRESSE) il y a un petit encart carto qui apparaît dans la fiche de l'établissement.

Le nom de la rue doit être présent dans la base adresse pour pouvoir être saisi manuellement
