### ISSUE TITLE
Migration base formation de sept 2014 jusqu'à aujourd'hui

### ISSUE THREAD

**Issue by SDIS79** [SDIS62/prevarisc#384]
Bonjour,
Je viens de mettre à jour notre base formation qui avait été installée lors de la formation suivi au SDIS62 en sept 2014. J'ai effectué : 
-le passage à la version 2.X (suite mail de K Dubuc du 30/10/2014)
-la mise à jour 'git pull'
-executer les requètes d'sql/migrations (env. 20 requètes)
Au lancement du navigateur, je tombe sur le message d'erreur suivant : 
Fatal error: Class 'SebastianBergmann\Git\Git' not found in /var/www/prevarisc-test/application/plugins/View.php on line 24

Pouvez-vous m'aider car je sèche ? SVP
Vous remerciant par avance.....
L. BONNIN
Resp. SIT
SDIS79

**Comment by kdubuc** [comment]
Vous avez déployé Prevarisc depuis un fichier zip, il n'y a donc plus de liaison avec la version Git. Je vous conseille de faire plutot un git clone https://github.com/SDIS62/prevarisc dans /var/www .
Sinon, si vous voulez rester sur les fichiers venants du zip, vous devez spécifier manuellement la version comme expliqué ici : https://github.com/SDIS62/prevarisc/blob/2.x/docs/documentation_installation.md#etape-2--installation-du-serveur-web (clés de configuration PREVARISC_REVISION & PREVARISC_BRANCH)

**Comment by kdubuc** [comment]
A moins que vous n'ayez pas exécuté composer install ?

**Comment by SDIS79** [comment]
Bonjour,
J'ai exécuté git clone et executer composer install (j'ai vu qu'il y avait des nouveaux répertoires sous vendor). Je tombe sur une page blanche sur le navigateur. Avez-vous une idée de ce que j'aurais pas fait ? SVP
Cordialement.

**Comment by fbeauchamp** [comment]
Est ce que vous pouvez exécuter la commande suivante ?

```
tail -f /var/log/apache2/error.log 
```

**Comment by SDIS79** [comment]
Bonjour M. Beauchamp,
CI-dessous le résultat de la commande : 
[Sun Mar 29 06:25:03 2015] [notice] Apache/2.2.22 (Debian) PHP/5.4.4-14+deb7u14 configured -- resuming normal operations
[Wed Apr 01 08:44:03 2015] 
[error] [client 192.168.3.57] PHP Fatal error:  Class 'Zend_Application' not found in /var/www/prevarisc/public/index.php on line 21
[Wed Apr 01 08:44:12 2015] 
[error] [client 192.168.3.57] PHP Warning:  require(/var/www/prevarisc-test/public/../application/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/prevarisc-test/public/index.php on line 18
[Wed Apr 01 08:44:12 2015] 
[error] [client 192.168.3.57] PHP Fatal error:  require(): Failed opening required '/var/www/prevarisc-test/public/../application/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/prevarisc-test/public/index.php on line 18
[Wed Apr 01 08:47:32 2015] 
[error] [client 192.168.3.57] PHP Fatal error:  Class 'Zend_Application' not found in /var/www/prevarisc/public/index.php on line 21

Nous avons actuellement 2 instances : Prevarisc et prevarisc-test.
Vous remerciant par avance pour votre retour d'info...
Cordialement.

**Comment by fbeauchamp** [comment]
Je suis un peu rouillé en PHP, mais je pense qu'il y a eu un soucis avec composer : Zend n'a aps été installé comme il faut.

**Comment by SDIS79** [comment]
Bonjour,
Savez-vous comment faire pour procéder à la ré-installation au propre de Zend_application ? SVP
Cordialement.

**Comment by kdubuc** [comment]
supprimez le dossier `vendor` et relancez `php composer install`

**Comment by SDIS79** [comment]
Effectivement, j'ai lancé "#php composer.phar update"  et ça fonctionne.
Merci M. Dubuc
