### ISSUE TITLE
Recherche du MCD à jour

### ISSUE THREAD

**Issue by IPV15** [SDIS62/prevarisc#388]
Serait il possible de remettre en ligne le MCD à jour de Prévarisc ?
En effet, nous cherchons à intégrer nos données et cela n'est pas possible sans.

En vous remerciant par avance,

Cordialement,

**Comment by fbeauchamp** [comment]
Si vous avez une base de données à jour, il est facile de régénérer le MCD depuis Mysql Workbench : 
https://dev.mysql.com/doc/workbench/en/wb-reverse-engineer-live.html

**Comment by IPV15** [comment]
Merci. C'est parfait.
Pourriez vous aussi me préciser comment disposer d'un dictionnaire des données à jour ?
Cordialement,
