### ISSUE TITLE
Mise à jour via GitHub

### ISSUE THREAD

**Issue by SDIS83Loic** [SDIS62/prevarisc#395]
Bonjour,

nous avons fait une installation il y a un an de prevarisc. Nous souhaitons mettre à jour Prevarisc.
lorsque je fais 
root@prevarisc-2:/var/www/prevarisc# git tag
v1.0.0
v1.1.0
v1.2.0
Lorsque je regarde sur l'interface dans la partie administration j'ai une version 1.2.1
1/ première interrogation qui dit vrai?

2/ j'ai déclaré le git de prevarisc et lancé la commande "git pull prevarisc". Puis j'ai eu un message demandant de choisir la branche. Donc j'ai excecuté la commande "git pull prevarisc 2.x". J'obtiens 
root@prevarisc-2:/var/www/prevarisc# git pull prevarisc 2.x
From https://github.com/SDIS62/prevarisc
- branch            2.x        -> FETCH_HEAD
  Already up-to-date.
  Il semble être à jour, mais comment savoir?
  Je ne suis pas utilisateur de GitHub. 

Avez-vous un lien ou un guide pour les mises à jour de Prevarisc?

Merci

Loic

**Comment by fbeauchamp** [comment]
il faut basculer sur la branche 2.X 

```
git checkout 2.x
```

Attention, il va y avoir une masse de patch sql a ne pas oublier ( et dans le bon ordre)

**Comment by SDIS83Loic** [comment]
J'ai une erreur lorsque j'excute la commande
git checkout 2.x
root@prevarisc-2:/var/www/prevarisc# git checkout 2.x
error: The following untracked working tree files would be overwritten by checko                                                                                                                               ut:
        .gitattributes
        .gitignore
        CONTRIBUTING.md
        LICENSE.md
        README.md
        application/Bootstrap.php
        application/controllers/AboutController.php
        application/controllers/AdminController.php
        application/controllers/CalendrierDesCommissionsController.php
        application/controllers/CommissionController.php
        application/controllers/ContactController.php
......
        application/models/DbTable/Etablissement.php
        application/models/DbTable/EtablissementAdresse.php
        application/models/DbTable/EtablissementContact.php
        application/models/DbTable/Etabli
Aborting

**Comment by fbeauchamp** [comment]
Vous avez modifiés ces fichiers ? C'est possible si vous avez modifié le projet avec certains éditeurs qui vont modifier la mise en page par exemple, ou si vous avez mis à jour les fichiers par un autre moyen que git.

Si vous voulez revenir exactement dans l'état de base :  

```
git reset --hard 
```

Et ensuite vous pouvez retenter le changement de branche

**Comment by SDIS83Loic** [comment]
Suite de mon chemin:

RESET [git reset --hard]

> root@prevarisc-2:/var/www/prevarisc# git reset --hard
> HEAD is now at 7180026 Merge pull request #394 from fbeauchamp/patch-4

CHANGEMENT DE BRANCHE [git checkout 2.x]

> root@prevarisc-2:/var/www/prevarisc# git checkout 2.x
> Already on '2.x'

RECUPERATION [git pull]

> root@prevarisc-2:/var/www/prevarisc# git pull
> There is no tracking information for the current branch. Please specify which branch you want to merge with. See git-pull(1) for details
>    git pull <remote> <branch>
> If you wish to set tracking information for this branch you can do so with:
>    git branch --set-upstream 2.x <remote>/<branch>

Lorsque j'essai le pull en ajoutant la branche 2.X [git pull origin 2.x]

> root@prevarisc-2:/var/www/prevarisc# git pull origin 2.x
> From https://github.com/SDIS62/prevarisc
> - branch            2.x        -> FETCH_HEAD
>   Already up-to-date.

Mon installation initiale a été faite depuis le ZIP récupérer sur le site du GitHub.
Je crois que j'ai raté une étape?

**Comment by fbeauchamp** [comment]
Là, je pense que tu es en 2.x et à jour. (surtout que je connais bien le gars qui à fait le dernier commit :smile: )

Que donne le contenu du dossier sql/migrations (ce dossier n'existe pas en 1.x) ?

 Par contre, il aurait été mieux de commencer par un git clone pour être sûr que git ne perde pas ses petits. Ca vaut peut être le coup de repartir de là, dans un autre dossier.

**Comment by SDIS83Loic** [comment]
Bon voilà ou j'en suis. Je suis reparti du début depuis mon répertoire /var/www/prevarisc/

>  git init
>  git clone https://github.com/SDIS62/prevarisc
>  git checkout 2.x
>  git pull

Maintenant je suis dans la mise à niveau des tables. Pas facile! Pas mal d'erreur due certainement au delta. je m'appui sur la structure du init pour mettre à niveau la base puis je passerai sur les mises à jour.

Sinon j'ai une erreur lors de l'accès à Prevarisc 

> Fatal error: Class 'SebastianBergmann\Git\Git' not found in /var/www/prevarisc/application/plugins/View.php on line 24
> J'espère que cela disparaitra après la mise à niveau de la structure des tables?

**Comment by fbeauchamp** [comment]
Ne pas oublier d'installer les dépendances ( étape 3 de https://github.com/SDIS62/prevarisc/blob/2.x/docs/documentation_installation.md ) 

```
curl https://getcomposer.org/installer | php
php composer.phar install --prefer-source
```

**Comment by SDIS83Loic** [comment]
Merci pour l'info des dépendances

> root@prevarisc-2:/var/www/prevarisc# php composer.phar install --prefer-source

J'ai injecté la base init.
Mais je rencontre des erreurs avec les scripts de migrations. Sont-ils nécessaires après l'écrasement par le prevarisc.sql?

**Comment by fbeauchamp** [comment]
Non, il ne sont utiles que si vous aviez une base active et que vous ne souhaitiez pas la remettre à zéro, sans conserver les données.

**Comment by SDIS83Loic** [comment]
Bon super, c'est du temps de gagné, s'il n'y a pas les modifications SQL.
Maintenant, j'ai un problème d'authentification. La base est brute de démarrage.
Lorsque que je rentre le mot de passe de root fourni dans la doc. je suis en échec.
La chaine de cryptage est PREVARISC_SECURITY_SALT 7aec3ab8e8d025c19e8fc8b6e0d75227 est la même.
:-( 
Avez-vous changé le mot de passe?
