### ISSUE TITLE
Prescriptions pour les études de demandes de dérogation : anomalie ?

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#406]
La possibilité de créer des prescriptions n'est pas autorisée pour les dossiers de nature étude  >  demande de dérogation.

Est-ce normal ou une anomalie ?

**Comment by A511701** [comment]
Avez-vous un historique sur ce sujet ?

**Comment by kdubuc** [comment]
L'ajout de prescription est filtré par une condition dans le code ici https://github.com/SDIS62/prevarisc/blob/2.x/application/layouts/dossier.phtml#L34 

La demande de dérogation est donc volontairement dépourvue de l'ajout de prescription.

Dès que j'ai des infos métiers précises sur le pourquoi du comment, je reposte ici.

**Comment by A511701** [comment]
Merci beaucoup, le sdis28 est intéressé par la raison métier :)

**Comment by kdubuc** [comment]
Donc, après avoir demandé à nos préventionnistes : réglementairement, les éléments prescriptifs issus du service d'incendie se retrouvent dans les mesures complémentaires disponible dans la première page, d'ou l'inutilité de la partie prescription dans les demandes de dérogation.

**Comment by A511701** [comment]
Merci beaucoup pour votre réponse !
