### ISSUE TITLE
Erreurs commit ba4489cbca1fb88765c43442efb2a7cb0cca3e6a

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#411]
Le dernier commit ba4489cbca1fb88765c43442efb2a7cb0cca3e6a comporte quelques coquilles :
- 2.4-25-ressourcesdashboard.sql ne passe pas : ERROR 1406 (22001) at line 3: Data too long for column 'text' at row 1
- la modification n'est pas impactée dans le sql d'init : sql/init/prevarisc.sql

Merci,

**Comment by kdubuc** [comment]
C'est corrigé, merci du retour !
