### ISSUE TITLE
date de dernière visite

### ISSUE THREAD

**Issue by fbeauchamp** [SDIS62/prevarisc#413]
Bonjour, 

   Est ce que les date de visite avant ouverture ne devraient pas comptée comme une date de dernière visite ? 

Merci 

Florent

**Comment by A511701** [comment]
Bonjour,

Ce point a été ajouté cette semaine sur le bloc "ets sans dernière visite programmée" (à minima).
Reste à voir sur la fiche établissement en effet.

**Comment by fbeauchamp** [comment]
Je pensais surtout à la méthode findLastVpCreationDoc dans dbTable/Dossier.php 

Merci

**Comment by A511701** [comment]
Tout à fait
