### ISSUE TITLE
Installation error : Failed to download zendframework/zendframework1 from source

### ISSUE THREAD

**Issue by aJClibre** [SDIS62/prevarisc#418]
Bonjour,

Nous rencontrons une erreur lors de l'installation de Prevarisc
$ su -
$ cd /var/www/ 
$ wget  https://github.com/SDIS62/prevarisc/archive/2.x.zip
$ 7z x 2.x.zip
$ mv prevarisc-2.x/ prevarisc/
$ chmod 755 prevarisc/
$ cd prevarisc
$ curl https://getcomposer.org/installer | php
$ php composer.phar install --prefer-source
= > Failed to download zendframework/zendframework1 from source: The process "git clone --no-checkout 'git://github.com/zendframework/zf1.git' '/var/www/prevarisc/vendor/zendframework/zendframework1' && cd '/var/www/prevarisc/vendor/zendframework/zendframework1' && git remote add composer 'git://github.com/zendframework/zf1.git' && git fetch composer" exceeded the timeout of 300 seconds.
    Now trying to download from dist

le dossier vendor/zendframework est alors vide.

Avez-vous une piste pour résoudre ce problème ?

Merci pour votre réponse.

**Comment by fbeauchamp** [comment]
Ici, c'est le proxy qui m'avait fait pas mal de misère. Est ce que vous en avez un ? 
Si oui, est ce que git est configuré pour l'utiliser ? La documentation est ici : http://labs.excilys.com/2011/03/29/git-derriere-un-proxy/ 

Au passage, je pense qu'il vaut mieux faire un 

```
  git clone -b 2.x https://github.com/SDIS62/prevarisc.git
```

au lieu de wget/unzip/mv. Cela vous simplifiera les mise à jour ultérieures

**Comment by aJClibre** [comment]
Effectivement il s'agissait bien du proxy. L'installation c'est bien déroulée. Merci pour l'info.
Par contre impossible de nous connecter en root / root. Nous avons donc été obligés de modifier application/controllers/SessionController.php (ligne 53).
