### ISSUE TITLE
Adresse Etablissement

### ISSUE THREAD

**Issue by pcano65** [SDIS62/prevarisc#422]
Bonjour,

Une fois une adresse créé pour un ERP, il n'est pas possible de la modifier, il faut la retirer et la recréer.
Est il possible d'ajouter une option de modification ?

Merci.

**Comment by pcano65** [comment]
Bonjour,

Toujours concernant l'adresse, le complément n'apparait pas sur la fiche.
Est il possible de le faire apparaitre ?

Merci.

**Comment by kdubuc** [comment]
Le complément apparait désormais sur la fiche établissement 😉
