### ISSUE TITLE
Problème importation de la BD Erpv2 vers prevarisc

### ISSUE THREAD

**Issue by sionicolas** [SDIS62/prevarisc#424]
Bonjour, lors de l'importation d'une table (adressecommune) qui est au format (.csv séparateur - point virgule), toutes les données se mettent sur la premiere colonne. Par conséquent l'importation échoue.

Je précise que j'ai utilisé excel 2007 pour les mettre à ce format.

Merci d'avance pour vôtre aide.

**Comment by adimpre** [comment]
Bonjour,

Je pense que votre problème vient du séparateur dans le fichier CSV.
Le séparateur de colonnes pour l'importation d'un fichier CSV est par défaut une virgule.
Il faut donc enregistrer votre CSV avec comme séparateur la virgule ou modifier le séparateur par défaut par un point-virgule.

**Comment by sionicolas** [comment]
C'était ça,  Merci !
