### ISSUE TITLE
Mise à niveau 2.x -> 3.x

### ISSUE THREAD

**Issue by 21Damien** [SDIS62/prevarisc#427]
Bonjour,

Je viens d'installer la version 2.x de Prevarisc jusqu'à lors sans soucis.
La migration vers 3.x se complique un peu. Le nouveau design est bien présent, mais les fonctionnalités plus véritablement accessibles. 
En effet, après avoir fusionné les différents dossiers, je me retrouve avec des erreurs d'accès à certains controllers comme l'administration :
- Erreur (script 'components/user.phtml' not found in path (/var/www/prevarisc3x/application/views/layouts/:/var/www/prevarisc3x/application/views/scripts/))

Mais aussi lors de l'ajout de dossier (fonctionnalité du menu) : 
- Fatal error: Call to a member function isAllowed() on boolean in /var/www/prevarisc3x/application/controllers/DossierController.php on line 244

Par ailleurs que contient la vers 3.x comme nouveautés et/ou fonctionnalités ?

PS : je viens de prendre mes fonctions au SDIS 21 et donc j'en profite également pour me présenter à vous.

Merci d'avance.

Damien

**Comment by kdubuc** [comment]
La version 3.x est pour l'instant une version expérimentale. Beaucoup de fonctionnalités développées pour la 3.x ont été portées vers la 2.x.
Le développement de la 3.x reprendra quand l'ensemble des points sur lesquels nous devons encore travailler seront résolus.
