### ISSUE TITLE
PB Geocodage

### ISSUE THREAD

**Issue by pcano65** [SDIS62/prevarisc#450]
Bonjour
On a remarqué que l'API du Geoportail de L'iGN, sur lequel se fait le geocodage de l'ERP à travers l'adresse renseignée, avait quelques bugs. En effet, sur certaines communes des Hautes-Pyrénées, qui ont un ou plusieurs homonymes en France, le geocodeur de l'iGN choisit la commune qui, d'après nous, a le numéro INSEE le plus bas. Comme notre département commence par 65, les communes des Hautes-Pyrénées ne sont pas choisies en premier sauf à avoir une adresse avec une voie référencée.
Seule solution quand on n'a pas de voie pour l'ERP, il faut essayer de saisir une voie qui serait référencée dans la commune pour que la fenêtre carto matche sur la commune étudiées afin de repositionner le X Y de l'ERP. Puis il faut enlever la voie et choisir "Voie non référencée".

**Comment by kdubuc** [comment]
je close ce ticket en faveur de https://github.com/SDIS62/prevarisc/issues/361 qui traite du même sujet
