### ISSUE TITLE
Prescriptions types : ajout hors textes et hors article ?

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#457]
Bonjour,

Dans l'administration, gestion des prescriptions types, dans l'arbre de classement, il est possible d'ajouter des prescriptions types à des niveaux intermédiaires (au niveau catégorie et article).

Cependant, de notre côté, cela génère des erreur de type "Incorrect integer value: '' for column 'PRESCRIPTIONTYPE_ARTICLE'".

Avez-vous la même erreur ? Est-ce une possibilité souhaitée ?

**Comment by ghost** [comment]
Bonjour,
J’ai effectué différents tests sur cette partie et je n’ai pas eu ce problème.
Vous rencontrez cette erreur à chaque ajout dans une « sous-catégorie » ? Ou alors, dans un cas particulier ?
Cette fonctionnalité est disponible pour laisser à chaque sdis le choix dans la gestion et l’organisation de ses prescriptions types.

**Comment by A511701** [comment]
OK, le problème est fixé par un cast en (int) sur les variables POST récupérées du client au niveau des identifiants des clés étrangères.
Est-ce que ce fix vous convient ?
