### ISSUE TITLE
Affichage des groupements de communes sur la Fiche d'informations générales

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#464]
Après complétion dans "administration/groupements de communes", les Groupements s'affichent dans l'ordre de saisie.
Est-il possible de les ranger dans un ordre plus fonctionnel (Département -> Arrondissement -> Canton -> Interco...) qui est en fait celui du menu déroulant dans administration ?
![prevarisc - tri des groupements de communes 16-10-2015](https://cloud.githubusercontent.com/assets/5104791/10542952/fa26a77a-741b-11e5-84ca-0a3c375f3b8e.jpg)

**Comment by kdubuc** [comment]
c'est une bonne idée, je vous tiens au courant de la mise en place de la correction

**Comment by olivierbcr** [comment]
Merci.

**Comment by olivierbcr** [comment]
C'est fonctionnel maintenant. Merci.
