### ISSUE TITLE
1iere connexion Prevarisc

### ISSUE THREAD

**Issue by SDIS79** [SDIS62/prevarisc#465]
Bonjour,
Nous venons, aujourd'hui, de terminer l'installation de PREVARISC. Tout s'est bien passé mais nous n'arrivons pas à nous connecter sur le logiciel pour la 1ere fois avec le login ROOT/root. Avez-vous une idée pour débloquer cette situation ? SVP
Cordialement.
LB - SDIS79

**Comment by ghost** [comment]
Bonjour,
Je pense que vous pouvez trouver des réponses à votre problème dans cette discution :
https://github.com/SDIS62/prevarisc/issues/233#issuecomment-149575570

Sinon, avant de tenter des manipulations vous pouvez essayer avec le longin/mdp: root/root (en minuscule)

**Comment by SDIS79** [comment]
Merci pour votre retour d'info. ça marche...
Il me reste plus qu'à solutionner le pb du ldap qui ne veut pas fonctionner alors qu'on a tout fait...
Cordialement...
