### ISSUE TITLE
PB d'installation de prevarisc sur Oracle VirtualBox

### ISSUE THREAD

**Issue by aechinard** [SDIS62/prevarisc#467]
Bonjour,

J'installe actuellement prevarisc comme indiqué sur la doc sur une VirtualBox équipée de Debian. Or tout fonctionne bien mais quand j'accède à http://prevarisc.sdis99.fr, une page blanche apparaît et je ne peux rien faire, aucun message d'erreur... J'ai refait l'installation 6 ou 7 fois et je ne sais pas d'ou cela vient. Je n'y connais pas plus que ça en linux et je patauge. Si quelqu'un peut me donner des pistes.

Merci par avance

**Comment by ghost** [comment]
Bonjour,
Et en tapant l’adresse ip du serveur ça fait pareil ?

[nathalie denis]

De : aechinard [mailto:notifications@github.com]
Envoyé : vendredi 6 novembre 2015 15:08
À : SDIS62/prevarisc
Objet : [prevarisc] PB d'installation de prevarisc sur Oracle VirtualBox (#467)

Bonjour,

J'installe actuellement prevarisc comme indiqué sur la doc sur une VirtualBox équipée de Debian. Or tout fonctionne bien mais quand j'accède à http://prevarisc.sdis99.fr, une page blanche apparaît et je ne peux rien faire, aucun message d'erreur... J'ai refait l'installation 6 ou 7 fois et je ne sais pas d'ou cela vient. Je n'y connais pas plus que ça en linux et je patauge. Si quelqu'un peut me donner des pistes.

Merci par avance

**Comment by aechinard** [comment]
Non, je tombe sur la page Apache2 Debian Default Page. J'ai du louper quelque chose dans la config...
Est-ce que le fichier sercret.ini est toujours d'actualié car le dossier configs n'existe pas dans l'arborescence de prevarisc/application ? Je l'ai créé ainsi que le fichier au cas ou.
Faut-il renseigner obligatoirement les valeurs suivantes dans apache2.conf : 
PREVARISC_CACHE_ADAPTER
PREVARISC_CACHE_HOST
PREVARISC_CACHE_PORT

**Comment by ghost** [comment]
Je vous joint une partie du support que j'ai utilisé pour réaliser l'install.
En espérant que cela vous aide.

De : aechinard [notifications@github.com]

Date d'envoi : mercredi 11 novembre 2015 16:00

À : SDIS62/prevarisc

Cc : INFORMATIQUE

Objet : Re: [prevarisc] PB d'installation de prevarisc sur Oracle VirtualBox (#467)
[X]
[X][X]
aechinard
Non, je tombe sur la page Apache2 Debian Default Page. J'ai du louper quelque chose dans la config... — Reply to this email directly or view it on GitHub.
mer. 16:00
[X]
[X][X]
Nathalie DENIS
Bonjour, Et en tapant l’adresse ip du serveur ça fait pareil ? De : aechinard [mailto:notifications@github.com] Envoyé : vendredi 6 novembre 2015 15:08 À : SDIS62/prevarisc Objet : [prevarisc] PB d'installation de prevarisc sur Oracle VirtualBox (#467)
ven. 06/11
[X]
[X][X]
aechinard
Bonjour, J'installe actuellement prevarisc comme indiqué sur la doc sur une VirtualBox équipée de Debian. Or tout fonctionne bien mais quand j'accède à http://prevarisc.sdis99.fr, une page blanche apparaît et je ne peux rien faire, aucun message d'erreur...
ven. 06/11

**Comment by aechinard** [comment]
Je n'ai pas trouvé de fichier joint...

**Comment by fbeauchamp** [comment]
Je pense qu'il s'agit d'un problème de paramétrage réseau.

Est ce que , pour test , vous pouvez ajouter un ligne  hosts file de votre machine [documentation ici ](http://www.commentcamarche.net/faq/5993-modifier-son-fichier-hosts) 
La ligne sera  `<adressip> prevarisc.sdis99.fr`

**Comment by aechinard** [comment]
Oui, c'est tout bon. Comme je suis sur la même machine et que je souhaite accéder localement à prévarisc j'ai paramétré le fichier host de la manière suivante : 127.0.0.1 prevarisc.sdis07.fr
L'accès à la base de données à partir de Debian avec Workbench fonctionne bien quand je teste la connexion sous workbench. L'adresse IP donnée pour celle-ci est 127.0.0.1 sur le port 3306...
Le fichier apache2.conf est renseigné de cette façon :

<VirtualHost *:80>
    ServerName prevarisc.sdis99.fr
    DocumentRoot /var/www/prevarisc/public
    SetEnv APPLICATION_ENV “production”
    SetEnv PREVARISC_DB_CHARSET utf8
    SetEnv PREVARISC_DB_HOST 127.0.0.1
    SetEnv PREVARISC_DB_USERNAME root
    SetEnv PREVARISC_DB_PASSWORD root
    SetEnv PREVARISC_DB_DBNAME prevarisc
    SetEnv PREVARISC_CACHE_LIFETIME 10
    SetEnv PREVARISC_SECURITY_SALT 7aec3ab8e8d025c19e8fc8b6e0d75227
    SetEnv PREVARISC_DEBUG_ENABLED 0
    <Directory /var/www/prevarisc/public>
        DirectoryIndex index.php
        AllowOverride all
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>

J'ai vraiment suivi la doc à la lettre. Certains points ne sont pas clairs comme les données du fichier host à utiliser sur une machine virtuelle ou encore le paramétrage de workbench sur debian.
Sur firefox, l'icone quand j'accède à prevarisc est bien le bon ainsi que l'url mais aucun champ ne s'affiche pour se loguer. C'est incompréhensible. Est-ce que cela fonctionne vraiment avec une machine virtuelle ?

Merci beaucoup pour votre aide.

**Comment by fbeauchamp** [comment]
Là c'est plus une problématique réseau, comment annoncer aux machines du réseau que le serveur prevarisc.sdis99.fr correspond à l'adresse ip 

Est ce que vous avez des messages d'erreurs dans le log apache ? pour le savoir lancez la commande `tail -f /var/log/apache2/error.log` et essayez de charger la page.

Dans tous les cas, l'installation d'un serveur demande quelques connaissances d'administration système, ce n'est pas lié à Prevarisc

**Comment by ghost** [comment]
Bonjour, oui prevarisc fonctionne parfaitement avec une machine virtuelle.

La configuration de prevarisc dans apache doit normalement se faire à l'aide d'un fichier Virtual Host (dans l'emplacement /etc/apache2/site-available/prevarisc.sdisxx.fr ).

Essayez de retirer ce que vous avez ajouté dans le fichier apache2.conf puis de créer le vhost tel que décrit dans la doc : https://apps.sdis62.fr:4000/prevarisc/Documentation_PREVARISC.zip

**Comment by aechinard** [comment]
Merci pour vos réponses. Je vois tout cela demain. La doc est beaucoup plus complète que celle par défaut. Merci encore.
