### ISSUE TITLE
Dans le dashboard, le bloc "Etablissement sans prochaine VP cette année" n'affiche pas les établissements visitables cette année

### ISSUE THREAD

**Issue by CO16** [SDIS62/prevarisc#475]
Bonjour,

il semble que dans le dashboard "Etablissement sans prochaine VP cette année", les établissements visitables en 2015 n'apparaissent pas. En revanche, les établissement à visiter en 2014 qui n'ont pas été visités apparaissent.

Les établissement visitables en 2015 apparaissent quand on modifie l'horloge système pour se mettre au 01/01/2016.

Si vous confirmez que ce fonctionnement est effectivement anormal, la modif semble être à faire dans models/DbTable/Etablissement.php dans la méthode "listeErpOuvertsSansProchainesVisitePeriodiques" en remplaçant un "<" par "<=".

**Comment by A511701** [comment]
Bonjour,

Ce bloc avait été pensé pour alerter sur les établissement "en retard de visite". Si vous passez en 2016, ceux en retard de 2015 apparaissent.
Ce bloc n'est pas destiné à préparer les visites sur 2016, mais uniquement à alerter en cas de non planification d'une visite en aval.
