### ISSUE TITLE
SQL - dépôt tables prescriptions, textes règlementaires, articles

### ISSUE THREAD

**Issue by 21Damien** [SDIS62/prevarisc#480]
Bonjour,

Vu lors de la formation (24/11 -> 27/11/2015), partie utilisateur, serait-il possible de mettre en téléchargement les tables prescriptions, textes règlementaires, articles du SDIS62 ?

Merci d'avance.

**Comment by olivierbcr** [comment]
Bonjour Kevin,
Même demande que "21Damien". 
Encore merci pour l'aide au paramétrage pendant la formation...

**Comment by fbeauchamp** [comment]
Ca m'intéresse aussi .

**Comment by kdubuc** [comment]
Je package tout ça pour demain :wink:

**Comment by olivierbcr** [comment]
```
Le 03/12/2015 16:45, Kévin DUBUC a
  écrit :


  Je package tout ça pour demain  
  —
    Reply to this email directly or view
      it on GitHub.








Merci.

--
```

**Comment by kdubuc** [comment]
Et voila : https://github.com/SDIS62/prevarisc/tree/2.x/sql/fixtures

**Comment by 21Damien** [comment]
Super merci :+1:

**Comment by olivierbcr** [comment]
Merci beaucoup Kévin.

**Comment by fbeauchamp** [comment]
merci
