### ISSUE TITLE
Création nouveau ERP - défilement continu du "sablier"

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#481]
Bonjour,
A la création d'un nouveau dossier le "sablier" défile en continu.
En quittant cet écran on constate que le dossier est pourtant bien enregistré et fonctionnel.
Avez-vous également ce comportement ?
Cordialement,
![022 - creation dossier - defilement continut](https://cloud.githubusercontent.com/assets/5104791/11476436/05096788-9783-11e5-9f04-e5bfa0e64926.jpg)

**Comment by olivierbcr** [comment]
Après quelques essais complémentaires, cela se produit dans le sous-menu "études" (AT, PC...) mais pas avec "visite de commission" ou "groupe de visite"...

**Comment by kdubuc** [comment]
Si vous pouviez me donner plus d'information sur les requêtes effectuées par Prevarisc grâce à la console de debug (http://www.alsacreations.com/astuce/lire/1436-console-javascript.html) onglet "Network", ça serait plus simple pour nous pour avoir une idée de ce qu'il se passe :confused:

**Comment by olivierbcr** [comment]
```
Le 01/12/2015 09:46, Kévin DUBUC a
  écrit :


  Si vous pouviez me donner plus d'information sur les requêtes
    effectuées par Prevarisc grâce à la console de debug (http://www.alsacreations.com/astuce/lire/1436-console-javascript.html)
    onglet "Network", ça serait plus simple pour nous pour avoir une
    idée de ce qu'il se passe  
  —
    Reply to this email directly or view
      it on GitHub.








OK...

--
```

**Comment by olivierbcr** [comment]
Cela vous aide t-il ? (dans l'affirmative je suis bon pour quitter les préventionnistes et muter avec les informaticiens ?!)
![022bis - creation dossier - defilement continu](https://cloud.githubusercontent.com/assets/5104791/11528989/65dfde58-98ea-11e5-9092-699abe9dc459.jpg)

**Comment by olivierbcr** [comment]
Ce comportement ne se produit plus suite à l'installation de la dernière release, à priori...
