### ISSUE TITLE
PB Migration ERP-V2 vers PREVARISC

### ISSUE THREAD

**Issue by aechinard** [SDIS62/prevarisc#489]
Bonjour,

Merci pour les documents fournis la dernière fois qui m'ont permis d'installer PREVARISC avec un environnement virtuel. Au passage, j'en ai profité pour utiliser les docs pour réaliser la migration des données d'ERP V2 vers PREVARISC. Tout fonctionne sans erreur sauf sur la tables des établissements ou je bute sur l'étape de transformation de la chaine en tableau. J'ai une erreur de script qui me dit les choses suivantes : 
Le composant Script a rencontré une exception dans le code utilisateur : 
Nom du proje SC_1b3301ff0cef44598c32d2b54ae01af0
La référence d'objet n'est pas définie à une instance d'un objet.
à ScriptMain.Entrée0_ProcessInputRow(Entrée0Buffer Row)
à ScriptMain.Entrée0_ProcessInput(Entrée0Buffer Buffer)
à UserComponent.ProcessInput(Int32 InputID, String InputName, PipelineBuffer, OutputNameMap, OutputMap)
à Microsoft.SqlServer.Dts.Pipeline.ScriptComponent.ProcessInput(Int32 InputID, PipelineBuffer buffer)
à Microsoft.SqlServer.Dts.Pipeline.ScriptComponentHost.ProcessInput(Int32 inputID, PipelineBuffer buffer)

Si j'ai bien suivi, ce script transforme une chaine de caractères en tableau sous forme d'entiers.
La source est composée de la sorte : 1,10;15;16
Le 1 est le numenreg (Int32 / DT_I4) et le reste est une chaine de caractères en entrée (String / DT_WSTR) puis des entiers en sortie.

Avez-vous une idée du problème rencontré ? Les données de ma base peuvent-elles générer une erreur similaire ?

Merci par avance.

**Comment by adimpre** [comment]
Bonjour,

Avez-vous tenté de regénérer le script ?
C'est à dire d'ouvrir le script en sélectionnant "modifier le script" dans l'éditeur de transformation de script. Puis en faisant un clique droit sur la solution et en choisissant "regénérer".

**Comment by aechinard** [comment]
Oui, cela à été déjà fait... Vous me confirmez bien qu'en entrée on récupère une chaîne de caractères composée de chiffres et de points virgules et qu'on ressort uniquement avec des entiers : 
1,4;5;6;  => 1 4 5 6 (apparemment)

**Comment by adimpre** [comment]
Le code permet de séparer les différents code ERP pour un établissement
Donc pour 1,4;5;6;
1 correspond au code de l'établissement et 4;5;6; à 3 codes ERP
On va retourner 3 lignes :
- 1 4
- 1 5
- 1 6

**Comment by aechinard** [comment]
C'est bien ce que j'avais compris avec le contenu du script avec le split et la boucle qui suit.

**Comment by aechinard** [comment]
OK, le problème est réglé. Cela provenait bien de la base de données. Des codes ERP contenaient des espaces ou des valeurs vides...
Tout fonctionne bien jusque là.
Merci pour les réponses.
