### ISSUE TITLE
Numéros de téléphones portables mal stockés en base.

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#490]
A l'ajout d'un n° de téléphone portable, via le menu Administration / Gestion des utilisateurs / Général, celui-ci est stocké en base dans l'emplacement réservé au fax.
![023 utilisateur information - tel mobile - ecran base et saisie](https://cloud.githubusercontent.com/assets/5104791/11641553/1c930f74-9d39-11e5-840f-c1d766de1c07.jpg)

**Comment by kdubuc** [comment]
Effectivement, le label utilisé n'était pas le bon, merci pour le retour : https://github.com/SDIS62/prevarisc/commit/20e2b96e60909be8ac55977b2de6f7cad5ddde2b

**Comment by olivierbcr** [comment]
Encore merci pour cette correction
