### ISSUE TITLE
Reports - image manquante

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#493]
Bonjour,

Les rapports jasper contient semble-t-il un asset manquant : 
C:\Users\adimpre.SDIS62\Documents\ireport\infosdis.jpg

Est-ce normal ?

**Comment by adimpre** [comment]
Bonjour,

J'ai effectivement oublier de fournir l'image infosdis avec les rapports.
Je vous joins l'image. Je vais voir pour l'ajouter avec les rapports jasper.
![infosdis](https://cloud.githubusercontent.com/assets/4126540/11833165/3460cfb4-a3c0-11e5-8b4e-2460de716a92.jpg)

**Comment by A511701** [comment]
Aucun problème, nous espérons faire avancer le smilblick ;)
