### ISSUE TITLE
Reports - procédure d'installation

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#494]
Bonjour,

Savez-vous où se trouve la procédure d'installation des rapports jaspert pour que les SDIS puissent les installer ?
En particulier :
- la liste des champs d'entrée du rapport
- l'arborescence à respecter avec le subreports
- le paramétrage des data-sources

Merci,

**Comment by adimpre** [comment]
Bonjour,

Aucune documentation n'a été réalisée. Je vais en réaliser une, merci pour votre retour

**Comment by A511701** [comment]
Aucun problème, merci pour les sdis utilisateurs ! :)

**Comment by kdubuc** [comment]
Et voilà : https://github.com/SDIS62/prevarisc/blob/2.x/docs/ireport%20-%20procedure%20installation.md
