### ISSUE TITLE
Prescriptions types - rappels règlementaires - Field NUM_PRESCRIPTION_DOSSIER default value

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#495]
Bonjour,

La structure de bdd de la table perscriptiondossier du SDIS62 en prod correspond-elle au schéma communautaire sur git ?
En effet, lors du paramétrage d'un rappel règlementaire, on obtient "Field NUM_PRESCRIPTION_DOSSIER" doesn't have a default value.

Merci,

**Comment by ghost** [comment]
Bonjour,
Oui, la structure de la bdd en prod au SDIS62 correspond bien au schéma communautaire (j’entends par là le prevarisc.sql du dossier init).
Vous rencontrez cette erreur lors d’un paramétrage de rappel réglementaire depuis la partie administration > gestion des prescriptions ?

**Comment by A511701** [comment]
Bonjour,
Nous rencontrons cela lorsqu'une prescription en ajout automatique sur un dossier est paramétrée et qu'on ajoute un dossier.
La PR #510 fixe ce problème normalement.
