### ISSUE TITLE
Reports - paramétrage du numéro du SDIS dans l'entête

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#496]
Bonjour,

Afin que les rapports jasper soient utilisables par tous les SDIS, il serait intéressant que le numéro du SDIS dans l'entête soit paramétrable.
C'est un détail.

**Comment by adimpre** [comment]
Bonjour,

Je vais regarder pour mettre en place ce paramètre.
Merci

**Comment by A511701** [comment]
Merci !
