### ISSUE TITLE
Prescriptions types - Rappels règlementaires : désactivation de l'ajout par défaut ne fonctionne pas

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#497]
Bonjour,

Il semble que la désactivation de l'ajout d'un rappel règlementaire par défaut à un dossier ne fonctionne pas : "Ajouter par défaut à la création d'un nouveau dossier".

Constatez-vous aussi le problème ?

**Comment by ghost** [comment]
Je confirme, il existe effectivement un problème cette partie, je régle ça au plus vite.
Merci

**Comment by ghost** [comment]
Bonjour,
le PR #514 fixe normalement le problème de reprise des "rappels réglementaires"
