### ISSUE TITLE
Prescriptions types - Edition d'une prescription sous chrome/FF affiche des chosen à 0px

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#498]
Bonjour,

Rencontrez-vous ce problème ?
Sous chrome ou firefox, dans l'admin, gestion des prescriptions types, édition d'une prescription type, les chosen des textes et articles ont une largeur de 0px, lié au fade sur la modal. 
Chosen est initialisé avec un select non visible d'où le problème.

Même comportement en front côté dossier.

**Comment by A511701** [comment]
Pour info, le retrait du fade sur le modal solutionne le problème.

**Comment by ghost** [comment]
Bonjour, 
non, que ce soit avec Firefox ou Chrome, nous n'avons le problème que vous décrivez

**Comment by kdubuc** [comment]
Je peux close ?

**Comment by A511701** [comment]
Oui, du coup, nous avons fixé ce problème.
