### ISSUE TITLE
Historique établissement - dossiers donnant avis "Etude suite avis diff" et "CR de visite des organismes d'inspection"

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#499]
Bonjour,

Les nouvelles natures de dossiers donnant avis lié au commit 6b6e12d9d6955e211fbaa89ab4dadceeece444c6 ont-elles été répercutées dans l'historique de l'établissement, service Etablissement, fonction getHistorique ?

Merci,

**Comment by kdubuc** [comment]
Vous avez totalement raison, je corrige ça. Merci pour le retour.
