### ISSUE TITLE
Génération Doc depuis calendrier

### ISSUE THREAD

**Issue by pcano65** [SDIS62/prevarisc#502]
Nous avons des messages d'erreur lors de la génération de doc (Convocation, ODJ ...) depuis le calendrier.
Est ce normal ?

Exception information:

Message: 'grpLoop' segment not found in the document
Stack trace:
#0 /var/www/prevarisc/application/views/scripts/calendrier-des-commissions/generationconvoc.phtml(134): Odf->setSegment('grpLoop')

...

**Comment by olivierbcr** [comment]
Bonjour,
Je suis actuellement dans la création de 25 modèles de documents et j'ai eu plusieurs fois ce message. A priori Prévarisc ne trouve pas la boucle (loop) de début (BEGIN) et/ou de fin (END) d'un champ de fusion dans votre modèle.
Le conseil du SDIS62, qui a fonctionné dans mon cas, est de vérifier que lors du collage ou du déplacement de votre champ de fusion dans writer celui-ci n'a pas transformé automatiquement les 2 tirets en fin de chaîne par un seul tiret + large car il prends cela pour une faute de frappe. Exemple de ce qui se produit lors du déplacement du champ de clotûre de la partie "dossiers": 
[!-- END infosDoss --] devient [!-- END infosDoss –] et génère ce type de message d'erreur.
Cela se produit régulièrement lors de la manipulation des champs de fusion et n'est pas visible à l'oeil si le zoom du document writer est en dessous de 100 %.
N'étant pas informaticien j'espère que arriverez à me comprendre.
Cordialement,

**Comment by olivierbcr** [comment]
Par curiosité, vous êtes en poste au sein du SDIS 65 ?

**Comment by pcano65** [comment]
Bonjour,

Nous avons le problème uniquement sur les docs générés depuis le calendrier.
Pas de soucis pour générer les docs depuis le dossier.

Sinon, je suis bien en poste au SDIS 65 ;)

Cdlt.

**Comment by olivierbcr** [comment]
Pour nous aussi le problème se présentait uniquement depuis le calendrier, à la génération des ordres du jour notamment.
Voulez-vous mon modèle d'OdJ, juste pour le tester sur votre calendrier. Il a 3 champs encore non fonctionnels mais il ne génère plus de message d'erreur " 'grpLoop' segment not found..." et fonctionne.
Vous êtes informaticien ou préventionniste ?

**Comment by pcano65** [comment]
Informaticien.
Je veux bien l'ODJ pour tester. Vous pouvez me l'envoyer sur l'adresse patrice.cano@sdis65.fr
Merci.
