### ISSUE TITLE
Ajout de documents dans "Administration / Gestion des documents"

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#505]
Je ne peux ajouter des documents de fusion que dans la Sous-commission départementale.
Pour les autres commissions lors de l'ajout l'indicateur de chargement défile en continu sans résultat.
Il faut utiliser la touche ESC pour sortir.
Je pense à un problème venant de mon paramétrage mais sans arriver à localiser l'erreur.
Quelqu'un a t-il eu un comportement similaire ?
![019 - ajout document](https://cloud.githubusercontent.com/assets/5104791/11817534/87fb0182-a355-11e5-9c6c-60dfad7997be.jpg)

**Comment by ghost** [comment]
Bonjour,
le commit #449 a légèrement modifié la gestion des documents.

Les documents sont maintenant classés par commissions afin de faciliter la gestion.

Une arborescence particulière est donc nécessaire (sous-dossiers ayant comme nom l’ID de la commission) afin de fonctionner correctement.

Vérifiez que vous avez bien dans le dossier /data/uploads/documents/ l’ensemble des dossiers correspondant aux ID des commissions existantes. (0 étant le dossier par défaut pour les documents visible après verrouillage)

Si ce n’est pas le cas vous pouvez créer cette arborescence directement depuis la partie administration.

Pour cela : 
Allez dans la Gestion des commissions.
Cliquez sur le bouton Gestion des commissions situé en haut à droite.
Une boite de dialogue contenant l’ensemble des libellés/types des commissions va s’afficher.
Ne modifiez rien et cliquez simplement sur sauvegarder.
Cette action va normalement créer automatiquement l’arborescence nécessaire au bon fonctionnement.

Dans le cas où la cause est différente, il serait nécessaire d’avoir des informations supplémentaires récoltées via firebug ou l'outil équivalent de chrome.

**Comment by olivierbcr** [comment]
A nouveau fonctionnel
