### ISSUE TITLE
Evolution - Affichage dernière page consultée

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#506]
Serait-il possible de revenir par défaut sur la dernière page consultée avant déconnexion automatique (comme dans phpMyAdmin, par exemple). En effet, à la reconnexion on retourne sur le dashboard et l'on doit se souvenir de la page sur laquelle on travaillait pour y accéder à nouveau.

**Comment by kdubuc** [comment]
Et voila ! https://github.com/SDIS62/prevarisc/commit/16dd96062b8129df5ecdadbbd51aaabf6b2447fe

**Comment by olivierbcr** [comment]
Merci.
