### ISSUE TITLE
Evolution - Prochaines commissions

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#507]
Dans le dashboard, la brique "Prochaines commissions" n'affiche que les évènements du mois courant (calendaire).
Serait-il possible d'afficher les commissions sur au moins 30 jours "filants". Cela permettrait de voir la prochaine commission en salle dès la tenue effective de la dernière.
L'accès rapide par le dashboard devient vite indispensable aux utilisateurs, par rapport à une recherche classique, pour naviguer rapidement vers les commissions en salle, les avis défavorables...

**Comment by A511701** [comment]
Vous pourriez modifier la variable PREVARISC_DASHBOARD_NEXT_COMMISSIONS_DAYS à 30 dans votre vhost. C

**Comment by A511701** [comment]
Cela devrait faire l'affaire.

**Comment by olivierbcr** [comment]
Merci. J'ai demandé l'assistance d'un informaticien pour modifier cette variable...

**Comment by olivierbcr** [comment]
C'est fait et fonctionnel pour une période de 30 jours. 
Nous allons maintenant essayer 45 jours, pour avoir la visibilité sur 2 commissions qui se suivent à + d'un mois, lorsque la deuxième est programmée plusieurs jours après la date initiale (cas le plus défavorable, qui se présente parfois)
Encore merci.

**Comment by olivierbcr** [comment]
Ça fonctionne. Je clôture.
