### ISSUE TITLE
Accès non autorisé dès la consultation d'un dossier

### ISSUE THREAD

**Issue by aechinard** [SDIS62/prevarisc#508]
J'ai enfin réussi à migrer la base WINPREV vers PREVARISC avec les outils qui m'ont gentiment été fournis. La migration c'est bien passée. 
Aucun utilisateur n'ayant été récupéré à partir de WINPREV, je les ai créé à la main dans la base avec comme exemple une version de test fonctionnelle de PREVARISC.

Existe t-il une procédure pour récupérer automatiquement les utilisateurs de WINPREV et les importer sous PREVARISC ?

Merci à tous pour votre aide précieuse et efficace.

**Comment by sdis52** [comment]
Salut aechinard , je suis du SDIS52 et je suis entrain de migrer WINPREV vers PREVARISC . Mais je suis bloqué ! Quel(s) outil(s) as-tu utilisé ? Moi j'utilise le projet sous Microsoft visio , c'est ton cas ? 

Cordialement 
Raph

**Comment by aechinard** [comment]
Bonjour,

J'avais commencé la migration avec visio dans un premier temps mais le résultat n'étant pas concluant j'ai continué sous excel avec des macros et des grosses feuilles de calcul...

Cordialement

**Comment by sdis52** [comment]
Ah oui d’accord , n’étant pas un pro d’Excel et tous ce qui s’en suit je resterais sous visio ^^ En tous cas merci de votre réponse rapide !

De : aechinard [mailto:notifications@github.com]
Envoyé : lundi 2 mai 2016 11:25
À : SDIS62/prevarisc
Cc : Raphaël LESEUR; Comment
Objet : Re: [SDIS62/prevarisc] Accès non autorisé dès la consultation d'un dossier (#508)

Bonjour,

J'avais commencé la migration avec visio dans un premier temps mais le résultat n'étant pas concluant j'ai continué sous excel avec des macros et des grosses feuilles de calcul...

Cordialement
