### ISSUE TITLE
Amélioration - Tri du menu déroulant de sélection du service instructeur (Dossiers)

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#509]
Dans "administration/groupements de communes", les Services instructeurs s'affichent dans l'ordre de saisie. Comme nous sommes passés de 3 secteur DDTM à 17 communautés de communes + des dizaines de communes, la liste est maintenant très longue.
Est-il possible de les ranger dans l'ordre alphabétique pour faciliter leur sélection dans le menu déroulant par les préventionnistes ?
![027 - tri des services instructeurs](https://cloud.githubusercontent.com/assets/5104791/11907761/fad77e3c-a5d6-11e5-97fc-59b05468e3e2.jpg)

**Comment by kdubuc** [comment]
Et voila https://github.com/SDIS62/prevarisc/commit/b0cb7c2ef79b91b148a6bd938371e7b5be5eaf3a :wink:
