### ISSUE TITLE
Mise à jour "fixtures" prescriptions problème de contrainte

### ISSUE THREAD

**Issue by SDIS83Loic** [SDIS62/prevarisc#513]
Bonjour,

nous avons appliqué la fixture (prescriptions.sql) sur les prescriptions et nous rencontrons un problème de contraintes entre les tables prescriptiontype et prescriptiontypeassoc.
La table prescriptiontypeassoc contient des enregistrements non référencés : 
- ID_PRESCRIPTIONTYPE 2, 3, 6, 7, 8, 11, 14, 21, 49, 74, 76

17 enregistrements de la table prescriptiontypeassoc sont orphelins.

**Comment by SDIS91** [comment]
Bonjour

Même problème chez nous.

**Comment by kdubuc** [comment]
Effectivement, j'ai mis à jour la fixture https://github.com/SDIS62/prevarisc/commit/77276895676597cd440b076c55859517c5d9e680, désolé :no_mouth:
