### ISSUE TITLE
Questions diverses

### ISSUE THREAD

**Issue by aechinard** [SDIS62/prevarisc#515]
Bonjour,

J'ai quelques questions pour mener à bien la migration d'ERP vers PREVARISC 
- Peut-on accéder à prevarisc avec les identifiants utilisateurs de l'active directory ou doit-on créer des utilisateurs directement à partir de prevarisc ?
- Comment faites-vous pour mettre à jour votre base "voies et adresses" et la répercuter sur la base prevarisc ?
- Existe-il une méthode pour géolocaliser automatiquement tous les établissements ou faut-il modifier manuellement les fiches ?
- Les valeurs Divers0 (appelée CADASTRE dans la base), divers1 et divers2 d'ERP peuvent-elles être migrées (et dans quelle table) ?

Merci par avance.

**Comment by 21Damien** [comment]
Bonjour, 
- Oui il est possible d'accéder à Prevarisc avec les identifiants AD. Cependant, il convient de créer les utilisateurs dans Prevarisc avec le bon login et de cocher la case authentification LDAP.
- Pouvez vous préciser la question ?
- Pour traiter un grand nombre d'établissements. Utiliser le geocodeur https://adresse.data.gouv.fr/csv/ puis effectuer un traitement via mysql pour mettre à jour la géolocalisation des établissements directement en base de données.
- Divers 0 pour nous correspond à notre classement papier des archives. Nous avons mappé sur le champ identifiant de prevarisc. Les autres champs peuvent éventuellement trouver un champ donnée pour y être stockés (description par exemple)

**Comment by aechinard** [comment]
Bonjour 21Damien,

Merci pour vos réponses.
Concernant la 2ème question, je souhaiterai savoir d'ou proviennent les informations des adresses et comment sont-elles mise à jour (extraction base IGN, ...) car si l'on créé un établissement dont l'adresse est inexistante, on ne peut la rajouter à partir de l'application...
Divers 0 correspond pour nous aussi à  l'ancien numéro du classement papier, je vais donc le traiter comme une description je pense.

**Comment by 21Damien** [comment]
Les adresses proviennent d'une extraction de la BAN. Nous pensons qu'une mise à jour de la BAN 3 à 4 fois par an sera suffisante pour éviter le blocage dans la saisie d'adresse d'un établissement.

**Comment by aechinard** [comment]
Est-ce que vous pouvez m'en dire plus sur cette extraction. Il existe de nombreux doublons dans la BAN, vous ne gardez qu'une seule entrée ou toutes ? Comment est renseigné l'ID_RUE de la table adresse_rue ? Les mises à jour de la base sont réalisées par comparaison de la BAN avec votre base prevarisc ou tout est mis à jour ?

Je vous remercie par avance pour vos réponses.
