### ISSUE TITLE
Affichage "Mise à jour disponible" dans le Panneau d'administration

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#516]
Dans l'onglet Informations générales du Panneau d'administration, l'information "Mise à jour disponible sur SDIS62/prevarisc" reste actif même à la suite d'une mise à jour. 
![032 - admin - indicateur maj disponible](https://cloud.githubusercontent.com/assets/5104791/12350148/85d6c476-bb75-11e5-8b40-b31b011400c5.jpg)
Cela reste un bogue très mineur !

**Comment by kdubuc** [comment]
J'ai du pousser une mise à jour en même temps que vous, essayez à nouveau de mettre à jour Prevarisc !

**Comment by olivierbcr** [comment]
Après application des dernières mises à jour l'étiquette, de couleur bleue, "Mise à jour disponible sur SDI62/prevarisc" reste active:
![sans titre 1](https://cloud.githubusercontent.com/assets/5104791/12733980/2fdfe922-c93e-11e5-888e-6492b670184f.jpg)

**Comment by kdubuc** [comment]
Le problème venait du fait que le merge des contributions créait un commit en plus, le check de version en avait donc toujours un de retard, et il pensait que Prevarisc n'était pas à jour. C'est désormais résolu grâce à une mise à jour de GitHub permettant de squash les merges en un seul commit. 😉
