### ISSUE TITLE
Génération OdJ commission - Affichage d'un message d'erreur

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#517]
A la génération d'un ordre du jour de commission PREVARISC affiche:
![sans titre 2](https://cloud.githubusercontent.com/assets/5104791/12350707/04c36458-bb79-11e5-805b-d43028f10bc8.jpg)
Mon informaticien préféré a essayé de modifier le nombre de signes "<" dans les lignes de commandes sans succès.

**Comment by kdubuc** [comment]
Avez vous toujours le même soucis avec les dernières mises à jour ?

**Comment by SDIS83Loic** [comment]
C'est bon nous avons fait le test. Tout est rentré dans l'ordre.
Merci.

**Comment by olivierbcr** [comment]
Merci une nouvelle fois pour ces mises à jour...
