### ISSUE TITLE
Evolution - Sécurisation de l'ordre du jour

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#519]
Après ventilation horaire des dossiers d'un OdJ il est possible de sélectionner le bouton "Ne pas prendre en compte les heures", au risque de perdre cette planification et de devoir recommencer.
![034 - odj commission- securisation prise en compte des heures](https://cloud.githubusercontent.com/assets/5104791/12354814/a257e1c0-bb98-11e5-9469-81c40def8ad4.jpg)
Serait-il possible d'associer un message de confirmation à ce bouton ?

**Comment by kdubuc** [comment]
Et voila https://github.com/SDIS62/prevarisc/commit/930a9fad0acbe0816fe0fb2cc1b70067e5615936
Merci pour le retour ! :wink:

**Comment by olivierbcr** [comment]
C'est parfait ! Les messages d'alertes sont suffisamment explicites pour avertir l'utilisateur afin qu'il ne "détruise" pas par erreur un ordre du jour déjà établi.
Par contre, si l'on veut simplifier la "charge" de calcul du logiciel, seul le message d'alerte "Confirmez vous de ne pas prendre en compte les heures ?" est utile. L'action inverse "prendre en compte les heures" ne présente pas de risque de fausse manipulation.
Encore MERCI pour la mise à disposition de toutes ces corrections et améliorations. J'espère qu'elles seront profitables à toute la communauté. Cordialement.
