### ISSUE TITLE
Colonne DATE_RECEPTION_DOC manquante dans dossierdocmanquant

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#521]
Bonjour,

Suite au commit https://github.com/SDIS62/prevarisc/commit/caa225872caa8379fe6a18eabed92b3d20b7ab43#diff-1a671bab03a416ad9c12844ca17fd66b, nous réalisons que la colonne DATE_RECEPTION_DOC a été  ajoutée au SQL d'init mais est manquante sur le SQL de migration associé.

Avez-vous la possibilité d'ajouter un SQL de migration pour cette colonne ?

Merci !
Vincent MICHEL

**Comment by A511701** [comment]
Bonjour,
Avez-vous eu le temps de voir ce problème ?

**Comment by kdubuc** [comment]
et voila https://github.com/SDIS62/prevarisc/commit/084e922e5d5c7ce13055853931262c9999f51593 :wink:

**Comment by A511701** [comment]
Super !!! Grand merci à vous !
