### ISSUE TITLE
IHM Adresse établissement

### ISSUE THREAD

**Issue by 21Damien** [SDIS62/prevarisc#527]
Bonjour,
Serait-il possible d'afficher le complément d'adresse dans le bloc adresse d'un établissement ?
En effet, lorsque l'on se trouve sur une fichie d'établissement, on a bien la liste d'adresses de ce dernier mais pas le complément qui s'affiche. 
Par exemple indiquer sour l'adresse, le complément en plus petite police.
Merci d'avance.

**Comment by kdubuc** [comment]
C'est fait : https://github.com/SDIS62/prevarisc/commit/6ea95039221b96d1101546bcfe752912a86d77b1
Merci pour le retour :wink:
