### ISSUE TITLE
Changement du cache par défaut

### ISSUE THREAD

**Issue by kdubuc** [SDIS62/prevarisc#530]
APC étant devenu obsolète, une alternative simple devait être trouvée pour remplacer le système de cache par défaut de Prevarisc.

**Un cache basé sur des fichiers est maintenant devenu le cache par défaut de Prevarisc.**

De ce fait, vous allez devoir procéder à une modification de droit du dossier contenant les fichiers cache : 

```
$ cd _path_to_prevarisc_
$ git pull
$ chown www-data:www-data cache
$ chmod 755 cache
```

**Comment by A511701** [comment]
Dans nos installations, nous optimisons ce fonctionnement en déclarant un filesystem de type RAMFS pour optimiser les i/o
