### ISSUE TITLE
Repositionnement Carto

### ISSUE THREAD

**Issue by pcano65** [SDIS62/prevarisc#533]
Il était possible avant la mise à jour du plugin IGN de repositionner le repère sur la carto.
Cela ne l'est plus ...
Merci!

**Comment by olivierbcr** [comment]
Même souci pour nous, lié me semble t-il aux #523 et #531.
On peut toujours saisir longitude et latitude dans l'écran d'ajout d'adresse pour obtenir l'emplacement précis de l'établissement. Mais ce n'est pas simple d'imposer aux préventionnistes d'aller capturer des coordonnées dans une autre application web (géoportail, maps, bing, osm...) pour les rapatrier dans prévarisc !

**Comment by pcano65** [comment]
Erratum !
En fait le repositionnement fonctionne différemment, mais il fonctionne.
Il ne faut pas faire un cliquer-glisser mais juste un cliquer sur la nouvelle position.

**Comment by olivierbcr** [comment]
C'est corrigé chez nous par une nouvelle génération de la clé IGN.
Il ne s'agissait donc pas du même problème.
