### ISSUE TITLE
Question : Auto-génération des identifiants des établissements, du numéro de documents

### ISSUE THREAD

**Issue by regnaulto** [SDIS62/prevarisc#537]
Bonjour,

Je souhaiterai savoir si la création d'un établissement génère automatiquement un identifiant (champ du même nom) type ERP 2 ou type défini par administrateur, ou a contrario si l'identifiant est un champ libre?
Cette question est le mêle lors de la génération des documents

cordialement

**Comment by kdubuc** [comment]
L'identifiant généré par Prevarisc est de type auto incrément. On commence à 1, et l'établissement aura 2, puis 3 et ainsi de suite ... on peut ajouter un ID rentré manuellement dans la fiche établissement.

**Comment by regnaulto** [comment]
merci pour cette information
