### ISSUE TITLE
Question : pourquoi les modèles de convocation en salle sont utilisés pour les groupes de visites ?

### ISSUE THREAD

**Issue by A511701** [SDIS62/prevarisc#540]
Bonjour,

Actuellement, lorsqu'on veut générer une convocation sur l'ODJ d'une date de groupe de visite (pas la commission en salle où est présenté le dossier), le modèle de convocation de commission en salle du membre est utilisé à la place du modèle de convocation en visite.

Est-ce normal /  voulu ?

**Comment by kdubuc** [comment]
poke @MatthieuHANSE

**Comment by A511701** [comment]
Bonjour,

Nous avons eu la confirmation qu'il s'agit d'une anomalie et a été corrigée.
