### ISSUE TITLE
Amélioration - Tri du menu déroulant de sélection du préventionniste (recherche dossiers)

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#546]
Serait-il possible de faire apparaitre les préventionnistes par ordre alphabétique dans le menu déroulant, au niveau des critères de recherche des dossiers ?
![041 - tri preventionniste dans recherche dossiers](https://cloud.githubusercontent.com/assets/5104791/13376597/47caa752-ddc0-11e5-89a8-ee50fb5cbe87.jpg)
Pour notre SDIS il y a 25 noms !

**Comment by kdubuc** [comment]
et voila https://github.com/SDIS62/prevarisc/commit/df2298f606efaba6da6d45c930d1c5c406005bf1 !
