### ISSUE TITLE
Bogue ? - message "fatal error" à survenue aléatoire

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#551]
Lors de la création de nouveaux dossiers ce message d'erreur s'affiche de manière aléatoire, tous les 10 à 15 dossiers environ, sans occasionner de perte de data:
![044 - message fatal error](https://cloud.githubusercontent.com/assets/5104791/13523031/501d9f86-e1f3-11e5-9be2-f5cb9bbc68bf.jpg)
Il suffit de faire retour ou de rafraîchir l'écran pour continuer la saisie.
Avez-vous ce problème ?

**Comment by pcano65** [comment]
Effectivement je confirme. Ça arrive à mes utilisateurs, mais j'attendais de savoir après quelles manip. exactement cela se produisait ...

**Comment by kdubuc** [comment]
Cela est lié au cache. Les autorisations données à l'utilisateur sont stockées dans le cache pour pouvoir être lues directement dans l'affichage des dossiers. Cela peut devenir un problème si le TTL du cache est court. C'est un point sur lequel je reviendrai dans des corrections majeures.
