### ISSUE TITLE
Bogue - Perte du classement des textes dans "Administration / Gestion des textes applicables"

### ISSUE THREAD

**Issue by olivierbcr** [SDIS62/prevarisc#552]
Lors de la modification d'un texte réglementaire celui-ci perd son ordre de classement et se retrouve en bas de liste, quelle que soit soit sa visibilité. Nous sommes donc obligés de reprendre l'ordre de classement des textes même après une modification mineure.
Cela se produit avec toutes les rubriques, sauf celle des "Dispositions spéciales".

**Comment by kdubuc** [comment]
Je confirme que le comportement de ce module est déroutant, mais il restera comme tel, en tous cas au moins jusqu'à la prochaine version majeure.
