### ISSUE TITLE
Mise à jour automatique de l'application

### ISSUE THREAD

**Issue by aechinard** [SDIS62/prevarisc#558]
Bonjour,

Est-il possible d'automatiser la mise à jour de prevarisc de façon à toujours avoir une version à jour ?

Merci à tous pour vos réponses.

**Comment by kdubuc** [comment]
Vous pouvez créer un script, s'executant par exemple tous les lundis, lançant lui même le processus de mise à jour.

Je conseille malgré tout de rester sur un système manuel, pour qu'un "humain" puisse effectuer les manipulations inhérentes aux mises à jour (migrations, gestion du cache etc ..) sans trop d'effets de bord.

**Comment by aechinard** [comment]
D'accord, je vais rester sur des maj manuelles.
En recoupant les informations des différents posts, j'en suis arrivé au raisonnement suivant :
Pour lancer la MAJ : git pull
Si ça ne passe pas, je sauvegarde mes données importées dans le répertoire public puis je tape : 
git fetch --all
git reset --hard origin/master
php composer.phar update -o
php composer.phar self-update

Est-ce correct ?

Merci par avance

**Comment by kdubuc** [comment]
C'est correct ! Les deux dernières commandes concernent composer (l'outil de gestion des dépendances de Prevarisc), mais ça ne fait pas de mal de mettre le tout à jour 😉
