### ISSUE TITLE
PB de Geolocalisation

### ISSUE THREAD

**Issue by aechinard** [SDIS62/prevarisc#559]
Bonjour,

Je n'arrive pas géolocaliser un établissement. Le fond de carte reste vide. Avec le bouton geoportail cela recherche mais rien n'est trouvé. Avec le bouton Nominatim les coordonnées sont trouvées mais la carte reste désespérément vide...

Ma clé IGN est correcte pourtant.

Si l'un d'entre vous à une idée, merci par avance.

**Comment by 21Damien** [comment]
La clé IGN correspond-elle bien au nom de domaine utilisé lorsque vous effectuez les tests ?
Je m'explque. Lorsque l'on déclare une clé IGN pro on doit indiquer l'url du site prevarisc.sdisXX.fr
Lorsque vous accédez à votre Prevarisc il convient d'y accéder par l'adresse déclarée chez IGN à savoir prevarisc.sdisXX.fr

**Comment by aechinard** [comment]
J'ai pris une clé de développement temporaire : 
Nom du contract :Prevarisc
Type de clé :Web
Referer : localhost
Date de souscription : 23/03/2016
Date d'expiration : 21/06/2016
Etat : Actif

et je n'ai pas eu à saisir ce genre d'information.
Je m'y prend peut-etre mal...

**Comment by 21Damien** [comment]
Lorsque vous accédez à Prevarisc quelle URL vous saisissez ?
Pour que la clé de développement  fonctionne il faut que l'url pour accéder à prevarisc soit http://localhost.

**Comment by aechinard** [comment]
Effectivement, cela fonctionne avec http://localhost.
Merci beaucoup pour cette solution.
