### ISSUE TITLE
Erreur sur création/modification IGH

### ISSUE THREAD

**Issue by pcano65** [SDIS62/prevarisc#580]
Voici le message d'erreur que nous avons à la modification d'un IGH (importé) ou lors de la création d'un IGH.
La périodicité d'un IGH est bien renseignée dans le panneau d'admin.

Message: SQLSTATE[HY093]: Invalid parameter number: no parameters were bound, query was: SELECT `periodicite`.`PERIODICITE_PERIODICITE` FROM `periodicite` WHERE (ID_CATEGORIE = ?) AND (ID_TYPE = ?) AND (LOCALSOMMEIL_PERIODICITE = 0) 

Merci pour votre aide.

**Comment by 21Damien** [comment]
Bonjour visiblement il manque le type et la catégorie de l'établissement  (ID_CATEGORIE = ?) AND (ID_TYPE = ?) 
Sont ils bien sélectionnés dans la fiche établissement.
Lors d'un _import _en base bien vérifier  que tous les champs obligatoires prévarisc soient renseignés. Sinon vous allez obtenir des erreurs.

**Comment by pcano65** [comment]
Nous avons aussi l'erreur lors de la création d'un IGH.
D'autre part, sur le formulaire de saisie d'un IGH, il n'y a ni le type ni la catégorie.

**Comment by kdubuc** [comment]
Alors pour expliquer le problème, à la création d'un IGH, Prevarisc va essayer de deviner le classement de votre établissement. Mais il vient contrôler des données non cohérentes avec un IGH (ici, la catégorie). Pouvez vous me confirmer que le problème persiste ?

**Comment by pcano65** [comment]
Oui le problème persiste.
Y a t'il un paramétrage particulier à faire ?
Merci
