### ISSUE TITLE
Evolutions prévues

### ISSUE THREAD

**Issue by regnaulto** [SDIS62/prevarisc#583]
bonjour,

existe t il une liste des évolutions prévues ou attendues ?

cordialement

**Comment by kdubuc** [comment]
Oui, mais je ne peux rien annoncer pour le moment :no_mouth:

**Comment by regnaulto** [comment]
bonjour,

c'est assez génant car dans le cadre d'un développement communautaire, j'aimerais éviter de faire développer des fonctionnalités déjà en cours 

cordialement

**Comment by kdubuc** [comment]
Une des pistes actuellement évoquées en interne est de développer un module DECI : gestion des poteaux d'eau pour suivre le décret du 27 Février 2015 qui modifie la partie réglementaire du Code de la Construction et de l’Habitation
