### ISSUE TITLE
Plantage suite à mise à jour

### ISSUE THREAD

**Issue by aechinard** [SDIS62/prevarisc#593]
Bonjour,

J'ai réalisé une mise à jour de prevarisc via les commandes suivantes : 
git pull => erreur
git fetch --all
git reset --hard origin
php composer.phar update -o
composer.phar self-update
La mise à jour à bien été effectuée mais lorsque j'accède à prevarisc j'ai le message suivant : 
**_Fatal error: Uncaught exception 'Zend_Cache_Exception' with message 'cache_dir "/var/www/prevarisc/public/../application/../cache" is not writable' in /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Cache.php:209 Stack trace: #0 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/var...') #1 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Cache/Backend/File.php(128): Zend_Cache_Backend_File->setCacheDir('/var/www/prevar...') #2 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Cache.php(153): Zend_Cache_Backend_File->__construct(Array) #3 /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('File', Array, false, true) #4 /var/www/prevarisc/application/Bootstrap.php(84): Zend_Cache::factory('Core', 'File', Array, Array, false, false, true) #5 /var/www/prevarisc/application/Bootstrap.php(92): Bootstrap->getCache() #6 /var/www/pre in /var/www/prevarisc/vendor/zendframework/zendframework1/library/Zend/Cache.php on line 209_**
Si je comprends bien, on ne peut écrire dans le dossier cache...

Si quelqu'un à une idée.
Merci par avance

**Comment by SDIS91** [comment]
Bonsoir
Il faut vérifier si les droits d'écriture sur le dossier cache ont changé.

Cordialement

**Comment by kdubuc** [comment]
Ce lien devrait vous aider : https://github.com/SDIS62/prevarisc/issues/530

**Comment by aechinard** [comment]
Les droits en écriture étaient bons sur le dossier cache contenu dans application mais ce n'était pas le bon dossier. J'ai donc remis les droits sur le dossier cache contenu à la racine du dossier prevarisc. Cela a réglé le problème.

Merci à tous les deux pour votre aide.
Je met en résolu.
