### ISSUE TITLE
Probleme Geolocalisation adresse

### ISSUE THREAD

**Issue by sdis12** [SDIS62/prevarisc#594]
Bonjour,

Nous utilisons prevarisc depuis quelques mois et il semblerait que suite à une mise à jour nous rencontrions un problème dans la géolicalisation lors de l'ajout d'une adresse à un établissement.

Quand on rajoute l'adresse, la carte est positionnée sur Rennes. Une fois l'adresse rentrée, quand on clique sur Géolocaliser cette adresse (Geoportail), il s'affiche "Géolocalisation en cours" et rien ne se passe.
Si on utilise via nominatim, on a le résultat : Introuvable.

Cette fonctionnalité marchait au moins avec Nominatim jusqu'a présent.

Auriez vous un idée de la source du problème ?

Merci d'avance pour votre aide.

**Comment by sdis12** [comment]
En testant un peu plus et en revenant sur un version antérieure via git cela refonctionne pour la géolocalisation via nominatim.
Le derniers commit fonctionnel chez nous est le : baa81e3 
Une idée d'où ça peut venir ?

Merci.

**Comment by A511701** [comment]
Bonjour,
La pull request suivante est ouverte depuis 1 mois sur ce sujet et permettra de corriger le problème :
https://github.com/SDIS62/prevarisc/pull/585

Merci,

**Comment by sdis12** [comment]
Merci pour la réponse. J'avais effectivement vu ce pull request. Ne maîtrisant pas bien github je pensais qu'il avait été validé.
Je vais donc repasser sur la version qui fonctionne en attendant.
Merci.

**Comment by kdubuc** [comment]
La PR a été mergée 😉

**Comment by sdis12** [comment]
Je dois le passer en prod mais sur le serveur de test cela semble bien corriger le problème.
Merci encore.

**Comment by A511701** [comment]
J'en profite pour pour demander un merge des autres PR :D

**Comment by kdubuc** [comment]
Toujours ce problème de rebase ... :confused:
