### ISSUE TITLE
Demande d'aide pour l'authentification par LDAP

### ISSUE THREAD

**Issue by aechinard** [SDIS62/prevarisc#607]
Bonjour,

J'ai besoin d(un petit coup de main pour pouvoir authentifier les utilisateurs avec le LDAP.
Quels sont les paramètres à mettre dans le fichier vhost ?
Mon domaine est ddsis. Cela doit correspondre au paramètre SetEnv PREVARISC_LDAP_BASEDN DC=ddsis

Si quelqu'un peut me donner un coup de main. Merci par avance.

**Comment by aechinard** [comment]
Personne n'utilise le LDAP ?

**Comment by bernardgalasso** [comment]
Bonjour.

Il suffit de définir ces valeurs dans /etc/httpd/conf/prevarisc/https-prevarisc-config.conf
SetEnv PREVARISC_LDAP_ENABLEB "1"
SetEnv PREVARISC_LDAP_HOST "<nomduserveur ou adresseip>"
SetEnv PREVARISC_LDAP_USERNAME "<user>"
SetEnv PREVARISC_LDAP_PASSWORD "<password>"
SetEnv PREVARISC_LDAP_BASEDN "<dn de base>"

Ça fonctionne à merveille avec notre AD windows.
Attention toutefois, la connexion doit se faire avec un utilisateur possédant les droits d'accès au LDAP.

**Comment by bernardgalasso** [comment]
Il faut remplir entre les guillemets avec les caractéristiques spécifiques à votre environnement.

**Comment by aechinard** [comment]
Bonjour,

Merci pour ces infos. C'est bien ce que j'avais fait mais je ne trouve pas le dossier httpd dans etc
J'utilise celui qui est dans etc/apache2/site-enabled

SetEnv PREVARISC_LDAP_ENABLED 1
SetEnv PREVARISC_LDAP_HOST 192.168.0.10
SetEnv PREVARISC_LDAP_PORT 389
SetEnv PREVARISC_LDAP_USERNAME root
SetEnv PREVARISC_LDAP_PASSWORD password
SetEnv PREVARISC_LDAP_BASEDN DC=ddsis, DC=local

**Comment by aechinard** [comment]
Pour la dernière ligne c'est bien DC=ddsis et pas DS

**Comment by bernardgalasso** [comment]
Le fichier de conf est à un autre endroit, selon comment Prevarisc est installé, c'est normal.
Pour la version avec laquelle je travaille, on encapsule les données par des "
Avez-vous essayé d'encapsuler ?
Attention à redémarrer Apache après chaque modif

**Comment by bernardgalasso** [comment]
Un petit fichier php permet de faire les tests du bind LDAP.
php - bases HTML
faire un $conn = ldap_connect($ldap, $port);
ldap_set_option ($conn, LDAP_OPS_PROTOCOL_VERSION, 3);
$bound = ldap_bind($conn, $user,$pass);
echo($bound);
pied HTML

**Comment by bernardgalasso** [comment]
[testldap.txt](https://github.com/SDIS62/prevarisc/files/521589/testldap.txt)

**Comment by bernardgalasso** [comment]
Adaptez ce fichier (user, password, ad) en fonction de votre système er renommez le en .php. Si vous pouvez faire un bind, vous obtiendrez un 1 dans la page web, sinon elle restera blanche.

**Comment by aechinard** [comment]
Merci beaucoup pour votre aide.
Malheureusement cela ne fonctionne toujours pas.
J'ai le message d'erreur suivant avec le fichier testldap.php : php Warning: ladap_bind(): Unable to bind to server: Invalid credentials in /home/user/testldap.php on line 11
Cette ligne correspond à la commande $bound = ldap_bind($conn, $user, $pass);

Si vous avez une petite idée du problème....

Merci encore.

**Comment by bernardgalasso** [comment]
Bonjour. 

Notez que nous utilisons un AD microsoft. Avec un openLdap, je ne connais pas. 

Pour pouvoir "binder" le LDAP, avec un AD, nous avons déclaré un utilisateur étant Administrateur du domaine. 
Il existe peut-être des droits plus précis pour cela, mais mes admins n'ont pas trouvé. 

Sinon, je ne vois pas de quoi ça peut venir. 

Cordialement 

PM Bernard GALASSO 
Service SIC - Secteur Informatique 
Section Systèmes d'Informations 
04 95 05 44 34 - 8 5834 
bernard.galasso@bmpm.gouv.fr 

----- Mail original -----

De: "aechinard" notifications@github.com 
À: "SDIS62/prevarisc" prevarisc@noreply.github.com 
Cc: "GALASSO Bernard" bernard.galasso@bmpm.gouv.fr, "Comment" comment@noreply.github.com 
Envoyé: Mardi 11 Octobre 2016 17:05:25 
Objet: Re: [SDIS62/prevarisc] Demande d'aide pour l'authentification par LDAP (#607) 

Merci beaucoup pour votre aide. 
Malheureusement cela ne fonctionne toujours pas. 
J'ai le message d'erreur suivant avec le fichier testldap.php : php Warning: ladap_bind(): Unable to bind to server: Invalid credentials in /home/user/testldap.php on line 11 
Cette ligne correspond à la commande $bound = ldap_bind($conn, $user, $pass); 
Si vous avez une petite idée du problème.... 
Merci encore.

**Comment by aechinard** [comment]
Bonjour,

J'utilise également un administrateur du domaine qui est prévu à cet effet, mais quelque chose bloque...

Merci pour votre aide qui a permis de faire avancer un peu plus la résolution du problème.

Cordialement

**Comment by bernardgalasso** [comment]
Un autre détail que vous pouvez tester : préfixer le nom d'utilisateur avec le nom du domaine ($user=" DOMAINE \root") 

PM Bernard GALASSO 
Service SIC - Secteur Informatique 
Section Systèmes d'Informations 
04 95 05 44 34 - 8 5834 
bernard.galasso@bmpm.gouv.fr 

----- Mail original -----

De: "aechinard" notifications@github.com 
À: "SDIS62/prevarisc" prevarisc@noreply.github.com 
Cc: "GALASSO Bernard" bernard.galasso@bmpm.gouv.fr, "Comment" comment@noreply.github.com 
Envoyé: Mercredi 12 Octobre 2016 08:55:16 
Objet: Re: [SDIS62/prevarisc] Demande d'aide pour l'authentification par LDAP (#607) 

Bonjour, 
J'utilise également un administrateur du domaine qui est prévu à cet effet, mais quelque chose bloque... 
Merci pour votre aide qui a permis de faire avancer un peu plus la résolution du problème. 
Cordialement

**Comment by aechinard** [comment]
Merci beaucoup, maintenant cela fonctionne, j'ai donc les bons réglages qu'il faut que je transpose à la config LDAP de prevarisc.

> $user = "ddsis\Administrateur";
> $pass = "password";
> $ad = "192.168.0.10";
> $adport = "389";

Par contre cela ne fonctionne pas avec prevarisc.

> SetEnv PREVARISC_LDAP_HOST " 192.168.0.10"
> SetEnv PREVARISC_LDAP_PORT "389"
> SetEnv PREVARISC_LDAP_USERNAME = "ddsis\Administrateur"
> SetEnv PREVARISC_LDAP_PASSWORD "password"
> SetEnv PREVARISC_LDAP_ENABLED "1"

Je n'ai pas mis

> SetEnv PREVARISC_LDAP_BASEDN "DC=ddsis, DC=local"

puisque cela fonctionnait avec le script sans cela.
J'ai un doute sur la syntaxe...

**Comment by bernardgalasso** [comment]
Il faut garder la ligne SetEnv PREVARISC_LDAP_BASEDN "DC=ddsis, DC=local" 

En fait, le php que j'avais transmis ne concerne que la connexion au LDAP, pas les fonctions de recherche. 

Une fois connecté, Prévarisc recherche l'utilisateur dans le LDAP à partir de ce DN de base. 

En gros : 
- connexion LDAP en administrateur (ldap_connect) 
- recherche de l'utilisateur, récupération ou vérification des objets le concernant (ldap_bind) 

PM Bernard GALASSO 
Service SIC - Secteur Informatique 
Section Systèmes d'Informations 
04 95 05 44 34 - 8 5834 
bernard.galasso@bmpm.gouv.fr 

----- Mail original -----

De: "aechinard" notifications@github.com 
À: "SDIS62/prevarisc" prevarisc@noreply.github.com 
Cc: "GALASSO Bernard" bernard.galasso@bmpm.gouv.fr, "Comment" comment@noreply.github.com 
Envoyé: Mercredi 12 Octobre 2016 10:13:41 
Objet: Re: [SDIS62/prevarisc] Demande d'aide pour l'authentification par LDAP (#607) 

Merci beaucoup, maintenant cela fonctionne, j'ai donc les bons réglages qu'il faut que je transpose à la config LDAP de prevarisc. 

$user = "ddsis\Administrateur"; 
$pass = "password"; 
$ad = "192.168.0.10"; 
$adport = "389"; 

Par contre cela ne fonctionne pas avec prevarisc. 

<blockquote>
SetEnv PREVARISC_LDAP_HOST " 192.168.0.10" 
SetEnv PREVARISC_LDAP_PORT "389" 
SetEnv PREVARISC_LDAP_USERNAME = "ddsis\Administrateur" 
SetEnv PREVARISC_LDAP_PASSWORD "password" 
SetEnv PREVARISC_LDAP_ENABLED "1" 
</blockquote>

Je n'ai pas mis 

<blockquote>
SetEnv PREVARISC_LDAP_BASEDN "DC=ddsis, DC=local" 
puisque cela fonctionnait avec le script sans cela. 
J'ai un doute sur la syntaxe... 
</blockquote>

**Comment by aechinard** [comment]
D'accord j'ai tout remis.
Est-ce que le problème ne viendrait pas de la connexion https. J'ai bien changé le port par défaut en 443 mais cela ne fonctionne pas plus pour autant...
Est-il possible de configurer cette connexion LDAP ailleurs que dans les paramètres de prevarisc, dans LDAP.conf peut-être ?

**Comment by bernardgalasso** [comment]
https c'est pour la partie client. Pour le LDAP de Prévarisc, tout se configure à ma connaissance dans Prévarisc. 

Quel est votre problème exactement ? 

PM Bernard GALASSO 
Service SIC - Secteur Informatique 
Section Systèmes d'Informations 
04 95 05 44 34 - 8 5834 
bernard.galasso@bmpm.gouv.fr 

----- Mail original -----

De: "aechinard" notifications@github.com 
À: "SDIS62/prevarisc" prevarisc@noreply.github.com 
Cc: "GALASSO Bernard" bernard.galasso@bmpm.gouv.fr, "Comment" comment@noreply.github.com 
Envoyé: Mercredi 12 Octobre 2016 10:57:19 
Objet: Re: [SDIS62/prevarisc] Demande d'aide pour l'authentification par LDAP (#607) 

D'accord j'ai tout remis. 
Est-ce que le problème ne viendrait pas de la connexion https. J'ai bien changé le port par défaut en 443 mais cela ne fonctionne pas plus pour autant... 
Est-il possible de configurer cette connexion LDAP ailleurs que dans les paramètres de prevarisc, dans LDAP.conf peut-être ?

**Comment by aechinard** [comment]
Effectivement cela ne fonctionne pas non plus sans ssl.
J'ai le message suivant : Erreur d'authentification Les identifiants ne correspondent pas.
Pourtant mon login et mot de passe sont ceux que j'utilise avec ma session. Connexion LDAP est bien activée avec mon compte sur prevarisc.

**Comment by bernardgalasso** [comment]
L'utilisateur est bien en base de données Prévarisc (table utilisateur) ? 
login = USERNAME_UTILISATEUR 
PASSWD_UTILISATEUR = Null 
ACTIF_UTILISATEUR = 1 

Dans l'AD, il est bien taggué user et dans la branche du domaine déclarée dans le BASE_DN ? 

PM Bernard GALASSO 
Service SIC - Secteur Informatique 
Section Systèmes d'Informations 
04 95 05 44 34 - 8 5834 
bernard.galasso@bmpm.gouv.fr 

----- Mail original -----

De: "aechinard" notifications@github.com 
À: "SDIS62/prevarisc" prevarisc@noreply.github.com 
Cc: "GALASSO Bernard" bernard.galasso@bmpm.gouv.fr, "Comment" comment@noreply.github.com 
Envoyé: Mercredi 12 Octobre 2016 11:32:36 
Objet: Re: [SDIS62/prevarisc] Demande d'aide pour l'authentification par LDAP (#607) 

Effectivement cela ne fonctionne pas non plus sans ssl. 
J'ai le message suivant : Erreur d'authentification Les identifiants ne correspondent pas. 
Pourtant mon login et mot de passe sont ceux que j'utilise avec ma session. Connexion LDAP est bien activée avec mon compte sur prevarisc.

**Comment by aechinard** [comment]
Pour la table Utilisateur de la base de données Prévarisc c'est bon.
Dans l'AD je ne sais pas, je vais voir mon collègue qui gère l'AD.

**Comment by bernardgalasso** [comment]
Si vous avez un user "admin du domaine", l'application LdapAdmin trouvable sur internet vous permettra de regarder. 

PM Bernard GALASSO 
Service SIC - Secteur Informatique 
Section Systèmes d'Informations 
04 95 05 44 34 - 8 5834 
bernard.galasso@bmpm.gouv.fr 

----- Mail original -----

De: "aechinard" notifications@github.com 
À: "SDIS62/prevarisc" prevarisc@noreply.github.com 
Cc: "GALASSO Bernard" bernard.galasso@bmpm.gouv.fr, "Comment" comment@noreply.github.com 
Envoyé: Mercredi 12 Octobre 2016 14:09:08 
Objet: Re: [SDIS62/prevarisc] Demande d'aide pour l'authentification par LDAP (#607) 

Pour la table Utilisateur de la base de données Prévarisc c'est bon. 
Dans l'AD je ne sais pas, je vais voir mon collègue qui gère l'AD.

**Comment by aechinard** [comment]
Bon, effectivement je peux me connecter à l'AD en administrateur avec l'application LdapAdmin.
Mon login qui se présente sous la forme echinarda est renseigné CN=ECHINARD Arnaud dans LDAP.
Malgré la modif dans Prévaric cela ne fonctionne pas mieux...

**Comment by bernardgalasso** [comment]
Normalement, il faut que l'utilisateur soit "echinarda " 
L'authentification devrait se faire sur le sAMAccountName 

Cet utilisateur est bien dans une arborescence du BASE_DN ? 

PM Bernard GALASSO 
Service SIC - Secteur Informatique 
Section Systèmes d'Informations 
04 95 05 44 34 - 8 5834 
bernard.galasso@bmpm.gouv.fr 

----- Mail original -----

De: "aechinard" notifications@github.com 
À: "SDIS62/prevarisc" prevarisc@noreply.github.com 
Cc: "GALASSO Bernard" bernard.galasso@bmpm.gouv.fr, "Comment" comment@noreply.github.com 
Envoyé: Mercredi 12 Octobre 2016 15:32:53 
Objet: Re: [SDIS62/prevarisc] Demande d'aide pour l'authentification par LDAP (#607) 

Bon, effectivement je peux me connecter à l'AD en administrateur avec l'application LdapAdmin. 
Mon login qui se présente sous la forme echinarda est renseigné CN=ECHINARD Arnaud dans LDAP. 
Malgré la modif dans Prévaric cela ne fonctionne pas mieux...

**Comment by aechinard** [comment]
Il est présent dans :
OU=Utilisateur et Groupes -> OU=Groupements Fonctionnels -> OU=Groupement Moyens Techniques -> OU=Tti -> CN=ECHINARD Arnaud

Ou puis-je trouver BASE_DN ?

**Comment by bernardgalasso** [comment]
Il faut regarder la fin du distinguishedName dans l'AD. 

Il faut que ça finisse par le BASE_DN défini dans Prévarisc 

Vu l'architecture que vous aviez fourni, je dirais que ça devrait donner "OU=Utilisateurs et Groupes, DS=ddsis, DC=local" 

Je ne connais pas la notation DS, ça n'est pas une erreur de frappe ? 

Dans nos fichier de configuration, on a SetEnv PREVARISC_LDAP_BASEDN "OU=XXX,DC=XXX,DC=XXX,DC=FR" 
C'est encapsulé par des " , ça commence par OU et il n'y a pas d'espaces délimitant les , 

Pour vous, je testerais avec SetEnv PREVARISC_LDAP_BASEDN " OU=Utilisateurs et Groupes,DC=ddsis,DC=local " 

Avec LdapAdmin, vous devez avoir votre distinguishedName qui ressemble à " CN=ECHINARD Arnaud,OU=Tti,OU=Groupement Moyens Techniques,OU=Groupements Fonctionnels,OU=Utilisateur et Groupes,DC=ddsis,DC=local " 

PM Bernard GALASSO 
Service SIC - Secteur Informatique 
Section Systèmes d'Informations 
04 95 05 44 34 - 8 5834 
bernard.galasso@bmpm.gouv.fr 

----- Mail original -----

De: "aechinard" notifications@github.com 
À: "SDIS62/prevarisc" prevarisc@noreply.github.com 
Cc: "GALASSO Bernard" bernard.galasso@bmpm.gouv.fr, "Comment" comment@noreply.github.com 
Envoyé: Mercredi 12 Octobre 2016 16:36:05 
Objet: Re: [SDIS62/prevarisc] Demande d'aide pour l'authentification par LDAP (#607) 

Il est présent dans : 
OU=Utilisateur et Groupes -> OU=Groupements Fonctionnels -> OU=Groupement Moyens Techniques -> OU=Tti -> CN=ECHINARD Arnaud 
Ou puis-je trouver BASE_DN ?

**Comment by aechinard** [comment]
Oui c'est bien cela et il y a bien une erreur sur DS qui est DC (faute de frappe).
Le distinguishedName est :

> CN=ECHINARD Arnaud,OU=Tti,OU=Groupement Moyens Techniques,OU=Groupements Fonctionnels,OU=Utilisateurs et Groupes,DC=ddsis,DC=local

J'ai modifié en conséquence la ligne :

> SetEnv PREVARISC_LDAP_BASEDN " OU=Utilisateurs et Groupes,DC=ddsis,DC=local "

mais c'est toujours pareil, l'authentification ne correspond pas.
Dois-je me connecter comme ma session Windows avec echinarda ou avec ECHINARD Arnaud ?

**Comment by bernardgalasso** [comment]
De ce qu'il y a dans le Framework Zend, je dirais avec le sAMAccountName : echinarda 

PM Bernard GALASSO 
Service SIC - Secteur Informatique 
Section Systèmes d'Informations 
04 95 05 44 34 - 8 5834 
bernard.galasso@bmpm.gouv.fr 

----- Mail original -----

De: "aechinard" notifications@github.com 
À: "SDIS62/prevarisc" prevarisc@noreply.github.com 
Cc: "GALASSO Bernard" bernard.galasso@bmpm.gouv.fr, "Comment" comment@noreply.github.com 
Envoyé: Jeudi 13 Octobre 2016 10:09:17 
Objet: Re: [SDIS62/prevarisc] Demande d'aide pour l'authentification par LDAP (#607) 

Oui c'est bien cela et il y a bien une erreur sur DS qui est DC (faute de frappe). 
Le distinguishedName est : 

CN=ECHINARD Arnaud,OU=Tti,OU=Groupement Moyens Techniques,OU=Groupements Fonctionnels,OU=Utilisateurs et Groupes,DC=ddsis,DC=local 

J'ai modifié en conséquence la ligne : 

<blockquote>
SetEnv PREVARISC_LDAP_BASEDN " OU=Utilisateurs et Groupes,DC=ddsis,DC=local " 
</blockquote>

mais c'est toujours pareil, l'authentification ne correspond pas. 
Dois-je me connecter comme ma session Windows avec echinarda ou avec ECHINARD Arnaud ?

**Comment by aechinard** [comment]
Bonjour,

J'ai réussi à obtenir un message plus précis sur les raisons de cet échec de connexion : 

> 0x31 (Invalid credentials; 80090308: LdapErr: DSID-0C0903A8, comment: AcceptSecurityContext error, data 52e, v1db1): administrateur

Malheureusement cela ne m'en dit pas beaucoup plus. Il semblerait qu'il manque quelque chose dans la chaine de connexion...

**Comment by aechinard** [comment]
J'ai trouvé !!!

Cela venait de l'absence du paramètre suivant dans le fichier de config : 

> SetEnv PREVARISC_NTLM_ENABLED 1

Maintenant cela fonctionne avec l'authentification en LDAP.

Merci pour votre aide.
