### ISSUE TITLE
Erreur "SebastianBergmann\Git not found"

### ISSUE THREAD

**Issue by SDIS91** [SDIS62/prevarisc#609]
Bonjour

Aprè le dernier pull du 23/08, nous avons eu une erreur au lancement de Prevarisc:

`Fatal error: Class 'SebastianBergmann\Git' not found in /home/www/prevarisc/application/plugins/View.php on line 24`

J'ai du remodifier cette ligne 24 de:
`$git = new SebastianBergmann\Git(APPLICATION_PATH . DS . '..');`
à:
`$git = new SebastianBergmann\Git\Git(APPLICATION_PATH . DS . '..');`

Pour dépasser l'erreur momentanément.
Comment régler le problème?

Merci d'avance

**Comment by kdubuc** [comment]
Lancez un `composer update -o` pour mettre à jour les dépendances

**Comment by SDIS91** [comment]
Le problème est résolu.

Merci beaucoup
