### ISSUE TITLE
Écran blanc après connexion à Prevarisc

### ISSUE THREAD

**Issue by jeremyk6** [SDIS62/prevarisc#621]
Bonjour,

j'ai installé Prevarisc en suivant le guide d'installation sur un de nos serveurs mais j'ai un écran blanc après connexion root. En consultant /var/log/apache2/error.log, j'ai le message:

`[Wed Sep 28 10:53:37.118247 2016] [:error] [pid 7597] [client 192.168.10.165:50188] PHP Fatal error:  Call to a member function isAllowed() on boolean in /var/www/prevarisc/application/controllers/IndexController.php on line 19`

Je ne pense pas avoir de problème de droit (j'accède à la page de connexion de Prevarisc) ni de connexion à la BdD (le message d'erreur est clair si les paramètres de connexions BdD sont incorrects et la connexion est refusée si le salt ne correspond pas). Je joins mon prevarisc.conf au cas où ([prevarisc.conf](https://github.com/SDIS62/prevarisc/files/497558/prevarisc.conf.txt)).

Si quelqu'un voit où se situe le problème, merci par avance !

**Comment by aechinard** [comment]
Bonjour,
Il manque quelques paramètres dans votre fichier de config...
Déjà   SetEnv PREVARISC_DB_HOST 127.0.0.1 n'autorise que la connexion depuis le serveur et pas d'une machine distante. Ce doit être l'IP de votre serveur sur le réseau.
Je ne sais si c'est bloquant mais comme vous n'utilisez pas le LDAP il faudrait peut-être renseigner à minima SetEnv PREVARISC_LDAP_ENABLED 0
Pour le mot de passe de la BDD, SetEnv PREVARISC_DB_PASSWORD *******\* doit être en clair dans le fichier.
Avez-vous fait les commandes a2dissite puis a2ensite prevarisc.sdis23.com et n'avez-vous pas mélangé le nom de l''application avec  prevarisc.sdis23.fr dans un fichier de config.

En espérant vous avoir un peu aidé...

**Comment by kdubuc** [comment]
Vous avez un problème de cache. En effet, la matrice des droits est chargée dans le cache car c'est une opération couteuse. Quand Prevarisc demande un droit d'accès il fait appel à la fonction `isAllowed()`. Au lieu de vous retourner la matrice, il vous retourne un statut d'erreur, ce qui est inattendu et fait donc crasher Prevarisc. Vérifiez que votre dossier /var/cache/prevarisc est bien accessible pour l'utilisateur www-data.

**Comment by jeremyk6** [comment]
www-data est de propriétaire /var/cache/prevarisc, j'ai fait un chmod 750 sur le dossier mais rien n'y fait, le problème reste le même.

**Comment by kdubuc** [comment]
Essayez de rajouter l'option PREVARISC_CACHE_LIFETIME avec comme valeur : 3600

**Comment by jeremyk6** [comment]
Super, c'était ça. Merci beaucoup !
