### ISSUE TITLE
Duplication des informations d'un établissement dans la table lors d'une modification

### ISSUE THREAD

**Issue by aechinard** [SDIS62/prevarisc#634]
Bonjour,

Je ne sais si c'est normal mais lorsque l'on modifie des informations sur un établissement, celles-ci ne sont pas modifiées dans la table `etablissementinformations` car une nouvelle ligne est créée à la fin de cette table. Ainsi les informations avant modification sont toujours présentes dans la table mais devenues inutiles.

Cela ne risque t-il pas d'encombrer la table à la longue ?
Pourquoi ne pas faire un UPDATE sur l'ID_ETABLISSEMENTINFORMATIONS ?

Merci par avance.

**Comment by SDIS83Loic** [comment]
Bonjour,

effectivement à chaque modification l'enregistrement précédent n'est pas mis à jour, c'est un nouveau qui est crée.
C'est une technique de développement qui permet d'avoir historique des modifications d'un établissement.
Il existe d'autre technique mais c'est celle-ci qui a été retenu par les développeurs. 
La recherche se fait sur la date de modification la plus grande.

Le risque d'encombrement existe mais il est la contrepartie de l'historique comme nos archives papiers.
Cela pourra faire partie d'une maintenance préventive tous les années avenir.

**Comment by aechinard** [comment]
Bonjour,

D'accord je n'avais pas vu les choses sous cet angle... Ce n'est donc pas un bug.

Merci pour l'info.
