### ISSUE TITLE
Problème dans la génération de statistiques.

### ISSUE THREAD

**Issue by sdis12** [SDIS62/prevarisc#638]
Bonjour,

Nous rencontrons un problème sur la requete d'extraction 4 : Liste ERP avec des visites periodiques sur 1 an.
Lorsque nous executons la requetes, nous avons un message : Generation en cours...
Le résultat ne s'affiche jamais.
Les autres extractions fonctionnent.

En regardant un peu dans les log nous avons cette erreur sur apache :
PHP Fatal error:  Call to undefined function Zend_Db_Expr() in /var/www/prevarisc/application/models/DbTable/Statistiques.php on line 87, referer: http://prevarisc.sdis12.fr/statistiques

En regardant dans le code il semblerait qu'il y ai un problème au niveau de la requete SQL. Avez vous le même problème ?

Merci pour votre aide.

**Comment by aechinard** [comment]
Bonjour,

C'est peut-être un peu tard mais voici la solution : 

Sur le fichier /var/www/prevarisc/application/models/DbTable/Statistiques.php à la ligne 87, il faut rajouter "new" au début de la requête : "ARRONDISSEMENT" => **new** Zend_DFb_Expr......
Enregistrez le fichier et tout devrait rentrer dans l'ordre.

**Comment by sdis12** [comment]
Bonjour,

Merci pour votre reponse qui résoud effectivement le problème !
