### ISSUE TITLE
Probleme de sauvegarde de l'adresse d'un établissement

### ISSUE THREAD

**Issue by Pirago** [SDIS62/prevarisc#665]
Bonjour,
Il m'est impossible de sauvegarder l'adresse d'un établissement dans la BD.
Je renseigne bien la commune et l'adresse, je géolocalise bien le lieu avec géoportail et pourtant si je sauvegarde mon établissement et que je retourne dessus je n'ai pas d'adresse et la table "etablissementadresse" dans la base de donnée reste vide.

Merci d'avance

**Comment by CO16** [comment]
Bonjour,

il faut que la commune en question ainsi que la rue soient référencées dans la base de données de Prevarisc. Pour être certain que ce soit le cas, Prevarisc est censé afficher un menu déroulant avec des propositions suite à la saisie de la commune et de la rue (sorte de saisie intuitive). Il faut alors cliquer sur les éléments proposés. Dans le cas contraire, l'adresse n'est pas enregistrée lorsqu'on enregistre l'établissement. C'est d'ailleurs trompeur car il n'y a aucun signalement de l'erreur.

Pour faire fonctionner le mécanisme, il faut donc alimenter (généralement de manière automatique depuis le SIG) les tables relatives aux adresses dans la base de données Prevarisc.

**Comment by Pirago** [comment]
Merci de votre réponse !
Effectivement, après avec rentrer les adresses ça garde bien tout en mémoire ! 
Merci beaucoup !
