### ISSUE TITLE
Gérer l'affichages des avis dans dossier

### ISSUE THREAD

**Issue by kdubuc** [SDIS62/prevarisc#86]
Pour les « études », seuls les avis : favorable, défavorable
Pour les « visite avant ouverture » et « visite de réception » : favorable, défavorable, n’a pu se prononcer
Pour les « visite périodique », «  visite de contrôle » et « visite inopinée » : : favorable, défavorable, avis différé (dans le cas de l’avis différé, une alerte doit exister sur ledit dossier)

**Comment by sla33** [comment]
Nous utilisons la version 2 (beta) du 24 juin 2014
Dans la table "avis" de Prevarisc, nous n'avons maintenant plus que 2 entrées :
1   Favorable
2   Défavorable
Alors qu'avant nous en avions 4
Etes-vous revenus sur le choix décrit plus haut d'avoir également des avis "n'a pu se prononcer" et "différé" ? Quand avez-vous effectué ce changement ? Pour la repirse des données nous avions besoin de "n'a pu se prononcer"
