### ISSUE TITLE
Probleme mise à jour 1.2 - dependance composer

### ISSUE THREAD

**Issue by SDIS83Loic** [SDIS62/prevarisc#94]
Lors de l'installation de la dépendance du composer, il y a une erreur d’exécution de l'installation du composer.phar.

[RuntimeException]
  Failed to clone https://github.com/kdubuc/odtphp.git, git was not found, check that it is installed and in
   your PATH env.

  sh: git: not found

**Comment by kdubuc** [comment]
Il faut installer git sur votre serveur (aptitude install git ou l'utilitaire git scm sur Windows)
