### ISSUE TITLE
Le schéma de base de données  n'est plus à jour

### ISSUE THREAD

**Issue by fbeauchamp** [SDIS62/prevarisc#99]
Bonjour,

la nouvelle matrice des droits semble s'appuyer sur la table prevarisc.resource qui n'est pas défini dans le model SQL

Merci

**Comment by kdubuc** [comment]
la table est définie dans le fichier mwb
Il faut faire un forward pour récupérer les valeurs par défaut

**Comment by fbeauchamp** [comment]
ok , j'ai resynchronisé le schéma de base de données ( pour ne pas casser ce que nous avions déjà saisi). 

Peut être faudra t il ajouter une  partie migration dans la doc : penser à mettre à jour le schéma de base de données et les dépendances du composer.

Merci

**Comment by A511701** [comment]
La table "admin" est toujours manquante, ce qui empêche la modification des utilisateurs cf #109

**Comment by kdubuc** [comment]
Qu'elle soit manquante est normal, par contre le bug se situe bien dans le controller : il essaie de chercher des paramètres LDAP en base, alors que ceux ci sont dans un .ini.
C'est pour cela que je close ici, et je laisse ouvert de l'autre côté, le patch arrive lundi normalement.

**Comment by A511701** [comment]
Super ! Merci beaucoup !
